-- ============================================================
-- YONA — profils virtuels : fichier 2 sur 10
-- 75 profils : Gabon, Cameroun, Congo-Brazzaville.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.ga.01@profils-virtuels.yona.invalid","first_name":"Prisca","last_name":"Ondo","gender":"female","birth_date":"1997-10-29","country":"Gabon","region":"Estuaire","city":"Libreville","bio":"Souriante et attentionnée, j'aime la cuisine et la louange. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Louange","Cuisine"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.ga.02@profils-virtuels.yona.invalid","first_name":"Steeve","last_name":"Mintsa","gender":"male","birth_date":"2000-04-03","country":"Gabon","region":"Ogooué-Maritime","city":"Port-Gentil","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Louange","Voyages"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.ga.03@profils-virtuels.yona.invalid","first_name":"Rachel","last_name":"Obiang","gender":"female","birth_date":"1986-04-18","country":"Gabon","region":"Haut-Ogooué","city":"Franceville","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. J'enseigne à l'école du dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Voyages","Musique","Cinéma","Mode"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.ga.04@profils-virtuels.yona.invalid","first_name":"Brice","last_name":"Bivigou","gender":"male","birth_date":"1979-03-27","country":"Gabon","region":"Woleu-Ntem","city":"Oyem","bio":"Posé mais déterminé, j'aime les voyages, le cinéma et les longues discussions. Je joue dans le groupe de louange de mon église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Voyages","Cinéma"],"denomination":"Protestante (Église évangélique du Gabon)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.ga.05@profils-virtuels.yona.invalid","first_name":"Murielle","last_name":"Nzé","gender":"female","birth_date":"2000-07-14","country":"Gabon","region":"Haut-Ogooué","city":"Moanda","bio":"Je suis une femme simple, passionnée par la mode et la cuisine. La prière rythme mes journées. J'attends un homme de foi, doux et responsable.","interests":["Cuisine","Nature","Mode","Bénévolat"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.ga.06@profils-virtuels.yona.invalid","first_name":"Wilfried","last_name":"Moussavou","gender":"male","birth_date":"1983-01-30","country":"Gabon","region":"Ngounié","city":"Mouila","bio":"Calme et joyeux, je partage mon temps entre mon travail et la lecture. La prière rythme mes journées. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Lecture"],"denomination":"Protestante (Église évangélique du Gabon)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":34,"max_age":52},
{"email":"virtuel.ga.07@profils-virtuels.yona.invalid","first_name":"Vanessa","last_name":"Nzamba","gender":"female","birth_date":"1992-05-13","country":"Gabon","region":"Moyen-Ogooué","city":"Lambaréné","bio":"Fille de Dieu avant tout, je trouve ma joie dans la mode et la danse. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Mode","Danse"],"denomination":"Protestante (Église évangélique du Gabon)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.ga.08@profils-virtuels.yona.invalid","first_name":"Arnaud","last_name":"Mapangou","gender":"male","birth_date":"2001-03-27","country":"Gabon","region":"Nyanga","city":"Tchibanga","bio":"Calme et joyeux, je partage mon temps entre mon travail et la lecture. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Cinéma"],"denomination":"Protestante (Église évangélique du Gabon)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.ga.09@profils-virtuels.yona.invalid","first_name":"Ursule","last_name":"Ekomi","gender":"female","birth_date":"2001-12-03","country":"Gabon","region":"Ogooué-Lolo","city":"Koulamoutou","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Nature","Voyages","Cuisine"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.ga.10@profils-virtuels.yona.invalid","first_name":"Landry","last_name":"Mba","gender":"male","birth_date":"1999-08-29","country":"Gabon","region":"Ogooué-Ivindo","city":"Makokou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de voyages. Je sers à l'accueil de mon église le dimanche. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Cuisine","Lecture","Voyages"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.ga.11@profils-virtuels.yona.invalid","first_name":"Larissa","last_name":"Ndong","gender":"female","birth_date":"1989-01-21","country":"Gabon","region":"Estuaire","city":"Ntoum","bio":"Douce mais déterminée, j'aime la cuisine, la photographie et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Photographie","Cuisine"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.ga.12@profils-virtuels.yona.invalid","first_name":"Junior","last_name":"Ella","gender":"male","birth_date":"1995-02-19","country":"Gabon","region":"Estuaire","city":"Libreville","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de sport. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Danse","Cuisine","Photographie"],"denomination":"Protestante (Église évangélique du Gabon)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.ga.13@profils-virtuels.yona.invalid","first_name":"Dorcas","last_name":"Nguema","gender":"female","birth_date":"2002-04-12","country":"Gabon","region":"Ogooué-Maritime","city":"Port-Gentil","bio":"Chaque journée est un cadeau de Dieu : je la remplis de mode et de musique. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Mode","Musique"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.ga.14@profils-virtuels.yona.invalid","first_name":"Fabrice","last_name":"Ognane","gender":"male","birth_date":"1983-11-04","country":"Gabon","region":"Haut-Ogooué","city":"Franceville","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de photographie. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Lecture"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":34,"max_age":52},
{"email":"virtuel.ga.15@profils-virtuels.yona.invalid","first_name":"Christelle","last_name":"Bouanga","gender":"female","birth_date":"1993-01-31","country":"Gabon","region":"Woleu-Ntem","city":"Oyem","bio":"Fille de Dieu avant tout, je trouve ma joie dans la musique et la photographie. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Photographie"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.ga.16@profils-virtuels.yona.invalid","first_name":"Yannick","last_name":"Mouketou","gender":"male","birth_date":"2001-03-18","country":"Gabon","region":"Haut-Ogooué","city":"Moanda","bio":"Fils de Dieu avant tout, je trouve ma joie dans les voyages et la lecture. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Voyages","Sport","Cuisine","Lecture"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.ga.17@profils-virtuels.yona.invalid","first_name":"Gloria","last_name":"Koumba","gender":"female","birth_date":"1983-09-04","country":"Gabon","region":"Ngounié","city":"Mouila","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la danse. La prière rythme mes journées. J'attends un homme de foi, doux et responsable.","interests":["Danse","Mode"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":34,"max_age":52},
{"email":"virtuel.ga.18@profils-virtuels.yona.invalid","first_name":"Christian","last_name":"Mboumba","gender":"male","birth_date":"1997-02-23","country":"Gabon","region":"Moyen-Ogooué","city":"Lambaréné","bio":"Fils de Dieu avant tout, je trouve ma joie dans la mode et le sport. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Mode","Sport"],"denomination":"Protestante (Église évangélique du Gabon)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.ga.19@profils-virtuels.yona.invalid","first_name":"Stessy","last_name":"Makaya","gender":"female","birth_date":"1985-10-08","country":"Gabon","region":"Nyanga","city":"Tchibanga","bio":"Fille de Dieu avant tout, je trouve ma joie dans le sport et le bénévolat. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Sport","Bénévolat"],"denomination":"Protestante (Église évangélique du Gabon)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.ga.20@profils-virtuels.yona.invalid","first_name":"Davy","last_name":"Mabika","gender":"male","birth_date":"1986-05-25","country":"Gabon","region":"Ogooué-Lolo","city":"Koulamoutou","bio":"Posé mais déterminé, j'aime la danse, le sport et les longues discussions. Je joue dans le groupe de louange de mon église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Danse","Sport","Louange"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":31,"max_age":49},
{"email":"virtuel.ga.21@profils-virtuels.yona.invalid","first_name":"Joëlle","last_name":"Ondo","gender":"female","birth_date":"1978-12-11","country":"Gabon","region":"Ogooué-Ivindo","city":"Makokou","bio":"Souriante et attentionnée, j'aime la lecture et la louange. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Louange","Lecture","Cinéma"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.ga.22@profils-virtuels.yona.invalid","first_name":"Hervé","last_name":"Mintsa","gender":"male","birth_date":"1999-10-24","country":"Gabon","region":"Estuaire","city":"Ntoum","bio":"Fils de Dieu avant tout, je trouve ma joie dans la musique et la lecture. J'aide à l'organisation des sorties de l'église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Musique"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.ga.23@profils-virtuels.yona.invalid","first_name":"Mireille","last_name":"Obiang","gender":"female","birth_date":"1994-01-12","country":"Gabon","region":"Estuaire","city":"Libreville","bio":"Souriante et attentionnée, j'aime les voyages et la mode. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Mode","Voyages"],"denomination":"Protestante (Église évangélique du Gabon)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.ga.24@profils-virtuels.yona.invalid","first_name":"Ghislain","last_name":"Bivigou","gender":"male","birth_date":"1993-11-14","country":"Gabon","region":"Ogooué-Maritime","city":"Port-Gentil","bio":"Calme et joyeux, je partage mon temps entre mon travail et la photographie. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Cinéma"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":24,"max_age":42},
{"email":"virtuel.ga.25@profils-virtuels.yona.invalid","first_name":"Nadège","last_name":"Nzé","gender":"female","birth_date":"1979-05-04","country":"Gabon","region":"Haut-Ogooué","city":"Franceville","bio":"Fille de Dieu avant tout, je trouve ma joie dans la mode et la lecture. J'enseigne à l'école du dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Mode","Louange","Lecture","Cuisine"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.cm.01@profils-virtuels.yona.invalid","first_name":"Aïcha","last_name":"Ngono","gender":"female","birth_date":"1979-08-03","country":"Cameroun","region":"Centre","city":"Yaoundé","bio":"Chaque journée est un cadeau de Dieu : je la remplis de balades dans la nature et de bénévolat. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Nature","Bénévolat"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.cm.02@profils-virtuels.yona.invalid","first_name":"Boris","last_name":"Bella","gender":"male","birth_date":"1991-06-21","country":"Cameroun","region":"Littoral","city":"Douala","bio":"Posé mais déterminé, j'aime la cuisine, le sport et les longues discussions. Je participe à un groupe de prière chaque semaine. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Sport"],"denomination":"Presbytérienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.cm.03@profils-virtuels.yona.invalid","first_name":"Solange","last_name":"Mbappé","gender":"female","birth_date":"1988-12-23","country":"Cameroun","region":"West","city":"Bafoussam","bio":"Fille de Dieu avant tout, je trouve ma joie dans la louange et la danse. Ma foi guide chacune de mes décisions. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Danse","Louange"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":29,"max_age":47},
{"email":"virtuel.cm.04@profils-virtuels.yona.invalid","first_name":"Hervé","last_name":"Tagne","gender":"male","birth_date":"1996-02-01","country":"Cameroun","region":"North-West","city":"Bamenda","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de photographie. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Photographie","Cuisine","Bénévolat"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.cm.05@profils-virtuels.yona.invalid","first_name":"Rosine","last_name":"Nkoulou","gender":"female","birth_date":"1995-03-17","country":"Cameroun","region":"North","city":"Garoua","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de voyages. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Photographie"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.cm.06@profils-virtuels.yona.invalid","first_name":"Thierry","last_name":"Fotso","gender":"male","birth_date":"1983-04-20","country":"Cameroun","region":"Adamaoua","city":"Ngaoundéré","bio":"Souriant et attentionné, j'aime les voyages et la danse. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Danse"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":34,"max_age":52},
{"email":"virtuel.cm.07@profils-virtuels.yona.invalid","first_name":"Pélagie","last_name":"Ndjock","gender":"female","birth_date":"1977-02-20","country":"Cameroun","region":"South","city":"Kribi","bio":"Souriante et attentionnée, j'aime la musique et la photographie. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Photographie","Musique"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.cm.08@profils-virtuels.yona.invalid","first_name":"Rodrigue","last_name":"Noah","gender":"male","birth_date":"1978-12-23","country":"Cameroun","region":"South-West","city":"Buea","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de cinéma. Je suis engagé dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Cinéma","Lecture","Bénévolat"],"denomination":"Pentecôtiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.cm.09@profils-virtuels.yona.invalid","first_name":"Yolande","last_name":"Tchamba","gender":"female","birth_date":"1983-09-25","country":"Cameroun","region":"South-West","city":"Limbe","bio":"Je suis une femme simple, passionnée par la musique et les voyages. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Voyages"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":34,"max_age":52},
{"email":"virtuel.cm.10@profils-virtuels.yona.invalid","first_name":"Cédric","last_name":"Kamga","gender":"male","birth_date":"1998-11-20","country":"Cameroun","region":"South","city":"Ébolowa","bio":"Je suis un homme simple, passionné par le sport et la lecture. J'aide à l'organisation des sorties de l'église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Sport","Lecture","Musique"],"denomination":"Presbytérienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.cm.11@profils-virtuels.yona.invalid","first_name":"Grâce","last_name":"Tchoumi","gender":"female","birth_date":"1999-01-29","country":"Cameroun","region":"West","city":"Dschang","bio":"Je suis une femme simple, passionnée par la lecture et la cuisine. J'aime méditer la Parole chaque matin. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Cinéma","Cuisine","Lecture"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.cm.12@profils-virtuels.yona.invalid","first_name":"Guy","last_name":"Atangana","gender":"male","birth_date":"1981-05-13","country":"Cameroun","region":"East","city":"Bertoua","bio":"Souriant et attentionné, j'aime la mode et la cuisine. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Cuisine","Mode"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.cm.13@profils-virtuels.yona.invalid","first_name":"Danielle","last_name":"Mbarga","gender":"female","birth_date":"1984-12-11","country":"Cameroun","region":"South-West","city":"Kumba","bio":"Je suis une femme simple, passionnée par la danse et la cuisine. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Danse"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.cm.14@profils-virtuels.yona.invalid","first_name":"Serge","last_name":"Eto'o","gender":"male","birth_date":"1979-10-30","country":"Cameroun","region":"Littoral","city":"Edéa","bio":"Posé mais déterminé, j'aime le sport, la lecture et les longues discussions. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Sport","Lecture","Cuisine"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.cm.15@profils-virtuels.yona.invalid","first_name":"Carine","last_name":"Nana","gender":"female","birth_date":"2001-08-03","country":"Cameroun","region":"Centre","city":"Yaoundé","bio":"Douce mais déterminée, j'aime la louange, la cuisine et les longues discussions. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Nature","Louange","Cuisine"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.cm.16@profils-virtuels.yona.invalid","first_name":"Patrice","last_name":"Essomba","gender":"male","birth_date":"1980-04-07","country":"Cameroun","region":"Littoral","city":"Douala","bio":"Je suis un homme simple, passionné par la cuisine et le cinéma. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Cinéma","Cuisine","Louange"],"denomination":"Presbytérienne","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.cm.17@profils-virtuels.yona.invalid","first_name":"Vanessa","last_name":"Onana","gender":"female","birth_date":"1991-11-17","country":"Cameroun","region":"West","city":"Bafoussam","bio":"Fille de Dieu avant tout, je trouve ma joie dans la musique et la cuisine. Je chante dans la chorale de mon église. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Mode","Musique"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.cm.18@profils-virtuels.yona.invalid","first_name":"Loïc","last_name":"Abena","gender":"male","birth_date":"1979-06-01","country":"Cameroun","region":"North-West","city":"Bamenda","bio":"Souriant et attentionné, j'aime le sport et la lecture. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Photographie","Voyages","Sport"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.cm.19@profils-virtuels.yona.invalid","first_name":"Laure","last_name":"Kenmogne","gender":"female","birth_date":"2003-12-26","country":"Cameroun","region":"North","city":"Garoua","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Photographie","Lecture","Cuisine"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.cm.20@profils-virtuels.yona.invalid","first_name":"Yves","last_name":"Manga","gender":"male","birth_date":"1977-06-13","country":"Cameroun","region":"Adamaoua","city":"Ngaoundéré","bio":"Posé mais déterminé, j'aime les balades dans la nature, la photographie et les longues discussions. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Lecture","Danse","Photographie","Nature"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.cm.21@profils-virtuels.yona.invalid","first_name":"Flore","last_name":"Ngono","gender":"female","birth_date":"1985-11-26","country":"Cameroun","region":"South","city":"Kribi","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. Ma foi guide chacune de mes décisions. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Voyages"],"denomination":"Presbytérienne","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.cm.22@profils-virtuels.yona.invalid","first_name":"Jean-Paul","last_name":"Bella","gender":"male","birth_date":"1994-02-14","country":"Cameroun","region":"South-West","city":"Buea","bio":"Posé mais déterminé, j'aime la danse, les voyages et les longues discussions. Je suis engagé dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Danse","Voyages"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.cm.23@profils-virtuels.yona.invalid","first_name":"Michèle","last_name":"Mbappé","gender":"female","birth_date":"1998-07-15","country":"Cameroun","region":"South-West","city":"Limbe","bio":"Fille de Dieu avant tout, je trouve ma joie dans la mode et la photographie. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Mode","Photographie","Cuisine"],"denomination":"Presbytérienne","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.cm.24@profils-virtuels.yona.invalid","first_name":"Steve","last_name":"Tagne","gender":"male","birth_date":"1991-03-13","country":"Cameroun","region":"South","city":"Ébolowa","bio":"Calme et joyeux, je partage mon temps entre mon travail et la cuisine. La prière rythme mes journées. J'attends une femme de foi, douce et pleine de joie.","interests":["Mode","Cuisine"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.cm.25@profils-virtuels.yona.invalid","first_name":"Nadine","last_name":"Nkoulou","gender":"female","birth_date":"1982-07-04","country":"Cameroun","region":"West","city":"Dschang","bio":"Douce mais déterminée, j'aime la cuisine, la photographie et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Cuisine","Photographie"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.cg.01@profils-virtuels.yona.invalid","first_name":"Bénie","last_name":"Samba","gender":"female","birth_date":"1994-12-03","country":"Congo-Brazzaville","region":"Brazzaville","city":"Brazzaville","bio":"Fille de Dieu avant tout, je trouve ma joie dans la mode et la cuisine. J'aime méditer la Parole chaque matin. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Cuisine","Mode","Bénévolat"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.cg.02@profils-virtuels.yona.invalid","first_name":"Fortuné","last_name":"Moukoko","gender":"male","birth_date":"1987-09-03","country":"Congo-Brazzaville","region":"Pointe-Noire","city":"Pointe-Noire","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la musique. J'aide à l'organisation des sorties de l'église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Danse","Musique","Louange","Sport"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":30,"max_age":48},
{"email":"virtuel.cg.03@profils-virtuels.yona.invalid","first_name":"Chancelvie","last_name":"Kounkou","gender":"female","birth_date":"1984-08-14","country":"Congo-Brazzaville","region":"Niari","city":"Dolisie","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Sport"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.cg.04@profils-virtuels.yona.invalid","first_name":"Merveil","last_name":"Nkounkou","gender":"male","birth_date":"1989-09-03","country":"Congo-Brazzaville","region":"Bouenza","city":"Nkayi","bio":"Souriant et attentionné, j'aime le cinéma et la lecture. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Lecture"],"denomination":"Kimbanguiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.cg.05@profils-virtuels.yona.invalid","first_name":"Reine","last_name":"Mabiala","gender":"female","birth_date":"1991-09-21","country":"Congo-Brazzaville","region":"Cuvette","city":"Owando","bio":"Souriante et attentionnée, j'aime la lecture et la danse. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Lecture","Bénévolat","Voyages","Danse"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.cg.06@profils-virtuels.yona.invalid","first_name":"Christ","last_name":"Okemba","gender":"male","birth_date":"1978-04-05","country":"Congo-Brazzaville","region":"Sangha","city":"Ouesso","bio":"Souriant et attentionné, j'aime les balades dans la nature et le bénévolat. La prière rythme mes journées. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Bénévolat","Nature"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.cg.07@profils-virtuels.yona.invalid","first_name":"Exaucée","last_name":"Mboungou","gender":"female","birth_date":"1982-09-18","country":"Congo-Brazzaville","region":"Bouenza","city":"Madingou","bio":"Je suis une femme simple, passionnée par les balades dans la nature et la louange. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Mode","Nature","Louange"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.cg.08@profils-virtuels.yona.invalid","first_name":"Ulrich","last_name":"Ibara","gender":"male","birth_date":"1994-07-23","country":"Congo-Brazzaville","region":"Plateaux","city":"Gamboma","bio":"Calme et joyeux, je partage mon temps entre mon travail et la lecture. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Lecture","Bénévolat"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.cg.09@profils-virtuels.yona.invalid","first_name":"Divine","last_name":"Kimbembé","gender":"female","birth_date":"1980-07-21","country":"Congo-Brazzaville","region":"Likouala","city":"Impfondo","bio":"Je suis une femme simple, passionnée par les voyages et la cuisine. La prière rythme mes journées. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Danse","Voyages"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.cg.10@profils-virtuels.yona.invalid","first_name":"Arsène","last_name":"Tchicaya","gender":"male","birth_date":"1995-08-06","country":"Congo-Brazzaville","region":"Lékoumou","city":"Sibiti","bio":"Posé mais déterminé, j'aime le sport, le cinéma et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Cinéma","Nature","Bénévolat"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.cg.11@profils-virtuels.yona.invalid","first_name":"Nelly","last_name":"Mavoungou","gender":"female","birth_date":"1994-04-27","country":"Congo-Brazzaville","region":"Pool","city":"Kinkala","bio":"Fille de Dieu avant tout, je trouve ma joie dans la musique et la mode. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Mode","Musique"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.cg.12@profils-virtuels.yona.invalid","first_name":"Exaucé","last_name":"Bouanga","gender":"male","birth_date":"2003-11-01","country":"Congo-Brazzaville","region":"Brazzaville","city":"Brazzaville","bio":"Souriant et attentionné, j'aime la musique et la mode. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Cinéma","Voyages","Musique","Mode"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.cg.13@profils-virtuels.yona.invalid","first_name":"Gloire","last_name":"Massamba","gender":"female","birth_date":"1985-05-24","country":"Congo-Brazzaville","region":"Pointe-Noire","city":"Pointe-Noire","bio":"Fille de Dieu avant tout, je trouve ma joie dans la cuisine et le sport. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Sport"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.cg.14@profils-virtuels.yona.invalid","first_name":"Hardy","last_name":"Miakassissa","gender":"male","birth_date":"1997-04-13","country":"Congo-Brazzaville","region":"Niari","city":"Dolisie","bio":"Souriant et attentionné, j'aime le bénévolat et les balades dans la nature. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Bénévolat","Danse","Nature","Voyages"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.cg.15@profils-virtuels.yona.invalid","first_name":"Victoire","last_name":"Malonga","gender":"female","birth_date":"1980-02-14","country":"Congo-Brazzaville","region":"Bouenza","city":"Nkayi","bio":"Chaque journée est un cadeau de Dieu : je la remplis de sport et de voyages. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Voyages","Sport"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.cg.16@profils-virtuels.yona.invalid","first_name":"Trésor","last_name":"Matsiona","gender":"male","birth_date":"2001-12-09","country":"Congo-Brazzaville","region":"Cuvette","city":"Owando","bio":"Je suis un homme simple, passionné par la cuisine et le cinéma. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Cinéma","Cuisine","Photographie","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.cg.17@profils-virtuels.yona.invalid","first_name":"Tendresse","last_name":"Loubaki","gender":"female","birth_date":"1992-05-01","country":"Congo-Brazzaville","region":"Sangha","city":"Ouesso","bio":"Souriante et attentionnée, j'aime la lecture et la louange. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Nature","Lecture","Voyages","Louange"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.cg.18@profils-virtuels.yona.invalid","first_name":"Varel","last_name":"Ngoma","gender":"male","birth_date":"1981-05-25","country":"Congo-Brazzaville","region":"Bouenza","city":"Madingou","bio":"Fils de Dieu avant tout, je trouve ma joie dans le cinéma et le sport. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Voyages","Bénévolat","Cinéma","Sport"],"denomination":"Kimbanguiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.cg.19@profils-virtuels.yona.invalid","first_name":"Prisca","last_name":"Bakala","gender":"female","birth_date":"1987-05-12","country":"Congo-Brazzaville","region":"Plateaux","city":"Gamboma","bio":"Fille de Dieu avant tout, je trouve ma joie dans les balades dans la nature et le cinéma. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Cinéma","Nature"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.cg.20@profils-virtuels.yona.invalid","first_name":"Prince","last_name":"Ngouabi","gender":"male","birth_date":"1980-09-07","country":"Congo-Brazzaville","region":"Likouala","city":"Impfondo","bio":"Fils de Dieu avant tout, je trouve ma joie dans la mode et la photographie. Je joue dans le groupe de louange de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Mode","Photographie","Musique"],"denomination":"Kimbanguiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.cg.21@profils-virtuels.yona.invalid","first_name":"Merveille","last_name":"Samba","gender":"female","birth_date":"1998-09-02","country":"Congo-Brazzaville","region":"Lékoumou","city":"Sibiti","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Bénévolat","Nature"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.cg.22@profils-virtuels.yona.invalid","first_name":"Rudy","last_name":"Moukoko","gender":"male","birth_date":"1989-03-25","country":"Congo-Brazzaville","region":"Pool","city":"Kinkala","bio":"Calme et joyeux, je partage mon temps entre mon travail et le sport. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Sport","Cuisine","Cinéma"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.cg.23@profils-virtuels.yona.invalid","first_name":"Ruth","last_name":"Kounkou","gender":"female","birth_date":"1990-11-30","country":"Congo-Brazzaville","region":"Brazzaville","city":"Brazzaville","bio":"Fille de Dieu avant tout, je trouve ma joie dans le bénévolat et la cuisine. Je chante dans la chorale de mon église. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Bénévolat"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.cg.24@profils-virtuels.yona.invalid","first_name":"Bienvenu","last_name":"Nkounkou","gender":"male","birth_date":"1982-11-17","country":"Congo-Brazzaville","region":"Pointe-Noire","city":"Pointe-Noire","bio":"Je suis un homme simple, passionné par la lecture et la photographie. Je sers à l'accueil de mon église le dimanche. J'attends une femme de foi, douce et pleine de joie.","interests":["Photographie","Lecture"],"denomination":"Salutiste (Armée du Salut)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.cg.25@profils-virtuels.yona.invalid","first_name":"Orphée","last_name":"Mabiala","gender":"female","birth_date":"1999-06-01","country":"Congo-Brazzaville","region":"Niari","city":"Dolisie","bio":"Je suis une femme simple, passionnée par la photographie et la lecture. J'aime méditer la Parole chaque matin. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Photographie","Lecture","Bénévolat"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":36}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
