-- ============================================================
-- YONA — profils virtuels : fichier 3 sur 10
-- 75 profils : RD Congo, Côte d'Ivoire, Sénégal.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.cd.01@profils-virtuels.yona.invalid","first_name":"Jemima","last_name":"Bokele","gender":"female","birth_date":"1988-08-02","country":"RD Congo","region":"Kinshasa","city":"Kinshasa","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la lecture. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Cinéma","Lecture"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":29,"max_age":47},
{"email":"virtuel.cd.02@profils-virtuels.yona.invalid","first_name":"Junior","last_name":"Tshisekedi","gender":"male","birth_date":"1992-02-17","country":"RD Congo","region":"Haut-Katanga","city":"Lubumbashi","bio":"Je suis un homme simple, passionné par la louange et le sport. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Sport","Louange"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.cd.03@profils-virtuels.yona.invalid","first_name":"Sarah","last_name":"Ilunga","gender":"female","birth_date":"1989-07-17","country":"RD Congo","region":"East Kasai","city":"Mbuji-Mayi","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. Ma foi guide chacune de mes décisions. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Cuisine","Sport","Voyages"],"denomination":"Protestante (ECC)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.cd.04@profils-virtuels.yona.invalid","first_name":"Christian","last_name":"Kalonji","gender":"male","birth_date":"1981-01-27","country":"RD Congo","region":"Tshopo","city":"Kisangani","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la danse. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Sport","Danse","Nature"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.cd.05@profils-virtuels.yona.invalid","first_name":"Nathalie","last_name":"Nsimba","gender":"female","birth_date":"1984-07-19","country":"RD Congo","region":"North Kivu","city":"Goma","bio":"Fille de Dieu avant tout, je trouve ma joie dans la danse et la cuisine. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Cuisine","Danse"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.cd.06@profils-virtuels.yona.invalid","first_name":"Plamedi","last_name":"Banza","gender":"male","birth_date":"2000-08-03","country":"RD Congo","region":"South Kivu","city":"Bukavu","bio":"Je suis un homme simple, passionné par la louange et la lecture. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Lecture","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.cd.07@profils-virtuels.yona.invalid","first_name":"Patience","last_name":"Lukusa","gender":"female","birth_date":"2002-06-25","country":"RD Congo","region":"Kasai-Central","city":"Kananga","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Musique"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.cd.08@profils-virtuels.yona.invalid","first_name":"Yannick","last_name":"Kanku","gender":"male","birth_date":"1986-12-19","country":"RD Congo","region":"Lualaba","city":"Kolwezi","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. J'aide à l'organisation des sorties de l'église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Louange","Lecture","Cuisine"],"denomination":"Kimbanguiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":31,"max_age":49},
{"email":"virtuel.cd.09@profils-virtuels.yona.invalid","first_name":"Rebecca","last_name":"Mutombo","gender":"female","birth_date":"1987-04-16","country":"RD Congo","region":"Bas-Congo","city":"Matadi","bio":"Fille de Dieu avant tout, je trouve ma joie dans les voyages et la cuisine. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cuisine","Voyages"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.cd.10@profils-virtuels.yona.invalid","first_name":"Michée","last_name":"Mbemba","gender":"male","birth_date":"1980-02-04","country":"RD Congo","region":"Haut-Katanga","city":"Likasi","bio":"Fils de Dieu avant tout, je trouve ma joie dans les voyages et le sport. Ma foi guide chacune de mes décisions. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Voyages","Nature","Musique","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.cd.11@profils-virtuels.yona.invalid","first_name":"Gloire","last_name":"Mwamba","gender":"female","birth_date":"1994-06-29","country":"RD Congo","region":"Équateur","city":"Mbandaka","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Bénévolat","Voyages"],"denomination":"Protestante (ECC)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.cd.12@profils-virtuels.yona.invalid","first_name":"Exaucé","last_name":"Lokombe","gender":"male","birth_date":"1996-09-29","country":"RD Congo","region":"Kwilu","city":"Kikwit","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Musique","Sport","Bénévolat","Photographie"],"denomination":"Kimbanguiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.cd.13@profils-virtuels.yona.invalid","first_name":"Esther","last_name":"Makiadi","gender":"female","birth_date":"1977-04-30","country":"RD Congo","region":"South Kivu","city":"Uvira","bio":"Douce mais déterminée, j'aime la cuisine, la musique et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Cuisine","Musique"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.cd.14@profils-virtuels.yona.invalid","first_name":"Dieumerci","last_name":"Kasongo","gender":"male","birth_date":"1996-03-09","country":"RD Congo","region":"Bas-Congo","city":"Boma","bio":"Chaque journée est un cadeau de Dieu : je la remplis de sport et de balades dans la nature. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Voyages","Sport"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.cd.15@profils-virtuels.yona.invalid","first_name":"Merveille","last_name":"Ngalula","gender":"female","birth_date":"2000-06-28","country":"RD Congo","region":"Kinshasa","city":"Kinshasa","bio":"Je suis une femme simple, passionnée par la louange et les voyages. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Nature","Louange","Voyages"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.cd.16@profils-virtuels.yona.invalid","first_name":"Trésor","last_name":"Kabeya","gender":"male","birth_date":"1999-12-21","country":"RD Congo","region":"Haut-Katanga","city":"Lubumbashi","bio":"Calme et joyeux, je partage mon temps entre mon travail et la cuisine. Je suis engagé dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Cuisine","Lecture","Danse"],"denomination":"Kimbanguiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.cd.17@profils-virtuels.yona.invalid","first_name":"Orpha","last_name":"Tshibanda","gender":"female","birth_date":"2003-04-10","country":"RD Congo","region":"East Kasai","city":"Mbuji-Mayi","bio":"Douce mais déterminée, j'aime la louange, la cuisine et les longues discussions. Ma foi guide chacune de mes décisions. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Cuisine","Mode","Louange"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.cd.18@profils-virtuels.yona.invalid","first_name":"Serge","last_name":"Mukendi","gender":"male","birth_date":"1985-09-30","country":"RD Congo","region":"Tshopo","city":"Kisangani","bio":"Je suis un homme simple, passionné par la musique et la mode. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Musique","Mode"],"denomination":"Protestante (ECC)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.cd.19@profils-virtuels.yona.invalid","first_name":"Grâce","last_name":"Kabila","gender":"female","birth_date":"1977-12-03","country":"RD Congo","region":"North Kivu","city":"Goma","bio":"Je suis une femme simple, passionnée par le bénévolat et les balades dans la nature. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Nature","Photographie","Bénévolat"],"denomination":"Kimbanguiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.cd.20@profils-virtuels.yona.invalid","first_name":"Ruphin","last_name":"Mbuyi","gender":"male","birth_date":"1996-10-08","country":"RD Congo","region":"South Kivu","city":"Bukavu","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. La prière rythme mes journées. J'attends une femme de foi, douce et pleine de joie.","interests":["Nature","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.cd.21@profils-virtuels.yona.invalid","first_name":"Divine","last_name":"Bokele","gender":"female","birth_date":"1978-05-30","country":"RD Congo","region":"Kasai-Central","city":"Kananga","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la photographie. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Photographie","Voyages","Musique","Mode"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.cd.22@profils-virtuels.yona.invalid","first_name":"Cédric","last_name":"Tshisekedi","gender":"male","birth_date":"1978-01-19","country":"RD Congo","region":"Lualaba","city":"Kolwezi","bio":"Chaque journée est un cadeau de Dieu : je la remplis de mode et de voyages. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Voyages","Bénévolat","Mode"],"denomination":"Protestante (ECC)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.cd.23@profils-virtuels.yona.invalid","first_name":"Naomie","last_name":"Ilunga","gender":"female","birth_date":"1987-09-11","country":"RD Congo","region":"Bas-Congo","city":"Matadi","bio":"Je suis une femme simple, passionnée par le cinéma et la photographie. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Cinéma"],"denomination":"Kimbanguiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.cd.24@profils-virtuels.yona.invalid","first_name":"Glody","last_name":"Kalonji","gender":"male","birth_date":"1999-11-28","country":"RD Congo","region":"Haut-Katanga","city":"Likasi","bio":"Fils de Dieu avant tout, je trouve ma joie dans le sport et la mode. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Sport","Voyages","Mode"],"denomination":"Protestante (ECC)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.cd.25@profils-virtuels.yona.invalid","first_name":"Huguette","last_name":"Nsimba","gender":"female","birth_date":"2000-02-08","country":"RD Congo","region":"Équateur","city":"Mbandaka","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Bénévolat","Mode","Voyages"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.ci.01@profils-virtuels.yona.invalid","first_name":"Chantal","last_name":"Gbagbo","gender":"female","birth_date":"1991-06-12","country":"Côte d'Ivoire","region":"Abidjan Autonomous District","city":"Abidjan","bio":"Souriante et attentionnée, j'aime le cinéma et le bénévolat. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.","interests":["Bénévolat","Cinéma","Lecture"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.ci.02@profils-virtuels.yona.invalid","first_name":"Fabrice","last_name":"Kouamé","gender":"male","birth_date":"1991-08-14","country":"Côte d'Ivoire","region":"Vallée du Bandama District","city":"Bouaké","bio":"Fils de Dieu avant tout, je trouve ma joie dans la musique et le bénévolat. Je suis engagé dans le groupe de jeunes de ma paroisse. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Musique"],"denomination":"Harriste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.ci.03@profils-virtuels.yona.invalid","first_name":"Ange","last_name":"Ehui","gender":"female","birth_date":"1983-09-01","country":"Côte d'Ivoire","region":"Lacs District","city":"Yamoussoukro","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la danse. Le Psaume 23 m'accompagne depuis toujours. J'attends un homme de foi, doux et responsable.","interests":["Danse","Louange","Sport","Lecture"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":34,"max_age":52},
{"email":"virtuel.ci.04@profils-virtuels.yona.invalid","first_name":"Cyrille","last_name":"Aka","gender":"male","birth_date":"1993-08-15","country":"Côte d'Ivoire","region":"Sassandra-Marahoue","city":"Daloa","bio":"Calme et joyeux, je partage mon temps entre mon travail et le bénévolat. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Sport","Bénévolat"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":24,"max_age":42},
{"email":"virtuel.ci.05@profils-virtuels.yona.invalid","first_name":"Ruth","last_name":"Bamba","gender":"female","birth_date":"1982-11-17","country":"Côte d'Ivoire","region":"Bas-Sassandra District","city":"San-Pédro","bio":"Je suis une femme simple, passionnée par la photographie et la musique. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Musique","Photographie"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.ci.06@profils-virtuels.yona.invalid","first_name":"Landry","last_name":"Séri","gender":"male","birth_date":"1987-06-23","country":"Côte d'Ivoire","region":"Savanes District","city":"Korhogo","bio":"Fils de Dieu avant tout, je trouve ma joie dans la musique et la danse. J'aide à l'organisation des sorties de l'église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Danse","Musique","Voyages"],"denomination":"Méthodiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":30,"max_age":48},
{"email":"virtuel.ci.07@profils-virtuels.yona.invalid","first_name":"Ahou","last_name":"Gnahoré","gender":"female","birth_date":"1996-04-05","country":"Côte d'Ivoire","region":"Montagnes","city":"Man","bio":"Je suis une femme simple, passionnée par les balades dans la nature et le sport. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Nature"],"denomination":"Méthodiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.ci.08@profils-virtuels.yona.invalid","first_name":"Konan","last_name":"Zadi","gender":"male","birth_date":"1982-12-10","country":"Côte d'Ivoire","region":"Goh-Djiboua","city":"Gagnoa","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux voyages. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Voyages","Nature","Mode","Sport"],"denomination":"Évangélique (Assemblées de Dieu)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.ci.09@profils-virtuels.yona.invalid","first_name":"Sylvie","last_name":"Koffi","gender":"female","birth_date":"1993-01-26","country":"Côte d'Ivoire","region":"Goh-Djiboua","city":"Divo","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la mode. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Lecture","Cuisine","Mode"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.ci.10@profils-virtuels.yona.invalid","first_name":"Brice","last_name":"Gnagne","gender":"male","birth_date":"1992-10-07","country":"Côte d'Ivoire","region":"Comoé District","city":"Abengourou","bio":"Je suis un homme simple, passionné par le cinéma et la musique. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Musique","Cinéma"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.ci.11@profils-virtuels.yona.invalid","first_name":"Laetitia","last_name":"Kouadio","gender":"female","birth_date":"1988-10-30","country":"Côte d'Ivoire","region":"Comoé District","city":"Grand-Bassam","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le sport. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Sport","Lecture","Danse"],"denomination":"Évangélique (Assemblées de Dieu)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":29,"max_age":47},
{"email":"virtuel.ci.12@profils-virtuels.yona.invalid","first_name":"Olivier","last_name":"Aké","gender":"male","birth_date":"1988-01-13","country":"Côte d'Ivoire","region":"Abidjan Autonomous District","city":"Bingerville","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de cinéma. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Photographie","Cinéma"],"denomination":"Harriste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.ci.13@profils-virtuels.yona.invalid","first_name":"Akissi","last_name":"Konan","gender":"female","birth_date":"1992-01-27","country":"Côte d'Ivoire","region":"Abidjan Autonomous District","city":"Anyama","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la photographie. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Lecture","Cinéma","Danse"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.ci.14@profils-virtuels.yona.invalid","first_name":"Ange","last_name":"Yao","gender":"male","birth_date":"1981-11-05","country":"Côte d'Ivoire","region":"Abidjan Autonomous District","city":"Abidjan","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de lecture. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Cuisine","Lecture"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.ci.15@profils-virtuels.yona.invalid","first_name":"Grâce","last_name":"N'Guessan","gender":"female","birth_date":"1992-05-03","country":"Côte d'Ivoire","region":"Vallée du Bandama District","city":"Bouaké","bio":"Douce mais déterminée, j'aime les balades dans la nature, la lecture et les longues discussions. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Nature"],"denomination":"Méthodiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.ci.16@profils-virtuels.yona.invalid","first_name":"Kouassi","last_name":"Dago","gender":"male","birth_date":"1991-03-17","country":"Côte d'Ivoire","region":"Lacs District","city":"Yamoussoukro","bio":"Calme et joyeux, je partage mon temps entre mon travail et le sport. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Nature","Sport","Lecture"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.ci.17@profils-virtuels.yona.invalid","first_name":"Prisca","last_name":"Tano","gender":"female","birth_date":"1988-11-02","country":"Côte d'Ivoire","region":"Sassandra-Marahoue","city":"Daloa","bio":"Souriante et attentionnée, j'aime la photographie et le sport. Je sers à l'accueil de mon église le dimanche. J'attends un homme de foi, doux et responsable.","interests":["Sport","Photographie","Nature"],"denomination":"Harriste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":29,"max_age":47},
{"email":"virtuel.ci.18@profils-virtuels.yona.invalid","first_name":"Yao","last_name":"Assi","gender":"male","birth_date":"1999-07-12","country":"Côte d'Ivoire","region":"Bas-Sassandra District","city":"San-Pédro","bio":"Posé mais déterminé, j'aime le sport, la mode et les longues discussions. La prière rythme mes journées. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Mode","Sport"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.ci.19@profils-virtuels.yona.invalid","first_name":"Marina","last_name":"Brou","gender":"female","birth_date":"1998-06-07","country":"Côte d'Ivoire","region":"Savanes District","city":"Korhogo","bio":"Douce mais déterminée, j'aime le bénévolat, la cuisine et les longues discussions. J'aime méditer la Parole chaque matin. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Cuisine","Bénévolat"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.ci.20@profils-virtuels.yona.invalid","first_name":"Serge","last_name":"Ouattara","gender":"male","birth_date":"1978-01-11","country":"Côte d'Ivoire","region":"Montagnes","city":"Man","bio":"Fils de Dieu avant tout, je trouve ma joie dans les voyages et la musique. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Danse","Voyages"],"denomination":"Évangélique (Assemblées de Dieu)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.ci.21@profils-virtuels.yona.invalid","first_name":"Amenan","last_name":"Gbagbo","gender":"female","birth_date":"2000-07-24","country":"Côte d'Ivoire","region":"Goh-Djiboua","city":"Gagnoa","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la lecture. Je suis engagée dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cuisine","Lecture"],"denomination":"Harriste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.ci.22@profils-virtuels.yona.invalid","first_name":"Jean-Marc","last_name":"Kouamé","gender":"male","birth_date":"1989-06-15","country":"Côte d'Ivoire","region":"Goh-Djiboua","city":"Divo","bio":"Posé mais déterminé, j'aime les balades dans la nature, le cinéma et les longues discussions. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Cinéma"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.ci.23@profils-virtuels.yona.invalid","first_name":"Nadia","last_name":"Ehui","gender":"female","birth_date":"2003-02-10","country":"Côte d'Ivoire","region":"Comoé District","city":"Abengourou","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la musique. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Musique","Danse"],"denomination":"Harriste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.ci.24@profils-virtuels.yona.invalid","first_name":"Didier","last_name":"Aka","gender":"male","birth_date":"2002-03-04","country":"Côte d'Ivoire","region":"Comoé District","city":"Grand-Bassam","bio":"Chaque journée est un cadeau de Dieu : je la remplis de sport et de bénévolat. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Sport","Bénévolat"],"denomination":"Évangélique (Assemblées de Dieu)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":33},
{"email":"virtuel.ci.25@profils-virtuels.yona.invalid","first_name":"Estelle","last_name":"Bamba","gender":"female","birth_date":"1983-01-13","country":"Côte d'Ivoire","region":"Abidjan Autonomous District","city":"Bingerville","bio":"Je suis une femme simple, passionnée par les balades dans la nature et la danse. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.","interests":["Nature","Mode","Danse","Lecture"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":34,"max_age":52},
{"email":"virtuel.sn.01@profils-virtuels.yona.invalid","first_name":"Rose","last_name":"Ndour","gender":"female","birth_date":"1980-01-12","country":"Sénégal","region":"Dakar","city":"Dakar","bio":"Je suis une femme simple, passionnée par la musique et la danse. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Danse"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.sn.02@profils-virtuels.yona.invalid","first_name":"Louis","last_name":"Diouf","gender":"male","birth_date":"1980-08-15","country":"Sénégal","region":"Thies","city":"Thiès","bio":"Calme et joyeux, je partage mon temps entre mon travail et le sport. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Sport","Danse"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.sn.03@profils-virtuels.yona.invalid","first_name":"Cécile","last_name":"Diatta","gender":"female","birth_date":"1977-02-19","country":"Sénégal","region":"Ziguinchor","city":"Ziguinchor","bio":"Fille de Dieu avant tout, je trouve ma joie dans la mode et le cinéma. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Mode"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.sn.04@profils-virtuels.yona.invalid","first_name":"Augustin","last_name":"Preira","gender":"male","birth_date":"1989-08-01","country":"Sénégal","region":"Saint-Louis","city":"Saint-Louis","bio":"Souriant et attentionné, j'aime le sport et les balades dans la nature. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Cinéma","Nature","Sport","Louange"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.sn.05@profils-virtuels.yona.invalid","first_name":"Joséphine","last_name":"Sarr","gender":"female","birth_date":"1994-08-20","country":"Sénégal","region":"Thies","city":"Mbour","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. Je chante dans la chorale de mon église. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cinéma","Bénévolat"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.sn.06@profils-virtuels.yona.invalid","first_name":"Charles","last_name":"Badji","gender":"male","birth_date":"1997-09-30","country":"Sénégal","region":"Kaolack","city":"Kaolack","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de sport. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Danse","Photographie","Sport"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.sn.07@profils-virtuels.yona.invalid","first_name":"Agnès","last_name":"Gomis","gender":"female","birth_date":"2000-04-07","country":"Sénégal","region":"Dakar","city":"Rufisque","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Voyages","Lecture","Cuisine"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.sn.08@profils-virtuels.yona.invalid","first_name":"Jean-Baptiste","last_name":"Faye","gender":"male","birth_date":"1988-07-31","country":"Sénégal","region":"Thies","city":"Joal","bio":"Posé mais déterminé, j'aime le bénévolat, la mode et les longues discussions. J'aide à l'organisation des sorties de l'église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Bénévolat","Nature","Mode"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.sn.09@profils-virtuels.yona.invalid","first_name":"Élisabeth","last_name":"Thiaw","gender":"female","birth_date":"1977-08-13","country":"Sénégal","region":"Ziguinchor","city":"Bignona","bio":"Chaque journée est un cadeau de Dieu : je la remplis de sport et de bénévolat. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Bénévolat","Sport","Photographie"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.sn.10@profils-virtuels.yona.invalid","first_name":"Marcel","last_name":"Coly","gender":"male","birth_date":"1979-05-24","country":"Sénégal","region":"Kolda","city":"Kolda","bio":"Chaque journée est un cadeau de Dieu : je la remplis de louange et de balades dans la nature. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Louange"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.sn.11@profils-virtuels.yona.invalid","first_name":"Thérèse","last_name":"Tine","gender":"female","birth_date":"2001-06-19","country":"Sénégal","region":"Fatick","city":"Fatick","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les balades dans la nature. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Nature","Bénévolat","Lecture"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.sn.12@profils-virtuels.yona.invalid","first_name":"Edouard","last_name":"Sagna","gender":"male","birth_date":"1999-12-26","country":"Sénégal","region":"Dakar","city":"Pikine","bio":"Calme et joyeux, je partage mon temps entre mon travail et la mode. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Photographie","Mode","Cinéma"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.sn.13@profils-virtuels.yona.invalid","first_name":"Louise","last_name":"Da Silva","gender":"female","birth_date":"1991-04-24","country":"Sénégal","region":"Dakar","city":"Dakar","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la photographie. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Danse","Photographie","Musique"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.sn.14@profils-virtuels.yona.invalid","first_name":"Pascal","last_name":"Ndiaye","gender":"male","birth_date":"1985-11-28","country":"Sénégal","region":"Thies","city":"Thiès","bio":"Je suis un homme simple, passionné par le sport et la danse. Je suis engagé dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Musique","Sport","Danse"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.sn.15@profils-virtuels.yona.invalid","first_name":"Marie-Anne","last_name":"Mendy","gender":"female","birth_date":"1997-10-16","country":"Sénégal","region":"Ziguinchor","city":"Ziguinchor","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Louange","Cuisine","Cinéma","Voyages"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.sn.16@profils-virtuels.yona.invalid","first_name":"Ferdinand","last_name":"Sène","gender":"male","birth_date":"1980-03-25","country":"Sénégal","region":"Saint-Louis","city":"Saint-Louis","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. Ma foi guide chacune de mes décisions. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Sport","Cuisine","Louange"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.sn.17@profils-virtuels.yona.invalid","first_name":"Hélène","last_name":"Manga","gender":"female","birth_date":"1985-11-21","country":"Sénégal","region":"Thies","city":"Mbour","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la louange. La prière rythme mes journées. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Louange","Photographie","Sport","Danse"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.sn.18@profils-virtuels.yona.invalid","first_name":"Bernard","last_name":"Diène","gender":"male","birth_date":"2001-10-15","country":"Sénégal","region":"Kaolack","city":"Kaolack","bio":"Calme et joyeux, je partage mon temps entre mon travail et le bénévolat. Ma foi guide chacune de mes décisions. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Lecture","Sport","Bénévolat"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.sn.19@profils-virtuels.yona.invalid","first_name":"Germaine","last_name":"Bassène","gender":"female","birth_date":"1987-02-20","country":"Sénégal","region":"Dakar","city":"Rufisque","bio":"Souriante et attentionnée, j'aime le cinéma et la louange. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Nature","Louange","Cinéma"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.sn.20@profils-virtuels.yona.invalid","first_name":"Pierre","last_name":"Basse","gender":"male","birth_date":"1993-01-12","country":"Sénégal","region":"Thies","city":"Joal","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de danse. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Danse","Voyages","Cuisine"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":24,"max_age":42},
{"email":"virtuel.sn.21@profils-virtuels.yona.invalid","first_name":"Madeleine","last_name":"Ndour","gender":"female","birth_date":"1987-07-14","country":"Sénégal","region":"Ziguinchor","city":"Bignona","bio":"Souriante et attentionnée, j'aime la lecture et la mode. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Danse","Mode","Photographie"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.sn.22@profils-virtuels.yona.invalid","first_name":"Raphaël","last_name":"Diouf","gender":"male","birth_date":"1997-04-24","country":"Sénégal","region":"Kolda","city":"Kolda","bio":"Je suis un homme simple, passionné par la mode et la musique. Je suis engagé dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Mode","Sport","Danse","Musique"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.sn.23@profils-virtuels.yona.invalid","first_name":"Clémentine","last_name":"Diatta","gender":"female","birth_date":"1989-04-11","country":"Sénégal","region":"Fatick","city":"Fatick","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. La prière rythme mes journées. J'attends un homme de foi, doux et responsable.","interests":["Louange","Cuisine","Mode","Voyages"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.sn.24@profils-virtuels.yona.invalid","first_name":"Joseph","last_name":"Preira","gender":"male","birth_date":"1988-09-03","country":"Sénégal","region":"Dakar","city":"Pikine","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. Ma foi guide chacune de mes décisions. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Louange","Bénévolat","Cuisine"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.sn.25@profils-virtuels.yona.invalid","first_name":"Albertine","last_name":"Sarr","gender":"female","birth_date":"1997-04-27","country":"Sénégal","region":"Dakar","city":"Dakar","bio":"Chaque journée est un cadeau de Dieu : je la remplis de mode et de musique. Je chante dans la chorale de mon église. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Mode","Voyages"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":20,"max_age":38}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
