-- ============================================================
-- YONA — profils virtuels : fichier 4 sur 10
-- 75 profils : Mali, Burkina Faso, Niger.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.ml.01@profils-virtuels.yona.invalid","first_name":"Anne","last_name":"Teme","gender":"female","birth_date":"1980-12-11","country":"Mali","region":"Bamako","city":"Bamako","bio":"Souriante et attentionnée, j'aime le sport et la photographie. La prière rythme mes journées. J'attends un homme de foi, doux et responsable.","interests":["Sport","Photographie","Voyages"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.ml.02@profils-virtuels.yona.invalid","first_name":"Samuel","last_name":"Dolo","gender":"male","birth_date":"1997-03-10","country":"Mali","region":"Sikasso","city":"Sikasso","bio":"Chaque journée est un cadeau de Dieu : je la remplis de danse et de sport. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Sport","Danse"],"denomination":"Protestante (Église chrétienne évangélique)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.ml.03@profils-virtuels.yona.invalid","first_name":"Esther","last_name":"Kassogué","gender":"female","birth_date":"1994-05-29","country":"Mali","region":"Ségou","city":"Ségou","bio":"Douce mais déterminée, j'aime la photographie, le cinéma et les longues discussions. Je sers à l'accueil de mon église le dimanche. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Cinéma","Bénévolat"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.ml.04@profils-virtuels.yona.invalid","first_name":"Claude","last_name":"Diarra","gender":"male","birth_date":"1995-08-26","country":"Mali","region":"Mopti","city":"Mopti","bio":"Fils de Dieu avant tout, je trouve ma joie dans la cuisine et le bénévolat. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Cuisine","Bénévolat"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.ml.05@profils-virtuels.yona.invalid","first_name":"Ruth","last_name":"Sagara","gender":"female","birth_date":"1983-11-08","country":"Mali","region":"Sikasso","city":"Koutiala","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la danse. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Louange","Cuisine","Danse"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":34,"max_age":52},
{"email":"virtuel.ml.06@profils-virtuels.yona.invalid","first_name":"André","last_name":"Coulibaly","gender":"male","birth_date":"1979-06-04","country":"Mali","region":"Ségou","city":"San","bio":"Posé mais déterminé, j'aime les balades dans la nature, le bénévolat et les longues discussions. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Nature","Bénévolat"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.ml.07@profils-virtuels.yona.invalid","first_name":"Marthe","last_name":"Tessougué","gender":"female","birth_date":"1977-06-24","country":"Mali","region":"Kayes","city":"Kayes","bio":"Chaque journée est un cadeau de Dieu : je la remplis de louange et de cinéma. Je chante dans la chorale de mon église. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Cinéma","Nature","Bénévolat"],"denomination":"Protestante (Église chrétienne évangélique)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.ml.08@profils-virtuels.yona.invalid","first_name":"Jacques","last_name":"Kamaté","gender":"male","birth_date":"1988-08-28","country":"Mali","region":"Sikasso","city":"Bougouni","bio":"Je suis un homme simple, passionné par la lecture et le cinéma. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Mode","Cinéma","Lecture"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.ml.09@profils-virtuels.yona.invalid","first_name":"Rachel","last_name":"Togo","gender":"female","birth_date":"1995-07-20","country":"Mali","region":"Koulikoro","city":"Kati","bio":"Douce mais déterminée, j'aime la lecture, la musique et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Sport","Musique","Lecture"],"denomination":"Protestante (Église chrétienne évangélique)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.ml.10@profils-virtuels.yona.invalid","first_name":"Bernard","last_name":"Dembélé","gender":"male","birth_date":"1989-11-19","country":"Mali","region":"Koulikoro","city":"Koulikoro","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de cinéma. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Cinéma","Lecture"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.ml.11@profils-virtuels.yona.invalid","first_name":"Élise","last_name":"Poudiougou","gender":"female","birth_date":"1985-09-03","country":"Mali","region":"Bamako","city":"Bamako","bio":"Fille de Dieu avant tout, je trouve ma joie dans la louange et les balades dans la nature. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Louange","Voyages","Nature"],"denomination":"Protestante (Église chrétienne évangélique)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.ml.12@profils-virtuels.yona.invalid","first_name":"Timothée","last_name":"Konaté","gender":"male","birth_date":"1988-10-30","country":"Mali","region":"Sikasso","city":"Sikasso","bio":"Chaque journée est un cadeau de Dieu : je la remplis de louange et de lecture. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Louange","Photographie","Lecture"],"denomination":"Protestante (Église chrétienne évangélique)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.ml.13@profils-virtuels.yona.invalid","first_name":"Suzanne","last_name":"Dara","gender":"female","birth_date":"1985-03-08","country":"Mali","region":"Ségou","city":"Ségou","bio":"Fille de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la photographie. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Nature","Photographie"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.ml.14@profils-virtuels.yona.invalid","first_name":"Joseph","last_name":"Bengaly","gender":"male","birth_date":"1999-09-04","country":"Mali","region":"Mopti","city":"Mopti","bio":"Calme et joyeux, je partage mon temps entre mon travail et les balades dans la nature. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Sport","Nature","Lecture"],"denomination":"Protestante (Église chrétienne évangélique)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.ml.15@profils-virtuels.yona.invalid","first_name":"Béatrice","last_name":"Dakouo","gender":"female","birth_date":"1981-07-22","country":"Mali","region":"Sikasso","city":"Koutiala","bio":"Fille de Dieu avant tout, je trouve ma joie dans la photographie et la danse. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Danse","Photographie"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":36,"max_age":54},
{"email":"virtuel.ml.16@profils-virtuels.yona.invalid","first_name":"Michel","last_name":"Guindo","gender":"male","birth_date":"1978-05-05","country":"Mali","region":"Ségou","city":"San","bio":"Je suis un homme simple, passionné par les voyages et le sport. Je joue dans le groupe de louange de mon église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Lecture","Voyages","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.ml.17@profils-virtuels.yona.invalid","first_name":"Myriam","last_name":"Goïta","gender":"female","birth_date":"1997-10-03","country":"Mali","region":"Kayes","city":"Kayes","bio":"Douce mais déterminée, j'aime la danse, la lecture et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Mode","Bénévolat","Danse"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.ml.18@profils-virtuels.yona.invalid","first_name":"Gabriel","last_name":"Sanogo","gender":"male","birth_date":"1978-04-08","country":"Mali","region":"Sikasso","city":"Bougouni","bio":"Posé mais déterminé, j'aime les voyages, la mode et les longues discussions. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Photographie","Mode","Voyages","Nature"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.ml.19@profils-virtuels.yona.invalid","first_name":"Véronique","last_name":"Kéita","gender":"female","birth_date":"2002-10-08","country":"Mali","region":"Koulikoro","city":"Kati","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Sport","Cinéma","Cuisine"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.ml.20@profils-virtuels.yona.invalid","first_name":"Moïse","last_name":"Traoré","gender":"male","birth_date":"1984-10-12","country":"Mali","region":"Koulikoro","city":"Koulikoro","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au cinéma. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Voyages","Musique","Danse"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.ml.21@profils-virtuels.yona.invalid","first_name":"Judith","last_name":"Teme","gender":"female","birth_date":"1999-10-01","country":"Mali","region":"Bamako","city":"Bamako","bio":"Fille de Dieu avant tout, je trouve ma joie dans le sport et le bénévolat. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Bénévolat","Sport"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.ml.22@profils-virtuels.yona.invalid","first_name":"François","last_name":"Dolo","gender":"male","birth_date":"1997-06-04","country":"Mali","region":"Sikasso","city":"Sikasso","bio":"Calme et joyeux, je partage mon temps entre mon travail et les voyages. Le Psaume 23 m'accompagne depuis toujours. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Voyages","Mode"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.ml.23@profils-virtuels.yona.invalid","first_name":"Deborah","last_name":"Kassogué","gender":"female","birth_date":"1987-11-15","country":"Mali","region":"Ségou","city":"Ségou","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la danse. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Nature","Musique","Danse"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.ml.24@profils-virtuels.yona.invalid","first_name":"Luc","last_name":"Diarra","gender":"male","birth_date":"2000-03-06","country":"Mali","region":"Mopti","city":"Mopti","bio":"Je suis un homme simple, passionné par les balades dans la nature et la musique. Le Psaume 23 m'accompagne depuis toujours. J'attends une femme de foi, douce et pleine de joie.","interests":["Musique","Cuisine","Nature"],"denomination":"Protestante (Église chrétienne évangélique)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.ml.25@profils-virtuels.yona.invalid","first_name":"Hélène","last_name":"Sagara","gender":"female","birth_date":"1982-02-06","country":"Mali","region":"Sikasso","city":"Koutiala","bio":"Fille de Dieu avant tout, je trouve ma joie dans la danse et la cuisine. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Danse","Cuisine"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.bf.01@profils-virtuels.yona.invalid","first_name":"Wendyam","last_name":"Compaoré","gender":"female","birth_date":"1987-05-03","country":"Burkina Faso","region":"Centre","city":"Ouagadougou","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la louange. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Danse","Cinéma","Photographie","Louange"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.bf.02@profils-virtuels.yona.invalid","first_name":"Wendkouni","last_name":"Kambou","gender":"male","birth_date":"1997-08-25","country":"Burkina Faso","region":"Hauts-Bassins","city":"Bobo-Dioulasso","bio":"Calme et joyeux, je partage mon temps entre mon travail et les voyages. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Voyages","Sport"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.bf.03@profils-virtuels.yona.invalid","first_name":"Habibou","last_name":"Sawadogo","gender":"female","birth_date":"1996-07-08","country":"Burkina Faso","region":"Centre-Ouest","city":"Koudougou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de mode. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Voyages","Mode"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.bf.04@profils-virtuels.yona.invalid","first_name":"Daniel","last_name":"Kaboré","gender":"male","birth_date":"1991-08-29","country":"Burkina Faso","region":"Nord","city":"Ouahigouya","bio":"Souriant et attentionné, j'aime la musique et les balades dans la nature. Je joue dans le groupe de louange de mon église. Je crois au mariage, à la fidélité et au respect.","interests":["Musique","Nature"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.bf.05@profils-virtuels.yona.invalid","first_name":"Pauline","last_name":"Tapsoba","gender":"female","birth_date":"1993-09-15","country":"Burkina Faso","region":"Cascades Region","city":"Banfora","bio":"Chaque journée est un cadeau de Dieu : je la remplis de voyages et de louange. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Lecture","Louange","Voyages"],"denomination":"Assemblées de Dieu","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.bf.06@profils-virtuels.yona.invalid","first_name":"Gérard","last_name":"Kouraogo","gender":"male","birth_date":"1978-06-18","country":"Burkina Faso","region":"Centre-Nord","city":"Kaya","bio":"Posé mais déterminé, j'aime la louange, la cuisine et les longues discussions. Je participe à un groupe de prière chaque semaine. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Cuisine"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.bf.07@profils-virtuels.yona.invalid","first_name":"Raïssa","last_name":"Dabiré","gender":"female","birth_date":"1982-06-04","country":"Burkina Faso","region":"Centre-Est","city":"Tenkodogo","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la lecture. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Cinéma","Danse"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.bf.08@profils-virtuels.yona.invalid","first_name":"Hyacinthe","last_name":"Kiemtoré","gender":"male","birth_date":"1992-11-24","country":"Burkina Faso","region":"Est","city":"Fada N'gourma","bio":"Posé mais déterminé, j'aime le bénévolat, la lecture et les longues discussions. Ma foi guide chacune de mes décisions. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Lecture","Bénévolat"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.bf.09@profils-virtuels.yona.invalid","first_name":"Florence","last_name":"Ouédraogo","gender":"female","birth_date":"1994-01-09","country":"Burkina Faso","region":"Boucle du Mouhoun","city":"Dédougou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de sport et de danse. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Sport","Danse"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.bf.10@profils-virtuels.yona.invalid","first_name":"Claude","last_name":"Sanou","gender":"male","birth_date":"1989-12-15","country":"Burkina Faso","region":"Centre-Ouest","city":"Réo","bio":"Souriant et attentionné, j'aime la musique et le bénévolat. Je suis engagé dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Musique","Sport","Mode","Bénévolat"],"denomination":"Assemblées de Dieu","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.bf.11@profils-virtuels.yona.invalid","first_name":"Laurence","last_name":"Ouattara","gender":"female","birth_date":"1977-01-17","country":"Burkina Faso","region":"Sud-Ouest","city":"Gaoua","bio":"Fille de Dieu avant tout, je trouve ma joie dans les balades dans la nature et le bénévolat. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Nature","Danse","Bénévolat","Cuisine"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.bf.12@profils-virtuels.yona.invalid","first_name":"Elie","last_name":"Bationo","gender":"male","birth_date":"1989-07-19","country":"Burkina Faso","region":"Plateau-Central","city":"Ziniaré","bio":"Chaque journée est un cadeau de Dieu : je la remplis de danse et de lecture. Je sers à l'accueil de mon église le dimanche. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Danse","Voyages","Nature","Lecture"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.bf.13@profils-virtuels.yona.invalid","first_name":"Irène","last_name":"Zoungrana","gender":"female","birth_date":"1980-08-27","country":"Burkina Faso","region":"Centre","city":"Ouagadougou","bio":"Douce mais déterminée, j'aime les voyages, la louange et les longues discussions. J'aime méditer la Parole chaque matin. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Voyages","Louange"],"denomination":"Assemblées de Dieu","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.bf.14@profils-virtuels.yona.invalid","first_name":"Pascal","last_name":"Zongo","gender":"male","birth_date":"1989-08-16","country":"Burkina Faso","region":"Hauts-Bassins","city":"Bobo-Dioulasso","bio":"Fils de Dieu avant tout, je trouve ma joie dans les voyages et le bénévolat. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Photographie","Voyages"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.bf.15@profils-virtuels.yona.invalid","first_name":"Delphine","last_name":"Kientega","gender":"female","birth_date":"1992-10-16","country":"Burkina Faso","region":"Centre-Ouest","city":"Koudougou","bio":"Je suis une femme simple, passionnée par la danse et la mode. Je chante dans la chorale de mon église. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Mode","Danse","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.bf.16@profils-virtuels.yona.invalid","first_name":"Lazare","last_name":"Ilboudo","gender":"male","birth_date":"1977-10-13","country":"Burkina Faso","region":"Nord","city":"Ouahigouya","bio":"Posé mais déterminé, j'aime la cuisine, le bénévolat et les longues discussions. J'aide à l'organisation des sorties de l'église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Bénévolat","Cuisine"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.bf.17@profils-virtuels.yona.invalid","first_name":"Josiane","last_name":"Nikiéma","gender":"female","birth_date":"1995-10-07","country":"Burkina Faso","region":"Cascades Region","city":"Banfora","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la cuisine. La prière rythme mes journées. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Lecture"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.bf.18@profils-virtuels.yona.invalid","first_name":"Jean-Paul","last_name":"Somé","gender":"male","birth_date":"1980-12-16","country":"Burkina Faso","region":"Centre-Nord","city":"Kaya","bio":"Souriant et attentionné, j'aime la louange et le cinéma. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Louange","Cinéma"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.bf.19@profils-virtuels.yona.invalid","first_name":"Edwige","last_name":"Kinda","gender":"female","birth_date":"1981-09-20","country":"Burkina Faso","region":"Centre-Est","city":"Tenkodogo","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de louange. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Louange","Musique","Lecture","Cinéma"],"denomination":"Protestante","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":36,"max_age":54},
{"email":"virtuel.bf.20@profils-virtuels.yona.invalid","first_name":"Alain","last_name":"Yaméogo","gender":"male","birth_date":"2003-12-02","country":"Burkina Faso","region":"Est","city":"Fada N'gourma","bio":"Je suis un homme simple, passionné par les voyages et le sport. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Danse","Bénévolat","Voyages"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.bf.21@profils-virtuels.yona.invalid","first_name":"Mariam","last_name":"Compaoré","gender":"female","birth_date":"1999-01-12","country":"Burkina Faso","region":"Boucle du Mouhoun","city":"Dédougou","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.","interests":["Louange","Lecture"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.bf.22@profils-virtuels.yona.invalid","first_name":"Noël","last_name":"Kambou","gender":"male","birth_date":"1985-08-16","country":"Burkina Faso","region":"Centre-Ouest","city":"Réo","bio":"Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de cinéma. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Cinéma"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.bf.23@profils-virtuels.yona.invalid","first_name":"Gisèle","last_name":"Sawadogo","gender":"female","birth_date":"1977-10-11","country":"Burkina Faso","region":"Sud-Ouest","city":"Gaoua","bio":"Fille de Dieu avant tout, je trouve ma joie dans la louange et la lecture. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Musique","Danse","Louange","Lecture"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.bf.24@profils-virtuels.yona.invalid","first_name":"Abel","last_name":"Kaboré","gender":"male","birth_date":"1988-02-06","country":"Burkina Faso","region":"Plateau-Central","city":"Ziniaré","bio":"Souriant et attentionné, j'aime les voyages et la musique. J'aide à l'organisation des sorties de l'église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Voyages","Musique","Mode","Cinéma"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.bf.25@profils-virtuels.yona.invalid","first_name":"Carine","last_name":"Tapsoba","gender":"female","birth_date":"2002-09-26","country":"Burkina Faso","region":"Centre","city":"Ouagadougou","bio":"Souriante et attentionnée, j'aime les balades dans la nature et le sport. Je chante dans la chorale de mon église. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Sport","Voyages","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.ne.01@profils-virtuels.yona.invalid","first_name":"Myriam","last_name":"Issa","gender":"female","birth_date":"1982-01-05","country":"Niger","region":"Niamey","city":"Niamey","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.","interests":["Cuisine","Photographie","Sport"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.ne.02@profils-virtuels.yona.invalid","first_name":"Josué","last_name":"Mahamadou","gender":"male","birth_date":"2003-01-07","country":"Niger","region":"Maradi Region","city":"Maradi","bio":"Posé mais déterminé, j'aime le bénévolat, le cinéma et les longues discussions. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Cuisine","Cinéma"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.ne.03@profils-virtuels.yona.invalid","first_name":"Rebecca","last_name":"Moussa","gender":"female","birth_date":"1998-07-27","country":"Niger","region":"Zinder Region","city":"Zinder","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la mode. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Cuisine","Mode","Louange"],"denomination":"Évangélique (EERN)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.ne.04@profils-virtuels.yona.invalid","first_name":"Isaac","last_name":"Ibrahim","gender":"male","birth_date":"1980-10-09","country":"Niger","region":"Tahoua Region","city":"Tahoua","bio":"Posé mais déterminé, j'aime la musique, la lecture et les longues discussions. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Cinéma","Musique","Nature","Lecture"],"denomination":"Évangélique (EERN)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.ne.05@profils-virtuels.yona.invalid","first_name":"Sarah","last_name":"Harouna","gender":"female","birth_date":"1998-04-05","country":"Niger","region":"Dosso Region","city":"Dosso","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la lecture. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Mode","Cuisine","Cinéma"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.ne.06@profils-virtuels.yona.invalid","first_name":"Silas","last_name":"Djibo","gender":"male","birth_date":"1991-06-22","country":"Niger","region":"Agadez","city":"Agadez","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. Le Psaume 23 m'accompagne depuis toujours. J'attends une femme de foi, douce et pleine de joie.","interests":["Sport","Mode"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.ne.07@profils-virtuels.yona.invalid","first_name":"Priscille","last_name":"Kountché","gender":"female","birth_date":"1998-01-15","country":"Niger","region":"Tillabéri Region","city":"Tillabéri","bio":"Douce mais déterminée, j'aime la danse, la mode et les longues discussions. Je suis engagée dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cinéma","Danse","Bénévolat","Mode"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.ne.08@profils-virtuels.yona.invalid","first_name":"Paul","last_name":"Maïga","gender":"male","birth_date":"1996-02-08","country":"Niger","region":"Tahoua Region","city":"Birni N Konni","bio":"Souriant et attentionné, j'aime le cinéma et la mode. Ma foi guide chacune de mes décisions. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Mode","Cinéma"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.ne.09@profils-virtuels.yona.invalid","first_name":"Marie","last_name":"Hamani","gender":"female","birth_date":"1988-11-30","country":"Niger","region":"Dosso Region","city":"Gaya","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Louange","Nature","Bénévolat"],"denomination":"Évangélique (EERN)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":29,"max_age":47},
{"email":"virtuel.ne.10@profils-virtuels.yona.invalid","first_name":"Daniel","last_name":"Abdou","gender":"male","birth_date":"2003-02-28","country":"Niger","region":"Tahoua Region","city":"Madaoua","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de sport. Je suis engagé dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Danse","Cuisine","Sport"],"denomination":"Évangélique (EERN)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.ne.11@profils-virtuels.yona.invalid","first_name":"Tabitha","last_name":"Amadou","gender":"female","birth_date":"1993-08-28","country":"Niger","region":"Niamey","city":"Niamey","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le sport. La prière rythme mes journées. J'attends un homme de foi, doux et responsable.","interests":["Lecture","Sport","Louange"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.ne.12@profils-virtuels.yona.invalid","first_name":"Gédéon","last_name":"Boubacar","gender":"male","birth_date":"1981-08-28","country":"Niger","region":"Maradi Region","city":"Maradi","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de bénévolat. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Cuisine"],"denomination":"Évangélique (EERN)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.ne.13@profils-virtuels.yona.invalid","first_name":"Abigaïl","last_name":"Garba","gender":"female","birth_date":"1998-08-26","country":"Niger","region":"Zinder Region","city":"Zinder","bio":"Douce mais déterminée, j'aime le bénévolat, les voyages et les longues discussions. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Voyages","Bénévolat"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.ne.14@profils-virtuels.yona.invalid","first_name":"Benjamin","last_name":"Ousmane","gender":"male","birth_date":"1984-05-17","country":"Niger","region":"Tahoua Region","city":"Tahoua","bio":"Souriant et attentionné, j'aime les voyages et les balades dans la nature. Je suis engagé dans le groupe de jeunes de ma paroisse. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Voyages","Sport","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.ne.15@profils-virtuels.yona.invalid","first_name":"Hannah","last_name":"Seyni","gender":"female","birth_date":"1998-08-09","country":"Niger","region":"Dosso Region","city":"Dosso","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de lecture. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Lecture"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.ne.16@profils-virtuels.yona.invalid","first_name":"Jean","last_name":"Zakari","gender":"male","birth_date":"1997-10-02","country":"Niger","region":"Agadez","city":"Agadez","bio":"Fils de Dieu avant tout, je trouve ma joie dans le sport et la photographie. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Sport","Lecture"],"denomination":"Évangélique (EERN)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.ne.17@profils-virtuels.yona.invalid","first_name":"Deborah","last_name":"Saidou","gender":"female","birth_date":"1978-01-01","country":"Niger","region":"Tillabéri Region","city":"Tillabéri","bio":"Je suis une femme simple, passionnée par la photographie et le sport. Je chante dans la chorale de mon église. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Photographie","Voyages","Sport"],"denomination":"Évangélique (EERN)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.ne.18@profils-virtuels.yona.invalid","first_name":"Nathan","last_name":"Souley","gender":"male","birth_date":"1992-03-30","country":"Niger","region":"Tahoua Region","city":"Birni N Konni","bio":"Je suis un homme simple, passionné par la louange et le sport. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Louange"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.ne.19@profils-virtuels.yona.invalid","first_name":"Lydie","last_name":"Yacouba","gender":"female","birth_date":"1978-02-21","country":"Niger","region":"Dosso Region","city":"Gaya","bio":"Je suis une femme simple, passionnée par le sport et le bénévolat. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Musique","Sport","Cinéma","Bénévolat"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.ne.20@profils-virtuels.yona.invalid","first_name":"Aaron","last_name":"Tanko","gender":"male","birth_date":"1988-01-16","country":"Niger","region":"Tahoua Region","city":"Madaoua","bio":"Je suis un homme simple, passionné par les balades dans la nature et le cinéma. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Nature","Cinéma"],"denomination":"Évangélique (EERN)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.ne.21@profils-virtuels.yona.invalid","first_name":"Salomé","last_name":"Issa","gender":"female","birth_date":"1997-01-13","country":"Niger","region":"Niamey","city":"Niamey","bio":"Douce mais déterminée, j'aime la photographie, le bénévolat et les longues discussions. La prière rythme mes journées. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Photographie","Bénévolat"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.ne.22@profils-virtuels.yona.invalid","first_name":"Samuel","last_name":"Mahamadou","gender":"male","birth_date":"1983-10-20","country":"Niger","region":"Maradi Region","city":"Maradi","bio":"Fils de Dieu avant tout, je trouve ma joie dans la photographie et le sport. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Mode","Photographie","Sport","Danse"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":34,"max_age":52},
{"email":"virtuel.ne.23@profils-virtuels.yona.invalid","first_name":"Naomi","last_name":"Moussa","gender":"female","birth_date":"1997-04-15","country":"Niger","region":"Zinder Region","city":"Zinder","bio":"Douce mais déterminée, j'aime la lecture, les balades dans la nature et les longues discussions. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Lecture","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.ne.24@profils-virtuels.yona.invalid","first_name":"Marc","last_name":"Ibrahim","gender":"male","birth_date":"1985-11-04","country":"Niger","region":"Tahoua Region","city":"Tahoua","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux balades dans la nature. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Cuisine","Nature","Voyages"],"denomination":"Évangélique (EERN)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.ne.25@profils-virtuels.yona.invalid","first_name":"Ruth","last_name":"Harouna","gender":"female","birth_date":"2003-01-29","country":"Niger","region":"Dosso Region","city":"Dosso","bio":"Douce mais déterminée, j'aime la cuisine, le sport et les longues discussions. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cuisine","Sport"],"denomination":"Évangélique (EERN)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":32}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
