-- ============================================================
-- YONA — profils virtuels : fichier 5 sur 10
-- 75 profils : Togo, Bénin, Guinée.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.tg.01@profils-virtuels.yona.invalid","first_name":"Elinam","last_name":"Gbeasor","gender":"female","birth_date":"1990-07-13","country":"Togo","region":"Maritime","city":"Lomé","bio":"Je suis une femme simple, passionnée par le sport et le bénévolat. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Bénévolat","Nature","Cinéma"],"denomination":"Évangélique presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.tg.02@profils-virtuels.yona.invalid","first_name":"Sénamé","last_name":"Kudjoh","gender":"male","birth_date":"1978-03-24","country":"Togo","region":"Centrale","city":"Sokodé","bio":"Fils de Dieu avant tout, je trouve ma joie dans la danse et la louange. Ma foi guide chacune de mes décisions. J'attends une femme de foi, douce et pleine de joie.","interests":["Danse","Louange","Cinéma"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.tg.03@profils-virtuels.yona.invalid","first_name":"Dzifa","last_name":"Sossou","gender":"female","birth_date":"1996-10-24","country":"Togo","region":"Kara","city":"Kara","bio":"Fille de Dieu avant tout, je trouve ma joie dans la danse et le sport. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Danse"],"denomination":"Évangélique presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.tg.04@profils-virtuels.yona.invalid","first_name":"Yawo","last_name":"Dossou","gender":"male","birth_date":"1999-07-21","country":"Togo","region":"Plateaux","city":"Kpalimé","bio":"Fils de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la cuisine. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Nature","Bénévolat","Cuisine"],"denomination":"Évangélique presbytérienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.tg.05@profils-virtuels.yona.invalid","first_name":"Mawuena","last_name":"Tchalla","gender":"female","birth_date":"1991-01-04","country":"Togo","region":"Plateaux","city":"Atakpamé","bio":"Douce mais déterminée, j'aime le bénévolat, les voyages et les longues discussions. Je suis engagée dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Voyages","Musique","Bénévolat"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.tg.06@profils-virtuels.yona.invalid","first_name":"Mawuli","last_name":"Amouzou","gender":"male","birth_date":"2001-10-20","country":"Togo","region":"Maritime","city":"Aného","bio":"Posé mais déterminé, j'aime la mode, le bénévolat et les longues discussions. Je joue dans le groupe de louange de mon église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Mode"],"denomination":"Méthodiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.tg.07@profils-virtuels.yona.invalid","first_name":"Dédé","last_name":"Akakpo","gender":"female","birth_date":"1989-03-30","country":"Togo","region":"Maritime","city":"Tsévié","bio":"Douce mais déterminée, j'aime la cuisine, la lecture et les longues discussions. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Voyages","Sport","Cuisine","Lecture"],"denomination":"Méthodiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.tg.08@profils-virtuels.yona.invalid","first_name":"Dodji","last_name":"Afanou","gender":"male","birth_date":"1999-09-11","country":"Togo","region":"Savanes","city":"Dapaong","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Mode"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.tg.09@profils-virtuels.yona.invalid","first_name":"Enyonam","last_name":"Amegah","gender":"female","birth_date":"1997-05-30","country":"Togo","region":"Kara","city":"Bassar","bio":"Je suis une femme simple, passionnée par la lecture et les voyages. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Voyages","Lecture","Louange","Cinéma"],"denomination":"Évangélique presbytérienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.tg.10@profils-virtuels.yona.invalid","first_name":"Kodjo","last_name":"Agbéko","gender":"male","birth_date":"1992-06-01","country":"Togo","region":"Plateaux","city":"Notsé","bio":"Souriant et attentionné, j'aime les balades dans la nature et la lecture. Ma foi guide chacune de mes décisions. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Louange","Lecture","Nature"],"denomination":"Méthodiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.tg.11@profils-virtuels.yona.invalid","first_name":"Edem","last_name":"Johnson","gender":"female","birth_date":"1990-09-05","country":"Togo","region":"Maritime","city":"Lomé","bio":"Je suis une femme simple, passionnée par les voyages et la mode. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Mode","Voyages"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.tg.12@profils-virtuels.yona.invalid","first_name":"Kossi","last_name":"Mensah","gender":"male","birth_date":"2001-10-18","country":"Togo","region":"Centrale","city":"Sokodé","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la mode. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Musique","Photographie","Mode"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.tg.13@profils-virtuels.yona.invalid","first_name":"Ayaba","last_name":"Klutse","gender":"female","birth_date":"1977-01-09","country":"Togo","region":"Kara","city":"Kara","bio":"Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de musique. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Musique"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.tg.14@profils-virtuels.yona.invalid","first_name":"Koffi","last_name":"Olympio","gender":"male","birth_date":"1999-05-03","country":"Togo","region":"Plateaux","city":"Kpalimé","bio":"Chaque journée est un cadeau de Dieu : je la remplis de balades dans la nature et de musique. J'aide à l'organisation des sorties de l'église. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Musique"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.tg.15@profils-virtuels.yona.invalid","first_name":"Yawa","last_name":"Agbodjan","gender":"female","birth_date":"2003-10-19","country":"Togo","region":"Plateaux","city":"Atakpamé","bio":"Chaque journée est un cadeau de Dieu : je la remplis de voyages et de photographie. Je suis engagée dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Lecture","Nature","Photographie","Voyages"],"denomination":"Évangélique presbytérienne","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.tg.16@profils-virtuels.yona.invalid","first_name":"Kafui","last_name":"Ahadji","gender":"male","birth_date":"1978-12-07","country":"Togo","region":"Maritime","city":"Aného","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la cuisine. Je joue dans le groupe de louange de mon église. J'attends une femme de foi, douce et pleine de joie.","interests":["Cuisine","Lecture","Voyages"],"denomination":"Évangélique presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.tg.17@profils-virtuels.yona.invalid","first_name":"Akossiwa","last_name":"Lawson","gender":"female","birth_date":"1984-09-22","country":"Togo","region":"Maritime","city":"Tsévié","bio":"Je suis une femme simple, passionnée par la danse et la lecture. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Lecture"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.tg.18@profils-virtuels.yona.invalid","first_name":"Eyram","last_name":"Kpodar","gender":"male","birth_date":"2003-05-08","country":"Togo","region":"Savanes","city":"Dapaong","bio":"Fils de Dieu avant tout, je trouve ma joie dans la danse et le sport. Je joue dans le groupe de louange de mon église. J'attends une femme de foi, douce et pleine de joie.","interests":["Danse","Voyages","Cinéma","Sport"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.tg.19@profils-virtuels.yona.invalid","first_name":"Kafui","last_name":"Adjavon","gender":"female","birth_date":"1979-03-13","country":"Togo","region":"Kara","city":"Bassar","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la lecture. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Danse","Lecture"],"denomination":"Méthodiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.tg.20@profils-virtuels.yona.invalid","first_name":"Komla","last_name":"Ekoué","gender":"male","birth_date":"2000-05-25","country":"Togo","region":"Plateaux","city":"Notsé","bio":"Calme et joyeux, je partage mon temps entre mon travail et la mode. Je joue dans le groupe de louange de mon église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Mode","Cinéma","Cuisine"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.tg.21@profils-virtuels.yona.invalid","first_name":"Esinam","last_name":"Gbeasor","gender":"female","birth_date":"2002-06-06","country":"Togo","region":"Maritime","city":"Lomé","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la danse. J'aime méditer la Parole chaque matin. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Danse","Photographie","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.tg.22@profils-virtuels.yona.invalid","first_name":"Yao","last_name":"Kudjoh","gender":"male","birth_date":"1985-04-23","country":"Togo","region":"Centrale","city":"Sokodé","bio":"Je suis un homme simple, passionné par les balades dans la nature et le cinéma. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Nature","Lecture","Cinéma"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.tg.23@profils-virtuels.yona.invalid","first_name":"Afi","last_name":"Sossou","gender":"female","birth_date":"1991-11-08","country":"Togo","region":"Kara","city":"Kara","bio":"Chaque journée est un cadeau de Dieu : je la remplis de mode et de cuisine. J'enseigne à l'école du dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cuisine","Nature","Mode","Musique"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.tg.24@profils-virtuels.yona.invalid","first_name":"Selom","last_name":"Dossou","gender":"male","birth_date":"1978-03-29","country":"Togo","region":"Plateaux","city":"Kpalimé","bio":"Posé mais déterminé, j'aime la mode, la cuisine et les longues discussions. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Cuisine","Photographie","Mode"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.tg.25@profils-virtuels.yona.invalid","first_name":"Akpénè","last_name":"Tchalla","gender":"female","birth_date":"1985-03-17","country":"Togo","region":"Plateaux","city":"Atakpamé","bio":"Douce mais déterminée, j'aime la musique, les voyages et les longues discussions. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Voyages","Musique"],"denomination":"Assemblées de Dieu","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.bj.01@profils-virtuels.yona.invalid","first_name":"Joëlle","last_name":"Zinsou","gender":"female","birth_date":"2001-07-09","country":"Bénin","region":"Littoral","city":"Cotonou","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Sport","Cinéma"],"denomination":"Méthodiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.bj.02@profils-virtuels.yona.invalid","first_name":"Fiacre","last_name":"Amoussou","gender":"male","birth_date":"1980-12-12","country":"Bénin","region":"Ouémé","city":"Porto-Novo","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la mode. La prière rythme mes journées. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Mode","Voyages","Nature"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.bj.03@profils-virtuels.yona.invalid","first_name":"Ornella","last_name":"Dossou-Yovo","gender":"female","birth_date":"1978-01-17","country":"Bénin","region":"Borgou","city":"Parakou","bio":"Souriante et attentionnée, j'aime les balades dans la nature et la danse. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Nature","Voyages","Danse"],"denomination":"Assemblées de Dieu","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.bj.04@profils-virtuels.yona.invalid","first_name":"Arnaud","last_name":"Houéto","gender":"male","birth_date":"1993-06-09","country":"Bénin","region":"Zou","city":"Abomey","bio":"Posé mais déterminé, j'aime la louange, la mode et les longues discussions. Je joue dans le groupe de louange de mon église. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Louange","Cinéma","Mode"],"denomination":"Méthodiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":24,"max_age":42},
{"email":"virtuel.bj.05@profils-virtuels.yona.invalid","first_name":"Adjoavi","last_name":"Hounsa","gender":"female","birth_date":"1996-07-31","country":"Bénin","region":"Atlantique","city":"Abomey-Calavi","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Sport","Danse","Musique","Bénévolat"],"denomination":"Méthodiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.bj.06@profils-virtuels.yona.invalid","first_name":"Hermann","last_name":"Ahouandjinou","gender":"male","birth_date":"2003-01-07","country":"Bénin","region":"Zou","city":"Bohicon","bio":"Je suis un homme simple, passionné par le bénévolat et la musique. Je suis engagé dans le groupe de jeunes de ma paroisse. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Musique"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.bj.07@profils-virtuels.yona.invalid","first_name":"Léonie","last_name":"Kpossou","gender":"female","birth_date":"1977-04-17","country":"Bénin","region":"Atakora","city":"Natitingou","bio":"Fille de Dieu avant tout, je trouve ma joie dans le cinéma et la danse. J'enseigne à l'école du dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Danse","Cinéma"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.bj.08@profils-virtuels.yona.invalid","first_name":"Lionel","last_name":"Adjovi","gender":"male","birth_date":"1998-10-08","country":"Bénin","region":"Mono","city":"Lokossa","bio":"Je suis un homme simple, passionné par la mode et la photographie. Je suis engagé dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Mode","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.bj.09@profils-virtuels.yona.invalid","first_name":"Bénédicte","last_name":"Agossou","gender":"female","birth_date":"1980-02-01","country":"Bénin","region":"Atlantique","city":"Ouidah","bio":"Douce mais déterminée, j'aime le cinéma, le sport et les longues discussions. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cinéma","Sport"],"denomination":"Église du christianisme céleste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.bj.10@profils-virtuels.yona.invalid","first_name":"Jérôme","last_name":"Gbaguidi","gender":"male","birth_date":"1983-10-25","country":"Bénin","region":"Donga","city":"Djougou","bio":"Posé mais déterminé, j'aime le bénévolat, la lecture et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Sport","Lecture","Bénévolat"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":34,"max_age":52},
{"email":"virtuel.bj.11@profils-virtuels.yona.invalid","first_name":"Dorothée","last_name":"Gnonlonfoun","gender":"female","birth_date":"1994-08-20","country":"Bénin","region":"Alibori","city":"Kandi","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la mode. Je suis engagée dans le groupe de jeunes de ma paroisse. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Photographie","Mode"],"denomination":"Méthodiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.bj.12@profils-virtuels.yona.invalid","first_name":"Christophe","last_name":"Hounkpatin","gender":"male","birth_date":"1987-12-18","country":"Bénin","region":"Collines","city":"Savalou","bio":"Je suis un homme simple, passionné par la lecture et la louange. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Voyages","Louange","Lecture"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":30,"max_age":48},
{"email":"virtuel.bj.13@profils-virtuels.yona.invalid","first_name":"Mariette","last_name":"Adéchian","gender":"female","birth_date":"2000-11-24","country":"Bénin","region":"Littoral","city":"Cotonou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de sport. J'aime méditer la Parole chaque matin. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Photographie"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.bj.14@profils-virtuels.yona.invalid","first_name":"Wilfried","last_name":"Tossou","gender":"male","birth_date":"1985-07-24","country":"Bénin","region":"Ouémé","city":"Porto-Novo","bio":"Fils de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la lecture. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Nature","Louange","Musique","Lecture"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.bj.15@profils-virtuels.yona.invalid","first_name":"Yvette","last_name":"Glèlè","gender":"female","birth_date":"1992-05-22","country":"Bénin","region":"Borgou","city":"Parakou","bio":"Je suis une femme simple, passionnée par le sport et la musique. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Louange","Sport","Bénévolat"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.bj.16@profils-virtuels.yona.invalid","first_name":"Romaric","last_name":"Sossa","gender":"male","birth_date":"1980-07-13","country":"Bénin","region":"Zou","city":"Abomey","bio":"Chaque journée est un cadeau de Dieu : je la remplis de voyages et de photographie. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Photographie","Cuisine","Voyages"],"denomination":"Église du christianisme céleste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.bj.17@profils-virtuels.yona.invalid","first_name":"Carmelle","last_name":"Akpovo","gender":"female","birth_date":"1987-09-23","country":"Bénin","region":"Atlantique","city":"Abomey-Calavi","bio":"Je suis une femme simple, passionnée par les balades dans la nature et le cinéma. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Sport","Nature","Mode"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.bj.18@profils-virtuels.yona.invalid","first_name":"Gildas","last_name":"Kiki","gender":"male","birth_date":"2001-10-22","country":"Bénin","region":"Zou","city":"Bohicon","bio":"Calme et joyeux, je partage mon temps entre mon travail et la mode. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Voyages","Danse","Sport","Mode"],"denomination":"Méthodiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.bj.19@profils-virtuels.yona.invalid","first_name":"Nadège","last_name":"Dansou","gender":"female","birth_date":"1987-05-11","country":"Bénin","region":"Atakora","city":"Natitingou","bio":"Souriante et attentionnée, j'aime le bénévolat et la cuisine. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Bénévolat","Cuisine"],"denomination":"Méthodiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.bj.20@profils-virtuels.yona.invalid","first_name":"Sylvain","last_name":"Houngbédji","gender":"male","birth_date":"1991-07-30","country":"Bénin","region":"Mono","city":"Lokossa","bio":"Chaque journée est un cadeau de Dieu : je la remplis de sport et de cuisine. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Photographie","Cuisine","Sport","Louange"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.bj.21@profils-virtuels.yona.invalid","first_name":"Gisèle","last_name":"Zinsou","gender":"female","birth_date":"2003-10-19","country":"Bénin","region":"Atlantique","city":"Ouidah","bio":"Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de cuisine. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Cuisine","Musique"],"denomination":"Église du christianisme céleste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.bj.22@profils-virtuels.yona.invalid","first_name":"Narcisse","last_name":"Amoussou","gender":"male","birth_date":"1995-08-13","country":"Bénin","region":"Donga","city":"Djougou","bio":"Calme et joyeux, je partage mon temps entre mon travail et le sport. Je suis engagé dans le groupe de jeunes de ma paroisse. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Nature","Sport"],"denomination":"Église du christianisme céleste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.bj.23@profils-virtuels.yona.invalid","first_name":"Rolande","last_name":"Dossou-Yovo","gender":"female","birth_date":"1983-07-09","country":"Bénin","region":"Alibori","city":"Kandi","bio":"Douce mais déterminée, j'aime le sport, le cinéma et les longues discussions. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Cinéma"],"denomination":"Église du christianisme céleste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":34,"max_age":52},
{"email":"virtuel.bj.24@profils-virtuels.yona.invalid","first_name":"Dieudonné","last_name":"Houéto","gender":"male","birth_date":"1979-08-22","country":"Bénin","region":"Collines","city":"Savalou","bio":"Je suis un homme simple, passionné par la photographie et la louange. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Musique","Danse","Louange","Photographie"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.bj.25@profils-virtuels.yona.invalid","first_name":"Elvire","last_name":"Hounsa","gender":"female","birth_date":"2001-07-27","country":"Bénin","region":"Littoral","city":"Cotonou","bio":"Souriante et attentionnée, j'aime la cuisine et la musique. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Musique","Cuisine"],"denomination":"Méthodiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.gn.01@profils-virtuels.yona.invalid","first_name":"Denise","last_name":"Koïvogui","gender":"female","birth_date":"1995-08-21","country":"Guinée","region":"Conakry","city":"Conakry","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la danse. J'enseigne à l'école du dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Danse"],"denomination":"Protestante évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.gn.02@profils-virtuels.yona.invalid","first_name":"Alphonse","last_name":"Sagno","gender":"male","birth_date":"1977-03-27","country":"Guinée","region":"Nzérékoré Region","city":"Nzérékoré","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de danse. J'aime méditer la Parole chaque matin. J'attends une femme de foi, douce et pleine de joie.","interests":["Danse","Photographie"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.gn.03@profils-virtuels.yona.invalid","first_name":"Agathe","last_name":"Soumah","gender":"female","birth_date":"1992-01-21","country":"Guinée","region":"Kankan Region","city":"Kankan","bio":"Souriante et attentionnée, j'aime le bénévolat et la danse. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Danse"],"denomination":"Protestante évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.gn.04@profils-virtuels.yona.invalid","first_name":"Raymond","last_name":"Théa","gender":"male","birth_date":"1985-10-19","country":"Guinée","region":"Kindia","city":"Kindia","bio":"Chaque journée est un cadeau de Dieu : je la remplis de balades dans la nature et de musique. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Danse","Musique","Louange"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.gn.05@profils-virtuels.yona.invalid","first_name":"Régine","last_name":"Lamah","gender":"female","birth_date":"1980-10-10","country":"Guinée","region":"Labé Region","city":"Labé","bio":"Je suis une femme simple, passionnée par la musique et le cinéma. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cinéma","Musique","Mode"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.gn.06@profils-virtuels.yona.invalid","first_name":"Étienne","last_name":"Kolié","gender":"male","birth_date":"1998-06-13","country":"Guinée","region":"Nzérékoré Region","city":"Gueckedou","bio":"Je suis un homme simple, passionné par la lecture et la cuisine. Je joue dans le groupe de louange de mon église. J'attends une femme de foi, douce et pleine de joie.","interests":["Cuisine","Lecture"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.gn.07@profils-virtuels.yona.invalid","first_name":"Pauline","last_name":"Kourouma","gender":"female","birth_date":"2003-06-02","country":"Guinée","region":"Nzérékoré Region","city":"Macenta","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la louange. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Cinéma"],"denomination":"Protestante évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.gn.08@profils-virtuels.yona.invalid","first_name":"Lucien","last_name":"Delamou","gender":"male","birth_date":"1995-10-29","country":"Guinée","region":"Faranah","city":"Kissidougou","bio":"Je suis un homme simple, passionné par les balades dans la nature et la danse. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Louange","Danse","Nature"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.gn.09@profils-virtuels.yona.invalid","first_name":"Marguerite","last_name":"Zogbélémou","gender":"female","birth_date":"1992-03-23","country":"Guinée","region":"Boké Region","city":"Boké","bio":"Douce mais déterminée, j'aime le bénévolat, le sport et les longues discussions. J'aime méditer la Parole chaque matin. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Danse","Bénévolat","Sport"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.gn.10@profils-virtuels.yona.invalid","first_name":"Pascal","last_name":"Haba","gender":"male","birth_date":"2002-07-08","country":"Guinée","region":"Mamou Region","city":"Mamou","bio":"Souriant et attentionné, j'aime la photographie et les balades dans la nature. Je sers à l'accueil de mon église le dimanche. J'attends une femme de foi, douce et pleine de joie.","interests":["Photographie","Nature","Voyages","Cuisine"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":33},
{"email":"virtuel.gn.11@profils-virtuels.yona.invalid","first_name":"Françoise","last_name":"Kpoghomou","gender":"female","birth_date":"1993-11-30","country":"Guinée","region":"Conakry","city":"Conakry","bio":"Fille de Dieu avant tout, je trouve ma joie dans le sport et la mode. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Mode","Sport"],"denomination":"Protestante évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.gn.12@profils-virtuels.yona.invalid","first_name":"Bernard","last_name":"Togba","gender":"male","birth_date":"1994-07-31","country":"Guinée","region":"Nzérékoré Region","city":"Nzérékoré","bio":"Calme et joyeux, je partage mon temps entre mon travail et le cinéma. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Cinéma","Mode"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.gn.13@profils-virtuels.yona.invalid","first_name":"Henriette","last_name":"Onivogui","gender":"female","birth_date":"1994-11-30","country":"Guinée","region":"Kankan Region","city":"Kankan","bio":"Je suis une femme simple, passionnée par la louange et la photographie. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Louange"],"denomination":"Protestante évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.gn.14@profils-virtuels.yona.invalid","first_name":"Fidèle","last_name":"Gbamou","gender":"male","birth_date":"2000-07-02","country":"Guinée","region":"Kindia","city":"Kindia","bio":"Souriant et attentionné, j'aime la mode et la lecture. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Lecture","Mode"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.gn.15@profils-virtuels.yona.invalid","first_name":"Lucie","last_name":"Mansaré","gender":"female","birth_date":"1992-09-09","country":"Guinée","region":"Labé Region","city":"Labé","bio":"Fille de Dieu avant tout, je trouve ma joie dans la danse et le cinéma. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Danse","Cinéma"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.gn.16@profils-virtuels.yona.invalid","first_name":"Georges","last_name":"Camara","gender":"male","birth_date":"1987-05-06","country":"Guinée","region":"Nzérékoré Region","city":"Gueckedou","bio":"Posé mais déterminé, j'aime la danse, les balades dans la nature et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Danse","Nature"],"denomination":"Protestante évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":30,"max_age":48},
{"email":"virtuel.gn.17@profils-virtuels.yona.invalid","first_name":"Victorine","last_name":"Loua","gender":"female","birth_date":"1982-06-04","country":"Guinée","region":"Nzérékoré Region","city":"Macenta","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la louange. J'enseigne à l'école du dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Louange"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.gn.18@profils-virtuels.yona.invalid","first_name":"Vincent","last_name":"Béavogui","gender":"male","birth_date":"1990-02-06","country":"Guinée","region":"Faranah","city":"Kissidougou","bio":"Je suis un homme simple, passionné par la musique et le bénévolat. Ma foi guide chacune de mes décisions. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Musique","Sport","Bénévolat","Voyages"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":27,"max_age":45},
{"email":"virtuel.gn.19@profils-virtuels.yona.invalid","first_name":"Germaine","last_name":"Guilavogui","gender":"female","birth_date":"2000-03-16","country":"Guinée","region":"Boké Region","city":"Boké","bio":"Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de louange. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Louange","Lecture","Bénévolat"],"denomination":"Protestante évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.gn.20@profils-virtuels.yona.invalid","first_name":"Jean","last_name":"Gomou","gender":"male","birth_date":"1987-03-05","country":"Guinée","region":"Mamou Region","city":"Mamou","bio":"Calme et joyeux, je partage mon temps entre mon travail et le bénévolat. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Cinéma","Sport"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":30,"max_age":48},
{"email":"virtuel.gn.21@profils-virtuels.yona.invalid","first_name":"Catherine","last_name":"Koïvogui","gender":"female","birth_date":"1988-11-07","country":"Guinée","region":"Conakry","city":"Conakry","bio":"Souriante et attentionnée, j'aime la musique et la photographie. Je chante dans la chorale de mon église. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Musique","Photographie","Sport"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":29,"max_age":47},
{"email":"virtuel.gn.22@profils-virtuels.yona.invalid","first_name":"Marcel","last_name":"Sagno","gender":"male","birth_date":"1993-05-09","country":"Guinée","region":"Nzérékoré Region","city":"Nzérékoré","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. Je joue dans le groupe de louange de mon église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Lecture","Danse","Musique"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":24,"max_age":42},
{"email":"virtuel.gn.23@profils-virtuels.yona.invalid","first_name":"Simone","last_name":"Soumah","gender":"female","birth_date":"1995-03-16","country":"Guinée","region":"Kankan Region","city":"Kankan","bio":"Fille de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la lecture. Je suis engagée dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Nature"],"denomination":"Protestante évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.gn.24@profils-virtuels.yona.invalid","first_name":"Célestin","last_name":"Théa","gender":"male","birth_date":"1978-02-15","country":"Guinée","region":"Kindia","city":"Kindia","bio":"Souriant et attentionné, j'aime la lecture et les voyages. J'aime méditer la Parole chaque matin. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Voyages","Lecture","Photographie","Bénévolat"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.gn.25@profils-virtuels.yona.invalid","first_name":"Jeanne","last_name":"Lamah","gender":"female","birth_date":"1984-08-12","country":"Guinée","region":"Labé Region","city":"Labé","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de danse. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Cuisine","Mode","Danse","Cinéma"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":33,"max_age":51}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
