-- ============================================================
-- YONA — profils virtuels : fichier 6 sur 10
-- 75 profils : Tchad, Centrafrique, Madagascar.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.td.01@profils-virtuels.yona.invalid","first_name":"Rachel","last_name":"Nodjitolnan","gender":"female","birth_date":"1982-10-19","country":"Tchad","region":"N'Djaména","city":"N'Djamena","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. La prière rythme mes journées. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Photographie","Danse","Voyages","Nature"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.td.02@profils-virtuels.yona.invalid","first_name":"Patrice","last_name":"Djimasngar","gender":"male","birth_date":"1991-06-26","country":"Tchad","region":"Logone Occidental","city":"Moundou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de mode et de photographie. Ma foi guide chacune de mes décisions. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Mode","Photographie"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.td.03@profils-virtuels.yona.invalid","first_name":"Mbaïrangar","last_name":"Djasrabé","gender":"female","birth_date":"1997-08-01","country":"Tchad","region":"Moyen-Chari","city":"Sarh","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Voyages","Bénévolat"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.td.04@profils-virtuels.yona.invalid","first_name":"Djimadoum","last_name":"Mianbé","gender":"male","birth_date":"1989-07-09","country":"Tchad","region":"Ouadaï","city":"Abéché","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au cinéma. Le Psaume 23 m'accompagne depuis toujours. J'attends une femme de foi, douce et pleine de joie.","interests":["Musique","Cinéma","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.td.05@profils-virtuels.yona.invalid","first_name":"Naomie","last_name":"Ngakoutou","gender":"female","birth_date":"1995-05-03","country":"Tchad","region":"Tandjilé","city":"Kelo","bio":"Fille de Dieu avant tout, je trouve ma joie dans les balades dans la nature et le bénévolat. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Bénévolat","Lecture","Nature"],"denomination":"Assemblées chrétiennes","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.td.06@profils-virtuels.yona.invalid","first_name":"Ferdinand","last_name":"Mbaïlemdana","gender":"male","birth_date":"1994-09-29","country":"Tchad","region":"Mandoul","city":"Koumra","bio":"Posé mais déterminé, j'aime la louange, les balades dans la nature et les longues discussions. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Louange","Nature","Cinéma"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.td.07@profils-virtuels.yona.invalid","first_name":"Félicité","last_name":"Kladoumbaye","gender":"female","birth_date":"1989-11-28","country":"Tchad","region":"Logone Oriental","city":"Doba","bio":"Je suis une femme simple, passionnée par la danse et la mode. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Mode","Danse"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.td.08@profils-virtuels.yona.invalid","first_name":"Ndilbé","last_name":"Toïdé","gender":"male","birth_date":"1984-12-09","country":"Tchad","region":"Mayo-Kebbi Ouest","city":"Pala","bio":"Fils de Dieu avant tout, je trouve ma joie dans le cinéma et le sport. Je joue dans le groupe de louange de mon église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Mode","Bénévolat","Cinéma","Sport"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.td.09@profils-virtuels.yona.invalid","first_name":"Ndéïdoum","last_name":"Allarassem","gender":"female","birth_date":"1999-05-18","country":"Tchad","region":"Mayo-Kebbi Est","city":"Bongor","bio":"Fille de Dieu avant tout, je trouve ma joie dans les voyages et la lecture. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Lecture","Mode"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.td.10@profils-virtuels.yona.invalid","first_name":"Daniel","last_name":"Ngarlejy","gender":"male","birth_date":"1984-04-16","country":"Tchad","region":"Tandjilé","city":"Laï","bio":"Je suis un homme simple, passionné par les voyages et les balades dans la nature. La prière rythme mes journées. J'attends une femme de foi, douce et pleine de joie.","interests":["Nature","Voyages","Cuisine","Louange"],"denomination":"Assemblées chrétiennes","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.td.11@profils-virtuels.yona.invalid","first_name":"Pascaline","last_name":"Ngarmadji","gender":"female","birth_date":"2003-11-06","country":"Tchad","region":"N'Djaména","city":"N'Djamena","bio":"Fille de Dieu avant tout, je trouve ma joie dans la cuisine et le sport. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Danse","Sport","Cuisine"],"denomination":"Assemblées chrétiennes","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.td.12@profils-virtuels.yona.invalid","first_name":"Timothée","last_name":"Doumgor","gender":"male","birth_date":"1980-05-27","country":"Tchad","region":"Logone Occidental","city":"Moundou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de sport. Je suis engagé dans le groupe de jeunes de ma paroisse. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Danse","Lecture","Sport","Cuisine"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.td.13@profils-virtuels.yona.invalid","first_name":"Achta","last_name":"Yamadji","gender":"female","birth_date":"1986-06-17","country":"Tchad","region":"Moyen-Chari","city":"Sarh","bio":"Douce mais déterminée, j'aime le sport, la photographie et les longues discussions. Je suis engagée dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Sport","Photographie"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.td.14@profils-virtuels.yona.invalid","first_name":"Ezéchiel","last_name":"Beassemda","gender":"male","birth_date":"1997-05-26","country":"Tchad","region":"Ouadaï","city":"Abéché","bio":"Calme et joyeux, je partage mon temps entre mon travail et les balades dans la nature. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Lecture","Danse","Nature","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.td.15@profils-virtuels.yona.invalid","first_name":"Honorine","last_name":"Ndoubabé","gender":"female","birth_date":"1979-08-14","country":"Tchad","region":"Tandjilé","city":"Kelo","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la lecture. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Lecture","Danse","Voyages"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.td.16@profils-virtuels.yona.invalid","first_name":"Rimtebaye","last_name":"Remadji","gender":"male","birth_date":"1984-02-11","country":"Tchad","region":"Mandoul","city":"Koumra","bio":"Souriant et attentionné, j'aime les voyages et la danse. La prière rythme mes journées. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Danse","Voyages","Photographie"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.td.17@profils-virtuels.yona.invalid","first_name":"Gisèle","last_name":"Kemkoye","gender":"female","birth_date":"1997-06-05","country":"Tchad","region":"Logone Oriental","city":"Doba","bio":"Souriante et attentionnée, j'aime la musique et la mode. Je chante dans la chorale de mon église. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Musique","Mode"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.td.18@profils-virtuels.yona.invalid","first_name":"Blaise","last_name":"Naïbei","gender":"male","birth_date":"1989-07-23","country":"Tchad","region":"Mayo-Kebbi Ouest","city":"Pala","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Nature","Sport","Cuisine"],"denomination":"Assemblées chrétiennes","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.td.19@profils-virtuels.yona.invalid","first_name":"Ruth","last_name":"Ngaba","gender":"female","birth_date":"1988-08-12","country":"Tchad","region":"Mayo-Kebbi Est","city":"Bongor","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de louange. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Mode","Louange","Photographie","Lecture"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":29,"max_age":47},
{"email":"virtuel.td.20@profils-virtuels.yona.invalid","first_name":"Clément","last_name":"Mbaïdoum","gender":"male","birth_date":"2000-08-23","country":"Tchad","region":"Tandjilé","city":"Laï","bio":"Chaque journée est un cadeau de Dieu : je la remplis de voyages et de mode. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Musique","Mode","Cinéma"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.td.21@profils-virtuels.yona.invalid","first_name":"Esther","last_name":"Nodjitolnan","gender":"female","birth_date":"1985-11-29","country":"Tchad","region":"N'Djaména","city":"N'Djamena","bio":"Fille de Dieu avant tout, je trouve ma joie dans les voyages et la louange. Je chante dans la chorale de mon église. J'attends un homme de foi, doux et responsable.","interests":["Voyages","Louange"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.td.22@profils-virtuels.yona.invalid","first_name":"Ngarta","last_name":"Djimasngar","gender":"male","birth_date":"1989-04-04","country":"Tchad","region":"Logone Occidental","city":"Moundou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de voyages. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Louange","Voyages","Cinéma"],"denomination":"Assemblées chrétiennes","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.td.23@profils-virtuels.yona.invalid","first_name":"Rosine","last_name":"Djasrabé","gender":"female","birth_date":"1986-11-12","country":"Tchad","region":"Moyen-Chari","city":"Sarh","bio":"Fille de Dieu avant tout, je trouve ma joie dans la photographie et les voyages. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Voyages","Photographie","Mode"],"denomination":"Assemblées chrétiennes","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.td.24@profils-virtuels.yona.invalid","first_name":"Alain","last_name":"Mianbé","gender":"male","birth_date":"1983-01-01","country":"Tchad","region":"Ouadaï","city":"Abéché","bio":"Fils de Dieu avant tout, je trouve ma joie dans le cinéma et la mode. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Mode","Cinéma"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":34,"max_age":52},
{"email":"virtuel.td.25@profils-virtuels.yona.invalid","first_name":"Déborah","last_name":"Ngakoutou","gender":"female","birth_date":"1989-01-28","country":"Tchad","region":"Tandjilé","city":"Kelo","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la cuisine. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Mode","Lecture","Cuisine"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.cf.01@profils-virtuels.yona.invalid","first_name":"Ginette","last_name":"Nganatouwa","gender":"female","birth_date":"1997-05-15","country":"Centrafrique","region":"Bangui","city":"Bangui","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les balades dans la nature. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Nature","Sport"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.cf.02@profils-virtuels.yona.invalid","first_name":"Jean-Pierre","last_name":"Sanzé","gender":"male","birth_date":"1982-07-08","country":"Centrafrique","region":"Ombella-M'Poko","city":"Bimbo","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. Je joue dans le groupe de louange de mon église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Photographie","Mode"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.cf.03@profils-virtuels.yona.invalid","first_name":"Diane","last_name":"Yakété","gender":"female","birth_date":"1993-07-27","country":"Centrafrique","region":"Mambéré-Kadéï","city":"Berbérati","bio":"Je suis une femme simple, passionnée par les balades dans la nature et la mode. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Mode","Musique","Lecture"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.cf.04@profils-virtuels.yona.invalid","first_name":"Rodrigue","last_name":"Yangongo","gender":"male","birth_date":"1989-03-29","country":"Centrafrique","region":"Mambéré","city":"Carnot","bio":"Posé mais déterminé, j'aime la musique, le cinéma et les longues discussions. Je joue dans le groupe de louange de mon église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Cinéma","Lecture","Musique"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.cf.05@profils-virtuels.yona.invalid","first_name":"Prisca","last_name":"Sélébangue","gender":"female","birth_date":"1998-11-03","country":"Centrafrique","region":"Ouaka","city":"Bambari","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la cuisine. J'enseigne à l'école du dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Cuisine"],"denomination":"Apostolique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.cf.06@profils-virtuels.yona.invalid","first_name":"Hippolyte","last_name":"Gaba","gender":"male","birth_date":"1993-07-30","country":"Centrafrique","region":"Nana-Mambéré","city":"Bouar","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux voyages. Je suis engagé dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Danse","Voyages","Mode"],"denomination":"Apostolique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":24,"max_age":42},
{"email":"virtuel.cf.07@profils-virtuels.yona.invalid","first_name":"Anicette","last_name":"Wanzet","gender":"female","birth_date":"1982-08-05","country":"Centrafrique","region":"Ouham","city":"Bossangoa","bio":"Chaque journée est un cadeau de Dieu : je la remplis de mode et de voyages. J'enseigne à l'école du dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Mode"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.cf.08@profils-virtuels.yona.invalid","first_name":"Gervais","last_name":"Ngaïkoïsset","gender":"male","birth_date":"1992-07-15","country":"Centrafrique","region":"Haute-Kotto","city":"Bria","bio":"Chaque journée est un cadeau de Dieu : je la remplis de musique et de photographie. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Musique","Photographie","Cinéma","Bénévolat"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.cf.09@profils-virtuels.yona.invalid","first_name":"Laurence","last_name":"Zanga","gender":"female","birth_date":"1979-11-02","country":"Centrafrique","region":"Mbomou","city":"Bangassou","bio":"Douce mais déterminée, j'aime le sport, la danse et les longues discussions. Je chante dans la chorale de mon église. J'attends un homme de foi, doux et responsable.","interests":["Danse","Sport"],"denomination":"Apostolique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.cf.10@profils-virtuels.yona.invalid","first_name":"Nestor","last_name":"Tolngar","gender":"male","birth_date":"1996-07-25","country":"Centrafrique","region":"Sangha-Mbaéré","city":"Nola","bio":"Calme et joyeux, je partage mon temps entre mon travail et les balades dans la nature. J'aime méditer la Parole chaque matin. J'attends une femme de foi, douce et pleine de joie.","interests":["Lecture","Cinéma","Nature"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.cf.11@profils-virtuels.yona.invalid","first_name":"Sandrine","last_name":"Zoumandji","gender":"female","birth_date":"1994-12-26","country":"Centrafrique","region":"Nana-Grébizi","city":"Kaga-Bandoro","bio":"Fille de Dieu avant tout, je trouve ma joie dans la musique et la mode. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Mode","Musique","Voyages"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.cf.12@profils-virtuels.yona.invalid","first_name":"Martial","last_name":"Ngouandji","gender":"male","birth_date":"1991-07-15","country":"Centrafrique","region":"Bangui","city":"Bangui","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. Je suis engagé dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Photographie","Sport","Cuisine","Bénévolat"],"denomination":"Apostolique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.cf.13@profils-virtuels.yona.invalid","first_name":"Josiane","last_name":"Doko","gender":"female","birth_date":"1982-01-02","country":"Centrafrique","region":"Ombella-M'Poko","city":"Bimbo","bio":"Chaque journée est un cadeau de Dieu : je la remplis de danse et de photographie. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Photographie","Mode"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.cf.14@profils-virtuels.yona.invalid","first_name":"Prosper","last_name":"Mbaïkoua","gender":"male","birth_date":"1988-11-07","country":"Centrafrique","region":"Mambéré-Kadéï","city":"Berbérati","bio":"Chaque journée est un cadeau de Dieu : je la remplis de louange et de cinéma. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Cuisine","Louange"],"denomination":"Apostolique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.cf.15@profils-virtuels.yona.invalid","first_name":"Élodie","last_name":"Mandaba","gender":"female","birth_date":"2003-06-03","country":"Centrafrique","region":"Mambéré","city":"Carnot","bio":"Je suis une femme simple, passionnée par la cuisine et les balades dans la nature. J'enseigne à l'école du dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Cuisine","Nature"],"denomination":"Apostolique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.cf.16@profils-virtuels.yona.invalid","first_name":"Fidèle","last_name":"Kossi","gender":"male","birth_date":"1996-05-04","country":"Centrafrique","region":"Ouaka","city":"Bambari","bio":"Souriant et attentionné, j'aime le bénévolat et le sport. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Sport","Bénévolat","Mode"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.cf.17@profils-virtuels.yona.invalid","first_name":"Brigitte","last_name":"Feïkéram","gender":"female","birth_date":"1996-05-20","country":"Centrafrique","region":"Nana-Mambéré","city":"Bouar","bio":"Douce mais déterminée, j'aime la photographie, la musique et les longues discussions. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Musique","Photographie"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.cf.18@profils-virtuels.yona.invalid","first_name":"Wilfried","last_name":"Bozizé","gender":"male","birth_date":"1982-10-28","country":"Centrafrique","region":"Ouham","city":"Bossangoa","bio":"Posé mais déterminé, j'aime la cuisine, la musique et les longues discussions. J'aide à l'organisation des sorties de l'église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Musique","Cuisine"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.cf.19@profils-virtuels.yona.invalid","first_name":"Flora","last_name":"Gbazi","gender":"female","birth_date":"1985-01-18","country":"Centrafrique","region":"Haute-Kotto","city":"Bria","bio":"Fille de Dieu avant tout, je trouve ma joie dans la musique et le cinéma. Ma foi guide chacune de mes décisions. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Lecture","Musique","Sport","Cinéma"],"denomination":"Apostolique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.cf.20@profils-virtuels.yona.invalid","first_name":"Aristide","last_name":"Kosseyo","gender":"male","birth_date":"2000-03-24","country":"Centrafrique","region":"Mbomou","city":"Bangassou","bio":"Je suis un homme simple, passionné par la lecture et la louange. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Lecture","Louange"],"denomination":"Apostolique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.cf.21@profils-virtuels.yona.invalid","first_name":"Marina","last_name":"Nganatouwa","gender":"female","birth_date":"2001-02-18","country":"Centrafrique","region":"Sangha-Mbaéré","city":"Nola","bio":"Souriante et attentionnée, j'aime la musique et la photographie. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Photographie"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.cf.22@profils-virtuels.yona.invalid","first_name":"Bertrand","last_name":"Sanzé","gender":"male","birth_date":"1986-08-19","country":"Centrafrique","region":"Nana-Grébizi","city":"Kaga-Bandoro","bio":"Fils de Dieu avant tout, je trouve ma joie dans la mode et le cinéma. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Nature","Louange","Cinéma","Mode"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":31,"max_age":49},
{"email":"virtuel.cf.23@profils-virtuels.yona.invalid","first_name":"Nicole","last_name":"Yakété","gender":"female","birth_date":"2000-11-13","country":"Centrafrique","region":"Bangui","city":"Bangui","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la mode. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.","interests":["Musique","Mode"],"denomination":"Apostolique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.cf.24@profils-virtuels.yona.invalid","first_name":"Evariste","last_name":"Yangongo","gender":"male","birth_date":"1998-04-04","country":"Centrafrique","region":"Ombella-M'Poko","city":"Bimbo","bio":"Posé mais déterminé, j'aime les voyages, la photographie et les longues discussions. Je joue dans le groupe de louange de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Voyages"],"denomination":"Apostolique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.cf.25@profils-virtuels.yona.invalid","first_name":"Chantal","last_name":"Sélébangue","gender":"female","birth_date":"1986-07-08","country":"Centrafrique","region":"Mambéré-Kadéï","city":"Berbérati","bio":"Fille de Dieu avant tout, je trouve ma joie dans la cuisine et le sport. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Sport","Cuisine"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.mg.01@profils-virtuels.yona.invalid","first_name":"Nirina","last_name":"Rakotoarisoa","gender":"female","birth_date":"1997-08-03","country":"Madagascar","region":"Analamanga","city":"Antananarivo","bio":"Fille de Dieu avant tout, je trouve ma joie dans la mode et le cinéma. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Mode","Cinéma"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.mg.02@profils-virtuels.yona.invalid","first_name":"Tahina","last_name":"Razafindrakoto","gender":"male","birth_date":"1996-08-08","country":"Madagascar","region":"Atsinanana","city":"Toamasina","bio":"Posé mais déterminé, j'aime le bénévolat, la danse et les longues discussions. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Danse","Cinéma"],"denomination":"Luthérienne (FLM)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.mg.03@profils-virtuels.yona.invalid","first_name":"Voahirana","last_name":"Randriamanana","gender":"female","birth_date":"1979-08-26","country":"Madagascar","region":"Vakinankaratra","city":"Antsirabe","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux voyages. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Voyages","Mode","Louange"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.mg.04@profils-virtuels.yona.invalid","first_name":"Fanomezantsoa","last_name":"Rakotondrabe","gender":"male","birth_date":"1990-10-21","country":"Madagascar","region":"Boeny","city":"Mahajanga","bio":"Chaque journée est un cadeau de Dieu : je la remplis de louange et de voyages. Ma foi guide chacune de mes décisions. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Lecture","Louange"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":27,"max_age":45},
{"email":"virtuel.mg.05@profils-virtuels.yona.invalid","first_name":"Sitraka","last_name":"Randrianasolo","gender":"female","birth_date":"2000-10-08","country":"Madagascar","region":"Upper Matsiatra","city":"Fianarantsoa","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la musique. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Voyages","Danse","Musique"],"denomination":"Luthérienne (FLM)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.mg.06@profils-virtuels.yona.invalid","first_name":"Zo","last_name":"Ramanantsoa","gender":"male","birth_date":"1994-10-24","country":"Madagascar","region":"Atsimo-Andrefana","city":"Toliara","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de cinéma. Je joue dans le groupe de louange de mon église. J'attends une femme de foi, douce et pleine de joie.","interests":["Cuisine","Bénévolat","Sport","Cinéma"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.mg.07@profils-virtuels.yona.invalid","first_name":"Fanja","last_name":"Andrianarisoa","gender":"female","birth_date":"2001-01-27","country":"Madagascar","region":"Diana","city":"Antsiranana","bio":"Douce mais déterminée, j'aime la danse, le sport et les longues discussions. Je chante dans la chorale de mon église. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Danse","Sport"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.mg.08@profils-virtuels.yona.invalid","first_name":"Hery","last_name":"Ratsimbazafy","gender":"male","birth_date":"1991-12-09","country":"Madagascar","region":"Alaotra Mangoro","city":"Ambatondrazaka","bio":"Fils de Dieu avant tout, je trouve ma joie dans la louange et le sport. Je suis engagé dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Sport","Louange","Nature","Mode"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.mg.09@profils-virtuels.yona.invalid","first_name":"Mialy","last_name":"Ravelomanana","gender":"female","birth_date":"1978-08-28","country":"Madagascar","region":"Menabe","city":"Morondava","bio":"Souriante et attentionnée, j'aime le sport et les balades dans la nature. Je chante dans la chorale de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cuisine","Sport","Mode","Nature"],"denomination":"Luthérienne (FLM)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.mg.10@profils-virtuels.yona.invalid","first_name":"Haja","last_name":"Rakotomalala","gender":"male","birth_date":"1994-07-26","country":"Madagascar","region":"Amoron'i Mania","city":"Ambositra","bio":"Posé mais déterminé, j'aime la musique, les balades dans la nature et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Sport","Nature","Musique","Louange"],"denomination":"Protestante réformée (FJKM)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.mg.11@profils-virtuels.yona.invalid","first_name":"Onja","last_name":"Andriatsitohaina","gender":"female","birth_date":"1989-10-28","country":"Madagascar","region":"Fitovinany Region","city":"Manakara","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les balades dans la nature. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Bénévolat","Voyages","Musique"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.mg.12@profils-virtuels.yona.invalid","first_name":"Jean-Luc","last_name":"Rasolofonirina","gender":"male","birth_date":"1979-01-07","country":"Madagascar","region":"Analamanga","city":"Antananarivo","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux balades dans la nature. Ma foi guide chacune de mes décisions. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Nature","Cuisine"],"denomination":"Protestante réformée (FJKM)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.mg.13@profils-virtuels.yona.invalid","first_name":"Soa","last_name":"Razanamahefa","gender":"female","birth_date":"1987-02-25","country":"Madagascar","region":"Atsinanana","city":"Toamasina","bio":"Fille de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la mode. Ma foi guide chacune de mes décisions. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Cinéma","Mode","Cuisine","Nature"],"denomination":"Luthérienne (FLM)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.mg.14@profils-virtuels.yona.invalid","first_name":"Mamy","last_name":"Rasoanaivo","gender":"male","birth_date":"1988-02-07","country":"Madagascar","region":"Vakinankaratra","city":"Antsirabe","bio":"Fils de Dieu avant tout, je trouve ma joie dans la louange et le bénévolat. Je participe à un groupe de prière chaque semaine. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Bénévolat","Mode"],"denomination":"Luthérienne (FLM)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.mg.15@profils-virtuels.yona.invalid","first_name":"Noro","last_name":"Rajaonarison","gender":"female","birth_date":"1984-04-29","country":"Madagascar","region":"Boeny","city":"Mahajanga","bio":"Chaque journée est un cadeau de Dieu : je la remplis de balades dans la nature et de mode. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Mode","Nature","Sport","Cuisine"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.mg.16@profils-virtuels.yona.invalid","first_name":"Lova","last_name":"Andriamahefa","gender":"male","birth_date":"1977-07-24","country":"Madagascar","region":"Upper Matsiatra","city":"Fianarantsoa","bio":"Posé mais déterminé, j'aime la danse, la photographie et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Photographie"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.mg.17@profils-virtuels.yona.invalid","first_name":"Tiana","last_name":"Ramaroson","gender":"female","birth_date":"1987-11-23","country":"Madagascar","region":"Atsimo-Andrefana","city":"Toliara","bio":"Je suis une femme simple, passionnée par la mode et le sport. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Sport","Mode"],"denomination":"Luthérienne (FLM)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.mg.18@profils-virtuels.yona.invalid","first_name":"Tiana","last_name":"Randriamampionona","gender":"male","birth_date":"1994-11-20","country":"Madagascar","region":"Diana","city":"Antsiranana","bio":"Fils de Dieu avant tout, je trouve ma joie dans le cinéma et la musique. Je participe à un groupe de prière chaque semaine. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Mode","Musique","Louange","Cinéma"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.mg.19@profils-virtuels.yona.invalid","first_name":"Hanitra","last_name":"Rabemananjara","gender":"female","birth_date":"1995-06-18","country":"Madagascar","region":"Alaotra Mangoro","city":"Ambatondrazaka","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Bénévolat"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.mg.20@profils-virtuels.yona.invalid","first_name":"Rija","last_name":"Rabearivelo","gender":"male","birth_date":"2002-02-11","country":"Madagascar","region":"Menabe","city":"Morondava","bio":"Je suis un homme simple, passionné par la photographie et les voyages. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Louange","Photographie","Voyages"],"denomination":"Protestante réformée (FJKM)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":33},
{"email":"virtuel.mg.21@profils-virtuels.yona.invalid","first_name":"Miora","last_name":"Rakotoarisoa","gender":"female","birth_date":"1979-10-12","country":"Madagascar","region":"Amoron'i Mania","city":"Ambositra","bio":"Douce mais déterminée, j'aime la musique, le bénévolat et les longues discussions. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Mode","Bénévolat","Musique"],"denomination":"Luthérienne (FLM)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.mg.22@profils-virtuels.yona.invalid","first_name":"Fetra","last_name":"Razafindrakoto","gender":"male","birth_date":"1977-10-25","country":"Madagascar","region":"Fitovinany Region","city":"Manakara","bio":"Posé mais déterminé, j'aime la cuisine, la musique et les longues discussions. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Musique","Cuisine"],"denomination":"Luthérienne (FLM)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.mg.23@profils-virtuels.yona.invalid","first_name":"Rindra","last_name":"Randriamanana","gender":"female","birth_date":"1998-06-05","country":"Madagascar","region":"Analamanga","city":"Antananarivo","bio":"Douce mais déterminée, j'aime le sport, la cuisine et les longues discussions. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Lecture","Sport","Cuisine"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.mg.24@profils-virtuels.yona.invalid","first_name":"Toky","last_name":"Rakotondrabe","gender":"male","birth_date":"1999-03-17","country":"Madagascar","region":"Atsinanana","city":"Toamasina","bio":"Je suis un homme simple, passionné par les balades dans la nature et la louange. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Nature","Louange","Bénévolat"],"denomination":"Protestante réformée (FJKM)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.mg.25@profils-virtuels.yona.invalid","first_name":"Hasina","last_name":"Randrianasolo","gender":"female","birth_date":"1980-02-23","country":"Madagascar","region":"Vakinankaratra","city":"Antsirabe","bio":"Je suis une femme simple, passionnée par le bénévolat et la mode. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Mode","Sport","Bénévolat"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":37,"max_age":55}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
