-- ============================================================
-- YONA — profils virtuels : fichier 7 sur 10
-- 75 profils : Burundi, Rwanda, Djibouti.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.bi.01@profils-virtuels.yona.invalid","first_name":"Joséphine","last_name":"Bizimana","gender":"female","birth_date":"1996-04-16","country":"Burundi","region":"Bujumbura Mairie","city":"Bujumbura","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la cuisine. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Bénévolat","Cuisine"],"denomination":"Pentecôtiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.bi.02@profils-virtuels.yona.invalid","first_name":"Lambert","last_name":"Nkurunziza","gender":"male","birth_date":"1981-03-06","country":"Burundi","region":"Gitega","city":"Gitega","bio":"Souriant et attentionné, j'aime les balades dans la nature et le sport. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Sport","Voyages","Nature"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.bi.03@profils-virtuels.yona.invalid","first_name":"Irakoze","last_name":"Manirakiza","gender":"female","birth_date":"2003-03-06","country":"Burundi","region":"Ngozi","city":"Ngozi","bio":"Fille de Dieu avant tout, je trouve ma joie dans la louange et les voyages. La prière rythme mes journées. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Nature","Voyages","Danse","Louange"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.bi.04@profils-virtuels.yona.invalid","first_name":"Innocent","last_name":"Nshimirimana","gender":"male","birth_date":"1987-02-21","country":"Burundi","region":"Muyinga","city":"Muyinga","bio":"Chaque journée est un cadeau de Dieu : je la remplis de louange et de mode. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Cinéma","Danse","Mode","Louange"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":30,"max_age":48},
{"email":"virtuel.bi.05@profils-virtuels.yona.invalid","first_name":"Ange","last_name":"Hakizimana","gender":"female","birth_date":"1979-11-04","country":"Burundi","region":"Rumonge","city":"Rumonge","bio":"Souriante et attentionnée, j'aime la photographie et le bénévolat. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Photographie","Lecture","Bénévolat"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.bi.06@profils-virtuels.yona.invalid","first_name":"Ndayishimiye","last_name":"Uwimana","gender":"male","birth_date":"1998-08-02","country":"Burundi","region":"Kayanza","city":"Kayanza","bio":"Je suis un homme simple, passionné par la photographie et la mode. Je joue dans le groupe de louange de mon église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Photographie","Cuisine","Mode","Louange"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.bi.07@profils-virtuels.yona.invalid","first_name":"Odette","last_name":"Irakoze","gender":"female","birth_date":"1977-11-20","country":"Burundi","region":"Makamba","city":"Makamba","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la danse. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Danse","Bénévolat","Voyages"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.bi.08@profils-virtuels.yona.invalid","first_name":"Patrick","last_name":"Habonimana","gender":"male","birth_date":"2003-07-30","country":"Burundi","region":"Bururi","city":"Bururi","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de sport. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Cinéma","Sport"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.bi.09@profils-virtuels.yona.invalid","first_name":"Sandrine","last_name":"Niyongabo","gender":"female","birth_date":"1991-10-21","country":"Burundi","region":"Cibitoke","city":"Cibitoke","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. La prière rythme mes journées. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Danse","Bénévolat"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.bi.10@profils-virtuels.yona.invalid","first_name":"Éric","last_name":"Ndayisenga","gender":"male","birth_date":"2000-08-08","country":"Burundi","region":"Gitega","city":"Muramvya","bio":"Fils de Dieu avant tout, je trouve ma joie dans le sport et la danse. J'aime méditer la Parole chaque matin. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Sport","Danse","Musique"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.bi.11@profils-virtuels.yona.invalid","first_name":"Claudine","last_name":"Bigirimana","gender":"female","birth_date":"1999-12-07","country":"Burundi","region":"Bujumbura Mairie","city":"Bujumbura","bio":"Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de mode. Ma foi guide chacune de mes décisions. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Lecture","Mode","Bénévolat"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.bi.12@profils-virtuels.yona.invalid","first_name":"Fabrice","last_name":"Ntahomvukiye","gender":"male","birth_date":"1985-11-30","country":"Burundi","region":"Gitega","city":"Gitega","bio":"Posé mais déterminé, j'aime le bénévolat, la musique et les longues discussions. La prière rythme mes journées. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Bénévolat","Musique"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.bi.13@profils-virtuels.yona.invalid","first_name":"Fidélité","last_name":"Kwizera","gender":"female","birth_date":"1999-05-19","country":"Burundi","region":"Ngozi","city":"Ngozi","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la mode. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Louange","Mode"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.bi.14@profils-virtuels.yona.invalid","first_name":"Déo","last_name":"Niyonzima","gender":"male","birth_date":"1993-06-17","country":"Burundi","region":"Muyinga","city":"Muyinga","bio":"Calme et joyeux, je partage mon temps entre mon travail et les voyages. J'aide à l'organisation des sorties de l'église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Nature","Mode","Voyages","Musique"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":24,"max_age":42},
{"email":"virtuel.bi.15@profils-virtuels.yona.invalid","first_name":"Espérance","last_name":"Nizigiyimana","gender":"female","birth_date":"1986-01-06","country":"Burundi","region":"Rumonge","city":"Rumonge","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Bénévolat"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.bi.16@profils-virtuels.yona.invalid","first_name":"Claver","last_name":"Nibizi","gender":"male","birth_date":"1998-12-07","country":"Burundi","region":"Kayanza","city":"Kayanza","bio":"Calme et joyeux, je partage mon temps entre mon travail et les voyages. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Voyages"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.bi.17@profils-virtuels.yona.invalid","first_name":"Gloriose","last_name":"Ndayizeye","gender":"female","birth_date":"1980-06-23","country":"Burundi","region":"Makamba","city":"Makamba","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la louange. Je suis engagée dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Louange","Danse","Bénévolat"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.bi.18@profils-virtuels.yona.invalid","first_name":"Vianney","last_name":"Havyarimana","gender":"male","birth_date":"1982-08-27","country":"Burundi","region":"Bururi","city":"Bururi","bio":"Posé mais déterminé, j'aime le cinéma, les balades dans la nature et les longues discussions. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Danse","Nature","Cinéma"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.bi.19@profils-virtuels.yona.invalid","first_name":"Vestine","last_name":"Ciza","gender":"female","birth_date":"2000-01-16","country":"Burundi","region":"Cibitoke","city":"Cibitoke","bio":"Fille de Dieu avant tout, je trouve ma joie dans la louange et les balades dans la nature. Je suis engagée dans le groupe de jeunes de ma paroisse. Je crois au mariage, à la fidélité et au respect.","interests":["Louange","Nature","Lecture","Musique"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.bi.20@profils-virtuels.yona.invalid","first_name":"Alexis","last_name":"Ndikumana","gender":"male","birth_date":"1998-05-16","country":"Burundi","region":"Gitega","city":"Muramvya","bio":"Souriant et attentionné, j'aime la danse et les voyages. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Voyages","Sport","Danse","Cuisine"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.bi.21@profils-virtuels.yona.invalid","first_name":"Diane","last_name":"Bizimana","gender":"female","birth_date":"1995-08-30","country":"Burundi","region":"Bujumbura Mairie","city":"Bujumbura","bio":"Je suis une femme simple, passionnée par la danse et la cuisine. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cuisine","Mode","Danse","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.bi.22@profils-virtuels.yona.invalid","first_name":"Gédéon","last_name":"Nkurunziza","gender":"male","birth_date":"1981-01-14","country":"Burundi","region":"Gitega","city":"Gitega","bio":"Chaque journée est un cadeau de Dieu : je la remplis de balades dans la nature et de mode. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Mode","Nature"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.bi.23@profils-virtuels.yona.invalid","first_name":"Liliane","last_name":"Manirakiza","gender":"female","birth_date":"1977-12-08","country":"Burundi","region":"Ngozi","city":"Ngozi","bio":"Douce mais déterminée, j'aime la cuisine, les voyages et les longues discussions. La prière rythme mes journées. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Voyages","Cuisine"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.bi.24@profils-virtuels.yona.invalid","first_name":"Thierry","last_name":"Nshimirimana","gender":"male","birth_date":"1977-12-08","country":"Burundi","region":"Muyinga","city":"Muyinga","bio":"Fils de Dieu avant tout, je trouve ma joie dans la louange et la danse. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Danse","Louange"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.bi.25@profils-virtuels.yona.invalid","first_name":"Médiatrice","last_name":"Hakizimana","gender":"female","birth_date":"2000-05-20","country":"Burundi","region":"Rumonge","city":"Rumonge","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au cinéma. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Cinéma","Cuisine","Sport"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.rw.01@profils-virtuels.yona.invalid","first_name":"Josiane","last_name":"Nshimiyimana","gender":"female","birth_date":"1985-06-22","country":"Rwanda","region":"Kigali","city":"Kigali","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la photographie. Je chante dans la chorale de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Louange","Danse"],"denomination":"Pentecôtiste (ADEPR)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.rw.02@profils-virtuels.yona.invalid","first_name":"Jean-Claude","last_name":"Umutoni","gender":"male","birth_date":"1983-08-10","country":"Rwanda","region":"Southern Province","city":"Butare","bio":"Calme et joyeux, je partage mon temps entre mon travail et la louange. La prière rythme mes journées. J'attends une femme de foi, douce et pleine de joie.","interests":["Louange","Danse"],"denomination":"Pentecôtiste (ADEPR)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":34,"max_age":52},
{"email":"virtuel.rw.03@profils-virtuels.yona.invalid","first_name":"Sandrine","last_name":"Ndayisaba","gender":"female","birth_date":"2001-03-07","country":"Rwanda","region":"Western Province","city":"Gisenyi","bio":"Je suis une femme simple, passionnée par la lecture et la cuisine. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Danse","Lecture","Cuisine"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.rw.04@profils-virtuels.yona.invalid","first_name":"Aimable","last_name":"Iradukunda","gender":"male","birth_date":"1996-12-10","country":"Rwanda","region":"Northern Province","city":"Musanze","bio":"Fils de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la photographie. Je joue dans le groupe de louange de mon église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Nature","Photographie","Lecture"],"denomination":"Presbytérienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.rw.05@profils-virtuels.yona.invalid","first_name":"Esther","last_name":"Kalisa","gender":"female","birth_date":"1990-06-06","country":"Rwanda","region":"Northern Province","city":"Byumba","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la cuisine. Je suis engagée dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Nature","Cinéma","Cuisine","Photographie"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.rw.06@profils-virtuels.yona.invalid","first_name":"Yves","last_name":"Habimana","gender":"male","birth_date":"1989-03-20","country":"Rwanda","region":"Western Province","city":"Cyangugu","bio":"Je suis un homme simple, passionné par la photographie et la louange. J'aide à l'organisation des sorties de l'église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Photographie","Louange"],"denomination":"Pentecôtiste (ADEPR)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.rw.07@profils-virtuels.yona.invalid","first_name":"Vanessa","last_name":"Mukamana","gender":"female","birth_date":"1989-06-26","country":"Rwanda","region":"Western Province","city":"Kibuye","bio":"Fille de Dieu avant tout, je trouve ma joie dans le sport et la cuisine. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Sport","Bénévolat","Cuisine","Louange"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.rw.08@profils-virtuels.yona.invalid","first_name":"Emmanuel","last_name":"Niyitegeka","gender":"male","birth_date":"1997-01-11","country":"Rwanda","region":"Southern Province","city":"Gitarama","bio":"Je suis un homme simple, passionné par la danse et la louange. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Danse","Voyages","Musique","Louange"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.rw.09@profils-virtuels.yona.invalid","first_name":"Claudine","last_name":"Tuyishime","gender":"female","birth_date":"1982-11-17","country":"Rwanda","region":"Southern Province","city":"Nyanza","bio":"Fille de Dieu avant tout, je trouve ma joie dans la cuisine et les voyages. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Voyages","Cinéma"],"denomination":"Pentecôtiste (ADEPR)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.rw.10@profils-virtuels.yona.invalid","first_name":"Patrick","last_name":"Mutesi","gender":"male","birth_date":"1988-08-28","country":"Rwanda","region":"Eastern Province","city":"Rwamagana","bio":"Posé mais déterminé, j'aime les balades dans la nature, le cinéma et les longues discussions. Je suis engagé dans le groupe de jeunes de ma paroisse. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Bénévolat","Cuisine","Cinéma"],"denomination":"Pentecôtiste (ADEPR)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.rw.11@profils-virtuels.yona.invalid","first_name":"Grace","last_name":"Ishimwe","gender":"female","birth_date":"1985-05-26","country":"Rwanda","region":"Eastern Province","city":"Kibungo","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la cuisine. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Sport","Cuisine","Louange"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.rw.12@profils-virtuels.yona.invalid","first_name":"Clément","last_name":"Rukundo","gender":"male","birth_date":"1981-01-01","country":"Rwanda","region":"Southern Province","city":"Muhanga","bio":"Je suis un homme simple, passionné par la cuisine et la mode. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Mode","Cuisine"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.rw.13@profils-virtuels.yona.invalid","first_name":"Solange","last_name":"Uwimana","gender":"female","birth_date":"1992-02-03","country":"Rwanda","region":"Kigali","city":"Kigali","bio":"Souriante et attentionnée, j'aime la photographie et la musique. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Photographie"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.rw.14@profils-virtuels.yona.invalid","first_name":"Valens","last_name":"Mugisha","gender":"male","birth_date":"2001-09-12","country":"Rwanda","region":"Southern Province","city":"Butare","bio":"Posé mais déterminé, j'aime le sport, la lecture et les longues discussions. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Sport","Bénévolat","Musique"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.rw.15@profils-virtuels.yona.invalid","first_name":"Divine","last_name":"Gatera","gender":"female","birth_date":"2003-10-12","country":"Rwanda","region":"Western Province","city":"Gisenyi","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la louange. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Louange"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.rw.16@profils-virtuels.yona.invalid","first_name":"Eric","last_name":"Hakizimana","gender":"male","birth_date":"1978-03-06","country":"Rwanda","region":"Northern Province","city":"Musanze","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la cuisine. Je joue dans le groupe de louange de mon église. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Danse","Musique","Cuisine"],"denomination":"Presbytérienne","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.rw.17@profils-virtuels.yona.invalid","first_name":"Pacifique","last_name":"Niyonsaba","gender":"female","birth_date":"1999-02-21","country":"Rwanda","region":"Northern Province","city":"Byumba","bio":"Douce mais déterminée, j'aime la cuisine, la musique et les longues discussions. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Musique","Lecture"],"denomination":"Pentecôtiste (ADEPR)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.rw.18@profils-virtuels.yona.invalid","first_name":"Olivier","last_name":"Uwase","gender":"male","birth_date":"1986-01-29","country":"Rwanda","region":"Western Province","city":"Cyangugu","bio":"Posé mais déterminé, j'aime les voyages, la cuisine et les longues discussions. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Mode","Cuisine","Voyages"],"denomination":"Pentecôtiste (ADEPR)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":31,"max_age":49},
{"email":"virtuel.rw.19@profils-virtuels.yona.invalid","first_name":"Diane","last_name":"Munyaneza","gender":"female","birth_date":"1997-12-23","country":"Rwanda","region":"Western Province","city":"Kibuye","bio":"Souriante et attentionnée, j'aime la musique et le bénévolat. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Cuisine","Louange","Bénévolat"],"denomination":"Presbytérienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.rw.20@profils-virtuels.yona.invalid","first_name":"Didier","last_name":"Kayitesi","gender":"male","birth_date":"1980-03-06","country":"Rwanda","region":"Southern Province","city":"Gitarama","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au cinéma. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Cuisine","Nature"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.rw.21@profils-virtuels.yona.invalid","first_name":"Olive","last_name":"Nshimiyimana","gender":"female","birth_date":"1984-12-16","country":"Rwanda","region":"Southern Province","city":"Nyanza","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le sport. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Sport"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.rw.22@profils-virtuels.yona.invalid","first_name":"Thierry","last_name":"Umutoni","gender":"male","birth_date":"1981-06-14","country":"Rwanda","region":"Eastern Province","city":"Rwamagana","bio":"Posé mais déterminé, j'aime la musique, le cinéma et les longues discussions. Ma foi guide chacune de mes décisions. J'attends une femme de foi, douce et pleine de joie.","interests":["Cinéma","Louange","Musique"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.rw.23@profils-virtuels.yona.invalid","first_name":"Liliane","last_name":"Ndayisaba","gender":"female","birth_date":"1981-11-29","country":"Rwanda","region":"Eastern Province","city":"Kibungo","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la cuisine. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cuisine","Lecture"],"denomination":"Presbytérienne","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":36,"max_age":54},
{"email":"virtuel.rw.24@profils-virtuels.yona.invalid","first_name":"Gaspard","last_name":"Iradukunda","gender":"male","birth_date":"1995-01-11","country":"Rwanda","region":"Southern Province","city":"Muhanga","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la danse. Je joue dans le groupe de louange de mon église. Je crois au mariage, à la fidélité et au respect.","interests":["Cinéma","Bénévolat","Danse"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.rw.25@profils-virtuels.yona.invalid","first_name":"Alice","last_name":"Kalisa","gender":"female","birth_date":"1992-10-16","country":"Rwanda","region":"Kigali","city":"Kigali","bio":"Fille de Dieu avant tout, je trouve ma joie dans la louange et la lecture. Je suis engagée dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Louange","Lecture","Cuisine","Musique"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.dj.01@profils-virtuels.yona.invalid","first_name":"Sarah","last_name":"Hersi","gender":"female","birth_date":"2000-01-09","country":"Djibouti","region":"Djibouti","city":"Djibouti","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. J'aime méditer la Parole chaque matin. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Danse","Louange","Musique","Voyages"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.dj.02@profils-virtuels.yona.invalid","first_name":"Gabriel","last_name":"Ali","gender":"male","birth_date":"1991-03-05","country":"Djibouti","region":"Tadjourah","city":"Tadjoura","bio":"Calme et joyeux, je partage mon temps entre mon travail et la mode. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Mode","Lecture","Louange","Nature"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.dj.03@profils-virtuels.yona.invalid","first_name":"Élisabeth","last_name":"Houssein","gender":"female","birth_date":"2003-09-21","country":"Djibouti","region":"Obock","city":"Obock","bio":"Chaque journée est un cadeau de Dieu : je la remplis de mode et de voyages. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Musique","Bénévolat","Mode"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.dj.04@profils-virtuels.yona.invalid","first_name":"Paul","last_name":"Elmi","gender":"male","birth_date":"1984-08-23","country":"Djibouti","region":"Dikhil","city":"Dikhil","bio":"Fils de Dieu avant tout, je trouve ma joie dans la danse et la photographie. Ma foi guide chacune de mes décisions. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Photographie","Lecture","Danse","Sport"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.dj.05@profils-virtuels.yona.invalid","first_name":"Judith","last_name":"Aden","gender":"female","birth_date":"1977-01-30","country":"Djibouti","region":"Arta","city":"Arta","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la musique. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Lecture","Musique"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.dj.06@profils-virtuels.yona.invalid","first_name":"Thomas","last_name":"Said","gender":"male","birth_date":"2000-02-22","country":"Djibouti","region":"Djibouti","city":"Djibouti","bio":"Je suis un homme simple, passionné par la danse et la louange. Le Psaume 23 m'accompagne depuis toujours. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Louange","Danse"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.dj.07@profils-virtuels.yona.invalid","first_name":"Deborah","last_name":"Abdi","gender":"female","birth_date":"1994-08-28","country":"Djibouti","region":"Tadjourah","city":"Tadjoura","bio":"Douce mais déterminée, j'aime la photographie, les voyages et les longues discussions. Je chante dans la chorale de mon église. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Lecture","Voyages"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.dj.08@profils-virtuels.yona.invalid","first_name":"Michel","last_name":"Hassan","gender":"male","birth_date":"1988-06-17","country":"Djibouti","region":"Obock","city":"Obock","bio":"Chaque journée est un cadeau de Dieu : je la remplis de danse et de louange. Je suis engagé dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Danse","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.dj.09@profils-virtuels.yona.invalid","first_name":"Lydie","last_name":"Kamil","gender":"female","birth_date":"1994-08-29","country":"Djibouti","region":"Dikhil","city":"Dikhil","bio":"Douce mais déterminée, j'aime la lecture, les voyages et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Voyages","Photographie","Mode","Lecture"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.dj.10@profils-virtuels.yona.invalid","first_name":"Samuel","last_name":"Waberi","gender":"male","birth_date":"1999-02-11","country":"Djibouti","region":"Arta","city":"Arta","bio":"Calme et joyeux, je partage mon temps entre mon travail et le cinéma. J'aide à l'organisation des sorties de l'église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Louange","Cinéma","Photographie","Lecture"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.dj.11@profils-virtuels.yona.invalid","first_name":"Naomi","last_name":"Ahmed","gender":"female","birth_date":"2001-04-02","country":"Djibouti","region":"Djibouti","city":"Djibouti","bio":"Fille de Dieu avant tout, je trouve ma joie dans la danse et la photographie. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Photographie","Danse"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.dj.12@profils-virtuels.yona.invalid","first_name":"David","last_name":"Omar","gender":"male","birth_date":"1981-07-31","country":"Djibouti","region":"Tadjourah","city":"Tadjoura","bio":"Posé mais déterminé, j'aime la danse, le bénévolat et les longues discussions. Ma foi guide chacune de mes décisions. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Cuisine","Danse","Bénévolat"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.dj.13@profils-virtuels.yona.invalid","first_name":"Hanna","last_name":"Mohamed","gender":"female","birth_date":"2000-11-15","country":"Djibouti","region":"Obock","city":"Obock","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. J'aime méditer la Parole chaque matin. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Musique","Bénévolat"],"denomination":"Orthodoxe éthiopienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.dj.14@profils-virtuels.yona.invalid","first_name":"Jonathan","last_name":"Dirieh","gender":"male","birth_date":"1995-12-26","country":"Djibouti","region":"Dikhil","city":"Dikhil","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la lecture. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Lecture","Mode"],"denomination":"Orthodoxe éthiopienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.dj.15@profils-virtuels.yona.invalid","first_name":"Suzanne","last_name":"Youssouf","gender":"female","birth_date":"1986-04-20","country":"Djibouti","region":"Arta","city":"Arta","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la lecture. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Cinéma","Lecture"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.dj.16@profils-virtuels.yona.invalid","first_name":"Pierre","last_name":"Ibrahim","gender":"male","birth_date":"1979-10-09","country":"Djibouti","region":"Djibouti","city":"Djibouti","bio":"Je suis un homme simple, passionné par le sport et la lecture. Je joue dans le groupe de louange de mon église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Sport","Lecture"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.dj.17@profils-virtuels.yona.invalid","first_name":"Isabelle","last_name":"Guedi","gender":"female","birth_date":"1989-05-28","country":"Djibouti","region":"Tadjourah","city":"Tadjoura","bio":"Je suis une femme simple, passionnée par la photographie et la musique. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Musique"],"denomination":"Orthodoxe éthiopienne","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.dj.18@profils-virtuels.yona.invalid","first_name":"Jean","last_name":"Robleh","gender":"male","birth_date":"1996-10-28","country":"Djibouti","region":"Obock","city":"Obock","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la danse. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Cinéma","Voyages","Danse","Photographie"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.dj.19@profils-virtuels.yona.invalid","first_name":"Rachel","last_name":"Moussa","gender":"female","birth_date":"1986-02-01","country":"Djibouti","region":"Dikhil","city":"Dikhil","bio":"Je suis une femme simple, passionnée par le cinéma et la cuisine. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Cinéma","Cuisine"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.dj.20@profils-virtuels.yona.invalid","first_name":"Nathan","last_name":"Farah","gender":"male","birth_date":"1984-09-01","country":"Djibouti","region":"Arta","city":"Arta","bio":"Calme et joyeux, je partage mon temps entre mon travail et la louange. Le Psaume 23 m'accompagne depuis toujours. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Musique","Louange","Sport"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.dj.21@profils-virtuels.yona.invalid","first_name":"Myriam","last_name":"Hersi","gender":"female","birth_date":"1996-04-05","country":"Djibouti","region":"Djibouti","city":"Djibouti","bio":"Je suis une femme simple, passionnée par les balades dans la nature et la cuisine. Ma foi guide chacune de mes décisions. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Nature","Musique"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.dj.22@profils-virtuels.yona.invalid","first_name":"Marc","last_name":"Ali","gender":"male","birth_date":"1989-12-16","country":"Djibouti","region":"Tadjourah","city":"Tadjoura","bio":"Calme et joyeux, je partage mon temps entre mon travail et le cinéma. La prière rythme mes journées. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Lecture","Louange","Cinéma","Musique"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.dj.23@profils-virtuels.yona.invalid","first_name":"Anne","last_name":"Houssein","gender":"female","birth_date":"1997-03-26","country":"Djibouti","region":"Obock","city":"Obock","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la lecture. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Mode"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.dj.24@profils-virtuels.yona.invalid","first_name":"Élie","last_name":"Elmi","gender":"male","birth_date":"2003-08-16","country":"Djibouti","region":"Dikhil","city":"Dikhil","bio":"Posé mais déterminé, j'aime la mode, la louange et les longues discussions. Je sers à l'accueil de mon église le dimanche. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Mode","Louange","Voyages"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.dj.25@profils-virtuels.yona.invalid","first_name":"Clarisse","last_name":"Aden","gender":"female","birth_date":"1990-04-02","country":"Djibouti","region":"Arta","city":"Arta","bio":"Douce mais déterminée, j'aime la cuisine, la danse et les longues discussions. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Danse","Nature","Cuisine","Lecture"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":27,"max_age":45}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
