-- ============================================================
-- YONA — profils virtuels : fichier 8 sur 10
-- 75 profils : Comores, Maurice, Seychelles.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.km.01@profils-virtuels.yona.invalid","first_name":"Zaïnaba","last_name":"Djaffar","gender":"female","birth_date":"2002-04-10","country":"Comores","region":"Grande Comore","city":"Moroni","bio":"Chaque journée est un cadeau de Dieu : je la remplis de louange et de lecture. Ma foi guide chacune de mes décisions. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Nature","Voyages","Louange","Lecture"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.km.02@profils-virtuels.yona.invalid","first_name":"Mahamoud","last_name":"Ahamada","gender":"male","birth_date":"2000-03-20","country":"Comores","region":"Anjouan","city":"Moutsamoudou","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la cuisine. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Louange","Cinéma","Voyages","Cuisine"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.km.03@profils-virtuels.yona.invalid","first_name":"Mariama","last_name":"Oubeidillah","gender":"female","birth_date":"1980-02-19","country":"Comores","region":"Mohéli","city":"Fomboni","bio":"Fille de Dieu avant tout, je trouve ma joie dans la lecture et le bénévolat. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Lecture"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.km.04@profils-virtuels.yona.invalid","first_name":"Ibrahim","last_name":"Hassani","gender":"male","birth_date":"2000-10-01","country":"Comores","region":"Anjouan","city":"Domoni","bio":"Fils de Dieu avant tout, je trouve ma joie dans la photographie et la lecture. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Nature","Photographie","Bénévolat","Lecture"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.km.05@profils-virtuels.yona.invalid","first_name":"Ruth","last_name":"Hamada","gender":"female","birth_date":"1994-04-13","country":"Comores","region":"Grande Comore","city":"Mitsamiouli","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. Ma foi guide chacune de mes décisions. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cuisine","Cinéma","Bénévolat","Mode"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.km.06@profils-virtuels.yona.invalid","first_name":"Anfane","last_name":"Ibouroi","gender":"male","birth_date":"1985-01-27","country":"Comores","region":"Anjouan","city":"Ouani","bio":"Posé mais déterminé, j'aime la photographie, la louange et les longues discussions. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Louange","Cuisine","Photographie"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.km.07@profils-virtuels.yona.invalid","first_name":"Sitti","last_name":"Mohamed","gender":"female","birth_date":"1989-04-26","country":"Comores","region":"Grande Comore","city":"Moroni","bio":"Chaque journée est un cadeau de Dieu : je la remplis de danse et de balades dans la nature. J'enseigne à l'école du dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Danse"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.km.08@profils-virtuels.yona.invalid","first_name":"Faissoili","last_name":"Bacar","gender":"male","birth_date":"2000-04-05","country":"Comores","region":"Anjouan","city":"Moutsamoudou","bio":"Fils de Dieu avant tout, je trouve ma joie dans les voyages et la louange. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Bénévolat","Louange","Voyages"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.km.09@profils-virtuels.yona.invalid","first_name":"Nadjma","last_name":"Mbaé","gender":"female","birth_date":"1988-01-21","country":"Comores","region":"Mohéli","city":"Fomboni","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. La prière rythme mes journées. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Lecture","Voyages","Bénévolat","Mode"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":29,"max_age":47},
{"email":"virtuel.km.10@profils-virtuels.yona.invalid","first_name":"Daniel","last_name":"Said","gender":"male","birth_date":"2001-04-01","country":"Comores","region":"Anjouan","city":"Domoni","bio":"Calme et joyeux, je partage mon temps entre mon travail et les balades dans la nature. Je participe à un groupe de prière chaque semaine. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Nature"],"denomination":"Protestante","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.km.11@profils-virtuels.yona.invalid","first_name":"Deborah","last_name":"Msaidié","gender":"female","birth_date":"1991-12-05","country":"Comores","region":"Grande Comore","city":"Mitsamiouli","bio":"Douce mais déterminée, j'aime le sport, la lecture et les longues discussions. La prière rythme mes journées. J'attends un homme de foi, doux et responsable.","interests":["Cuisine","Lecture","Sport","Voyages"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.km.12@profils-virtuels.yona.invalid","first_name":"Youssouf","last_name":"Charif","gender":"male","birth_date":"1977-07-17","country":"Comores","region":"Anjouan","city":"Ouani","bio":"Calme et joyeux, je partage mon temps entre mon travail et les balades dans la nature. Je joue dans le groupe de louange de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Sport","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.km.13@profils-virtuels.yona.invalid","first_name":"Hadidja","last_name":"Youssouf","gender":"female","birth_date":"2000-09-08","country":"Comores","region":"Grande Comore","city":"Moroni","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au cinéma. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Cinéma","Bénévolat","Sport"],"denomination":"Protestante","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.km.14@profils-virtuels.yona.invalid","first_name":"Jean","last_name":"Toyb","gender":"male","birth_date":"2001-01-28","country":"Comores","region":"Anjouan","city":"Moutsamoudou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de balades dans la nature. La prière rythme mes journées. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Nature","Photographie"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.km.15@profils-virtuels.yona.invalid","first_name":"Rachel","last_name":"Attoumane","gender":"female","birth_date":"2001-04-09","country":"Comores","region":"Mohéli","city":"Fomboni","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le bénévolat. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Bénévolat"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.km.16@profils-virtuels.yona.invalid","first_name":"Nassur","last_name":"Soulé","gender":"male","birth_date":"1980-11-07","country":"Comores","region":"Anjouan","city":"Domoni","bio":"Calme et joyeux, je partage mon temps entre mon travail et les voyages. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Photographie","Voyages","Lecture"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.km.17@profils-virtuels.yona.invalid","first_name":"Faouzia","last_name":"Abdallah","gender":"female","birth_date":"2001-08-04","country":"Comores","region":"Grande Comore","city":"Mitsamiouli","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la lecture. Ma foi guide chacune de mes décisions. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Photographie","Voyages","Lecture"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.km.18@profils-virtuels.yona.invalid","first_name":"Mohamed","last_name":"Madi","gender":"male","birth_date":"1988-03-31","country":"Comores","region":"Anjouan","city":"Ouani","bio":"Fils de Dieu avant tout, je trouve ma joie dans le bénévolat et les voyages. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Voyages","Bénévolat"],"denomination":"Protestante","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.km.19@profils-virtuels.yona.invalid","first_name":"Echati","last_name":"Ali","gender":"female","birth_date":"2000-10-06","country":"Comores","region":"Grande Comore","city":"Moroni","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la danse. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Voyages","Danse","Louange","Photographie"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.km.20@profils-virtuels.yona.invalid","first_name":"Saïd","last_name":"Mzé","gender":"male","birth_date":"1982-01-15","country":"Comores","region":"Anjouan","city":"Moutsamoudou","bio":"Chaque journée est un cadeau de Dieu : je la remplis de mode et de voyages. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Sport","Voyages","Mode","Cuisine"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.km.21@profils-virtuels.yona.invalid","first_name":"Housna","last_name":"Djaffar","gender":"female","birth_date":"1990-06-25","country":"Comores","region":"Mohéli","city":"Fomboni","bio":"Fille de Dieu avant tout, je trouve ma joie dans le sport et le cinéma. Je chante dans la chorale de mon église. J'attends un homme de foi, doux et responsable.","interests":["Sport","Lecture","Cinéma"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.km.22@profils-virtuels.yona.invalid","first_name":"Samuel","last_name":"Ahamada","gender":"male","birth_date":"1997-08-03","country":"Comores","region":"Anjouan","city":"Domoni","bio":"Souriant et attentionné, j'aime les voyages et la musique. J'aide à l'organisation des sorties de l'église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Lecture","Musique"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.km.23@profils-virtuels.yona.invalid","first_name":"Ankili","last_name":"Oubeidillah","gender":"female","birth_date":"1980-12-20","country":"Comores","region":"Grande Comore","city":"Mitsamiouli","bio":"Souriante et attentionnée, j'aime le bénévolat et le cinéma. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Cinéma","Lecture"],"denomination":"Protestante","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.km.24@profils-virtuels.yona.invalid","first_name":"Ahmed","last_name":"Hassani","gender":"male","birth_date":"1977-05-06","country":"Comores","region":"Anjouan","city":"Ouani","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Bénévolat","Cinéma","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.km.25@profils-virtuels.yona.invalid","first_name":"Esther","last_name":"Hamada","gender":"female","birth_date":"1991-12-16","country":"Comores","region":"Grande Comore","city":"Moroni","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux voyages. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Louange","Voyages","Nature"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.mu.01@profils-virtuels.yona.invalid","first_name":"Karine","last_name":"Lebrasse","gender":"female","birth_date":"1987-08-08","country":"Maurice","region":"Port Louis","city":"Port Louis","bio":"Douce mais déterminée, j'aime la lecture, les voyages et les longues discussions. Je suis engagée dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Voyages","Sport"],"denomination":"Presbytérienne","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.mu.02@profils-virtuels.yona.invalid","first_name":"Ludovic","last_name":"Gentil","gender":"male","birth_date":"1997-10-26","country":"Maurice","region":"Plaines Wilhems","city":"Curepipe","bio":"Je suis un homme simple, passionné par la mode et les balades dans la nature. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Mode","Nature","Sport"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.mu.03@profils-virtuels.yona.invalid","first_name":"Nathalie","last_name":"Pillay","gender":"female","birth_date":"1992-12-22","country":"Maurice","region":"Plaines Wilhems","city":"Quatre Bornes","bio":"Fille de Dieu avant tout, je trouve ma joie dans la cuisine et la photographie. Je suis engagée dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Photographie","Cinéma","Voyages","Cuisine"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.mu.04@profils-virtuels.yona.invalid","first_name":"Jean-Michel","last_name":"Appadoo","gender":"male","birth_date":"1977-12-18","country":"Maurice","region":"Plaines Wilhems","city":"Vacoas","bio":"Souriant et attentionné, j'aime les balades dans la nature et les voyages. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Voyages","Mode"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.mu.05@profils-virtuels.yona.invalid","first_name":"Priya","last_name":"Duval","gender":"female","birth_date":"1986-07-13","country":"Maurice","region":"Grand Port","city":"Mahébourg","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la lecture. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Lecture"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.mu.06@profils-virtuels.yona.invalid","first_name":"Sébastien","last_name":"Jolicoeur","gender":"male","birth_date":"1988-10-29","country":"Maurice","region":"Plaines Wilhems","city":"Beau Bassin-Rose Hill","bio":"Je suis un homme simple, passionné par la musique et le sport. Je joue dans le groupe de louange de mon église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Louange","Sport","Musique"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.mu.07@profils-virtuels.yona.invalid","first_name":"Sandra","last_name":"Moothoo","gender":"female","birth_date":"2000-06-05","country":"Maurice","region":"Flacq","city":"Centre de Flacq","bio":"Fille de Dieu avant tout, je trouve ma joie dans le bénévolat et la cuisine. Je suis engagée dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Louange","Bénévolat","Cuisine"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.mu.08@profils-virtuels.yona.invalid","first_name":"Ravi","last_name":"Ramasawmy","gender":"male","birth_date":"1985-11-30","country":"Maurice","region":"Rivière du Rempart","city":"Goodlands","bio":"Je suis un homme simple, passionné par les balades dans la nature et la cuisine. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Cuisine","Mode","Nature"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.mu.09@profils-virtuels.yona.invalid","first_name":"Doris","last_name":"Ah-Yan","gender":"female","birth_date":"2000-04-27","country":"Maurice","region":"Pamplemousses","city":"Triolet","bio":"Chaque journée est un cadeau de Dieu : je la remplis de musique et de balades dans la nature. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Nature","Louange","Musique"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.mu.10@profils-virtuels.yona.invalid","first_name":"Kevin","last_name":"Rose","gender":"male","birth_date":"2002-08-15","country":"Maurice","region":"Port Louis","city":"Port Louis","bio":"Calme et joyeux, je partage mon temps entre mon travail et la louange. J'aide à l'organisation des sorties de l'église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Danse","Mode","Louange"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":33},
{"email":"virtuel.mu.11@profils-virtuels.yona.invalid","first_name":"Vanessa","last_name":"Li Kwong Ken","gender":"female","birth_date":"1999-01-02","country":"Maurice","region":"Plaines Wilhems","city":"Curepipe","bio":"Souriante et attentionnée, j'aime la photographie et la musique. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Photographie"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.mu.12@profils-virtuels.yona.invalid","first_name":"Nicolas","last_name":"Fanchette","gender":"male","birth_date":"2002-01-26","country":"Maurice","region":"Plaines Wilhems","city":"Quatre Bornes","bio":"Souriant et attentionné, j'aime le cinéma et la danse. Je suis engagé dans le groupe de jeunes de ma paroisse. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Danse","Cinéma","Sport"],"denomination":"Assemblées de Dieu","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":33},
{"email":"virtuel.mu.13@profils-virtuels.yona.invalid","first_name":"Laëtitia","last_name":"Henri","gender":"female","birth_date":"1990-11-03","country":"Maurice","region":"Plaines Wilhems","city":"Vacoas","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le sport. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Nature","Photographie","Louange","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.mu.14@profils-virtuels.yona.invalid","first_name":"Patrick","last_name":"Laval","gender":"male","birth_date":"1979-08-04","country":"Maurice","region":"Grand Port","city":"Mahébourg","bio":"Posé mais déterminé, j'aime le bénévolat, la photographie et les longues discussions. Je suis engagé dans le groupe de jeunes de ma paroisse. Je crois au mariage, à la fidélité et au respect.","interests":["Lecture","Bénévolat","Cuisine","Photographie"],"denomination":"Presbytérienne","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.mu.15@profils-virtuels.yona.invalid","first_name":"Stéphanie","last_name":"Mamet","gender":"female","birth_date":"1987-02-22","country":"Maurice","region":"Plaines Wilhems","city":"Beau Bassin-Rose Hill","bio":"Souriante et attentionnée, j'aime la danse et les voyages. Ma foi guide chacune de mes décisions. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Voyages","Louange","Cuisine","Danse"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.mu.16@profils-virtuels.yona.invalid","first_name":"Yannick","last_name":"Bégué","gender":"male","birth_date":"1991-12-04","country":"Maurice","region":"Flacq","city":"Centre de Flacq","bio":"Calme et joyeux, je partage mon temps entre mon travail et le sport. J'aide à l'organisation des sorties de l'église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Mode","Photographie","Sport"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.mu.17@profils-virtuels.yona.invalid","first_name":"Julie","last_name":"Desveaux","gender":"female","birth_date":"1978-03-27","country":"Maurice","region":"Rivière du Rempart","city":"Goodlands","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la lecture. Ma foi guide chacune de mes décisions. J'attends un homme de foi, doux et responsable.","interests":["Nature","Lecture"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.mu.18@profils-virtuels.yona.invalid","first_name":"Damien","last_name":"Louis","gender":"male","birth_date":"1986-03-03","country":"Maurice","region":"Pamplemousses","city":"Triolet","bio":"Je suis un homme simple, passionné par la louange et le bénévolat. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Bénévolat","Louange"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":31,"max_age":49},
{"email":"virtuel.mu.19@profils-virtuels.yona.invalid","first_name":"Emilie","last_name":"Sauzier","gender":"female","birth_date":"1980-04-12","country":"Maurice","region":"Port Louis","city":"Port Louis","bio":"Douce mais déterminée, j'aime le cinéma, les voyages et les longues discussions. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Voyages"],"denomination":"Presbytérienne","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.mu.20@profils-virtuels.yona.invalid","first_name":"Laurent","last_name":"Perrine","gender":"male","birth_date":"2003-10-12","country":"Maurice","region":"Plaines Wilhems","city":"Curepipe","bio":"Calme et joyeux, je partage mon temps entre mon travail et les voyages. La prière rythme mes journées. J'attends une femme de foi, douce et pleine de joie.","interests":["Lecture","Voyages","Nature"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.mu.21@profils-virtuels.yona.invalid","first_name":"Cindy","last_name":"Lebrasse","gender":"female","birth_date":"1978-07-01","country":"Maurice","region":"Plaines Wilhems","city":"Quatre Bornes","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les balades dans la nature. Je chante dans la chorale de mon église. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Nature","Photographie","Cuisine"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.mu.22@profils-virtuels.yona.invalid","first_name":"Olivier","last_name":"Gentil","gender":"male","birth_date":"1995-07-05","country":"Maurice","region":"Plaines Wilhems","city":"Vacoas","bio":"Souriant et attentionné, j'aime le sport et la mode. J'aide à l'organisation des sorties de l'église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Mode","Cuisine","Danse","Sport"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.mu.23@profils-virtuels.yona.invalid","first_name":"Jessica","last_name":"Pillay","gender":"female","birth_date":"1978-08-11","country":"Maurice","region":"Grand Port","city":"Mahébourg","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la lecture. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Danse","Lecture"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.mu.24@profils-virtuels.yona.invalid","first_name":"Fabrice","last_name":"Appadoo","gender":"male","birth_date":"1977-06-03","country":"Maurice","region":"Plaines Wilhems","city":"Beau Bassin-Rose Hill","bio":"Calme et joyeux, je partage mon temps entre mon travail et les voyages. J'aime méditer la Parole chaque matin. J'attends une femme de foi, douce et pleine de joie.","interests":["Mode","Photographie","Danse","Voyages"],"denomination":"Assemblées de Dieu","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.mu.25@profils-virtuels.yona.invalid","first_name":"Gaëlle","last_name":"Duval","gender":"female","birth_date":"1993-03-12","country":"Maurice","region":"Flacq","city":"Centre de Flacq","bio":"Souriante et attentionnée, j'aime le bénévolat et la cuisine. J'enseigne à l'école du dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Cuisine","Photographie"],"denomination":"Assemblées de Dieu","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.sc.01@profils-virtuels.yona.invalid","first_name":"Cindy","last_name":"Larue","gender":"female","birth_date":"1982-02-09","country":"Seychelles","region":"La Rivière Anglaise","city":"Victoria","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de balades dans la nature. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Lecture"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.sc.02@profils-virtuels.yona.invalid","first_name":"Joachim","last_name":"Vidot","gender":"male","birth_date":"1987-12-11","country":"Seychelles","region":"Anse Boileau","city":"Anse Boileau","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. Je joue dans le groupe de louange de mon église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Sport"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":30,"max_age":48},
{"email":"virtuel.sc.03@profils-virtuels.yona.invalid","first_name":"Annette","last_name":"Savy","gender":"female","birth_date":"1982-08-11","country":"Seychelles","region":"Beau Vallon","city":"Beau Vallon","bio":"Souriante et attentionnée, j'aime la photographie et la mode. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Mode","Photographie","Musique"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.sc.04@profils-virtuels.yona.invalid","first_name":"Bernard","last_name":"Hoareau","gender":"male","birth_date":"1992-05-10","country":"Seychelles","region":"Takamaka","city":"Takamaka","bio":"Je suis un homme simple, passionné par la photographie et la cuisine. La prière rythme mes journées. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Photographie","Cuisine"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.sc.05@profils-virtuels.yona.invalid","first_name":"Linda","last_name":"Sinon","gender":"female","birth_date":"1989-09-14","country":"Seychelles","region":"Cascade","city":"Cascade","bio":"Je suis une femme simple, passionnée par la louange et la mode. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Louange","Mode","Nature"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.sc.06@profils-virtuels.yona.invalid","first_name":"Jean-Paul","last_name":"Barbé","gender":"male","birth_date":"1997-09-11","country":"Seychelles","region":"Bel Ombre","city":"Bel Ombre","bio":"Je suis un homme simple, passionné par les voyages et la louange. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Photographie","Louange","Voyages"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.sc.07@profils-virtuels.yona.invalid","first_name":"Sheryl","last_name":"Mondon","gender":"female","birth_date":"2001-01-05","country":"Seychelles","region":"Anse Royale","city":"Anse Royale","bio":"Chaque journée est un cadeau de Dieu : je la remplis de musique et de danse. J'enseigne à l'école du dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Cuisine","Mode","Musique"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.sc.08@profils-virtuels.yona.invalid","first_name":"Wavel","last_name":"Esparon","gender":"male","birth_date":"1985-11-27","country":"Seychelles","region":"Baie Lazare","city":"Baie Lazare","bio":"Fils de Dieu avant tout, je trouve ma joie dans la mode et la photographie. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Mode","Photographie"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.sc.09@profils-virtuels.yona.invalid","first_name":"Vivianne","last_name":"Payet","gender":"female","birth_date":"1979-12-01","country":"Seychelles","region":"La Rivière Anglaise","city":"Victoria","bio":"Je suis une femme simple, passionnée par le bénévolat et la cuisine. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cuisine","Bénévolat"],"denomination":"Pentecôtiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.sc.10@profils-virtuels.yona.invalid","first_name":"Ralph","last_name":"Confait","gender":"male","birth_date":"1980-01-03","country":"Seychelles","region":"Anse Boileau","city":"Anse Boileau","bio":"Souriant et attentionné, j'aime les voyages et la danse. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Voyages","Cinéma","Danse","Nature"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.sc.11@profils-virtuels.yona.invalid","first_name":"Josiane","last_name":"Rose","gender":"female","birth_date":"1980-12-08","country":"Seychelles","region":"Beau Vallon","city":"Beau Vallon","bio":"Je suis une femme simple, passionnée par le cinéma et la louange. Je chante dans la chorale de mon église. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Louange"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.sc.12@profils-virtuels.yona.invalid","first_name":"Daniel","last_name":"Faure","gender":"male","birth_date":"1981-09-07","country":"Seychelles","region":"Takamaka","city":"Takamaka","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la musique. Le Psaume 23 m'accompagne depuis toujours. J'attends une femme de foi, douce et pleine de joie.","interests":["Cuisine","Musique","Cinéma","Mode"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.sc.13@profils-virtuels.yona.invalid","first_name":"Amanda","last_name":"Laporte","gender":"female","birth_date":"2000-03-25","country":"Seychelles","region":"Cascade","city":"Cascade","bio":"Fille de Dieu avant tout, je trouve ma joie dans la musique et la mode. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Mode","Musique"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.sc.14@profils-virtuels.yona.invalid","first_name":"Dereck","last_name":"Dogley","gender":"male","birth_date":"1998-07-18","country":"Seychelles","region":"Bel Ombre","city":"Bel Ombre","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la musique. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Mode","Cuisine","Musique","Voyages"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.sc.15@profils-virtuels.yona.invalid","first_name":"Marie-Ange","last_name":"Labrosse","gender":"female","birth_date":"2002-11-15","country":"Seychelles","region":"Anse Royale","city":"Anse Royale","bio":"Douce mais déterminée, j'aime la musique, la photographie et les longues discussions. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Musique","Photographie"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.sc.16@profils-virtuels.yona.invalid","first_name":"Alex","last_name":"Pillay","gender":"male","birth_date":"1981-09-02","country":"Seychelles","region":"Baie Lazare","city":"Baie Lazare","bio":"Fils de Dieu avant tout, je trouve ma joie dans le sport et la louange. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Sport","Bénévolat","Louange","Mode"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.sc.17@profils-virtuels.yona.invalid","first_name":"Daniella","last_name":"Michel","gender":"female","birth_date":"1999-11-05","country":"Seychelles","region":"La Rivière Anglaise","city":"Victoria","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Nature","Danse","Louange"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.sc.18@profils-virtuels.yona.invalid","first_name":"Terry","last_name":"Uranie","gender":"male","birth_date":"1998-06-02","country":"Seychelles","region":"Anse Boileau","city":"Anse Boileau","bio":"Souriant et attentionné, j'aime la louange et la musique. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Musique","Nature","Louange"],"denomination":"Pentecôtiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.sc.19@profils-virtuels.yona.invalid","first_name":"Natasha","last_name":"Quatre","gender":"female","birth_date":"1994-09-01","country":"Seychelles","region":"Beau Vallon","city":"Beau Vallon","bio":"Fille de Dieu avant tout, je trouve ma joie dans le cinéma et la lecture. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Cinéma","Bénévolat","Photographie"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.sc.20@profils-virtuels.yona.invalid","first_name":"Marcel","last_name":"Albert","gender":"male","birth_date":"1985-02-13","country":"Seychelles","region":"Takamaka","city":"Takamaka","bio":"Souriant et attentionné, j'aime la danse et la lecture. La prière rythme mes journées. J'attends une femme de foi, douce et pleine de joie.","interests":["Mode","Danse","Lecture","Photographie"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.sc.21@profils-virtuels.yona.invalid","first_name":"Elsie","last_name":"Larue","gender":"female","birth_date":"1996-06-26","country":"Seychelles","region":"Cascade","city":"Cascade","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Louange","Mode","Sport"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.sc.22@profils-virtuels.yona.invalid","first_name":"Clifford","last_name":"Vidot","gender":"male","birth_date":"1991-11-11","country":"Seychelles","region":"Bel Ombre","city":"Bel Ombre","bio":"Calme et joyeux, je partage mon temps entre mon travail et la musique. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Musique","Sport"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.sc.23@profils-virtuels.yona.invalid","first_name":"Bernadette","last_name":"Savy","gender":"female","birth_date":"2001-08-01","country":"Seychelles","region":"Anse Royale","city":"Anse Royale","bio":"Souriante et attentionnée, j'aime le bénévolat et la danse. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Sport","Danse","Bénévolat"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.sc.24@profils-virtuels.yona.invalid","first_name":"Ronny","last_name":"Hoareau","gender":"male","birth_date":"1978-06-14","country":"Seychelles","region":"Baie Lazare","city":"Baie Lazare","bio":"Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de cuisine. La prière rythme mes journées. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Cuisine","Musique"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.sc.25@profils-virtuels.yona.invalid","first_name":"Fiona","last_name":"Sinon","gender":"female","birth_date":"1986-09-10","country":"Seychelles","region":"La Rivière Anglaise","city":"Victoria","bio":"Fille de Dieu avant tout, je trouve ma joie dans le cinéma et la mode. La prière rythme mes journées. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Lecture","Cinéma","Mode"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":31,"max_age":49}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
