-- ============================================================
-- YONA — profils virtuels : fichier 9 sur 10
-- 75 profils : Maroc, Algérie, Tunisie.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.ma.01@profils-virtuels.yona.invalid","first_name":"Samira","last_name":"Fassi Fihri","gender":"female","birth_date":"2001-04-19","country":"Maroc","region":"Casablanca-Settat","city":"Casablanca","bio":"Je suis une femme simple, passionnée par le cinéma et la danse. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Danse","Cinéma","Lecture"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":34},
{"email":"virtuel.ma.02@profils-virtuels.yona.invalid","first_name":"Rachid","last_name":"Alaoui","gender":"male","birth_date":"1992-02-21","country":"Maroc","region":"Rabat-Salé-Kénitra","city":"Rabat","bio":"Calme et joyeux, je partage mon temps entre mon travail et la mode. Je suis engagé dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Musique","Mode"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.ma.03@profils-virtuels.yona.invalid","first_name":"Leïla","last_name":"El Idrissi","gender":"female","birth_date":"1987-09-17","country":"Maroc","region":"Marrakesh-Safi","city":"Marrakesh","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux balades dans la nature. Je chante dans la chorale de mon église. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Sport","Photographie"],"denomination":"Protestante (EEAM)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.ma.04@profils-virtuels.yona.invalid","first_name":"David","last_name":"Kettani","gender":"male","birth_date":"1984-11-23","country":"Maroc","region":"Fes-Meknes","city":"Fes","bio":"Je suis un homme simple, passionné par la lecture et le sport. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Lecture","Cinéma","Sport","Louange"],"denomination":"Protestante (EEAM)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.ma.05@profils-virtuels.yona.invalid","first_name":"Hanane","last_name":"Zniber","gender":"female","birth_date":"1985-03-05","country":"Maroc","region":"Tanger-Tetouan-Al Hoceima","city":"Tangier","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Musique","Sport","Cinéma"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.ma.06@profils-virtuels.yona.invalid","first_name":"Yassine","last_name":"Benjelloun","gender":"male","birth_date":"1985-10-02","country":"Maroc","region":"Souss-Massa","city":"Agadir","bio":"Fils de Dieu avant tout, je trouve ma joie dans la cuisine et les balades dans la nature. Je joue dans le groupe de louange de mon église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Cuisine","Louange","Nature","Sport"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":32,"max_age":50},
{"email":"virtuel.ma.07@profils-virtuels.yona.invalid","first_name":"Meryem","last_name":"Mansouri","gender":"female","birth_date":"2002-07-17","country":"Maroc","region":"Fes-Meknes","city":"Meknes","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Bénévolat","Nature"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.ma.08@profils-virtuels.yona.invalid","first_name":"Mehdi","last_name":"Haddad","gender":"male","birth_date":"1994-01-03","country":"Maroc","region":"Oriental","city":"Oujda","bio":"Calme et joyeux, je partage mon temps entre mon travail et la louange. Je suis engagé dans le groupe de jeunes de ma paroisse. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Danse","Cinéma","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.ma.09@profils-virtuels.yona.invalid","first_name":"Imane","last_name":"Berrada","gender":"female","birth_date":"1995-01-09","country":"Maroc","region":"Rabat-Salé-Kénitra","city":"Kenitra","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Cinéma","Mode","Sport","Musique"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.ma.10@profils-virtuels.yona.invalid","first_name":"Elias","last_name":"Belkadi","gender":"male","birth_date":"1996-05-06","country":"Maroc","region":"Tanger-Tetouan-Al Hoceima","city":"Tétouan","bio":"Je suis un homme simple, passionné par le bénévolat et le cinéma. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Cinéma","Bénévolat","Photographie"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.ma.11@profils-virtuels.yona.invalid","first_name":"Malika","last_name":"Amrani","gender":"female","birth_date":"1989-05-23","country":"Maroc","region":"Casablanca-Settat","city":"El Jadida","bio":"Souriante et attentionnée, j'aime la mode et les balades dans la nature. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Nature","Mode","Sport"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.ma.12@profils-virtuels.yona.invalid","first_name":"Ismaël","last_name":"Cherkaoui","gender":"male","birth_date":"1989-01-23","country":"Maroc","region":"Casablanca-Settat","city":"Mohammedia","bio":"Je suis un homme simple, passionné par la lecture et la danse. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Photographie","Cuisine","Danse"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.ma.13@profils-virtuels.yona.invalid","first_name":"Souad","last_name":"Sebti","gender":"female","birth_date":"1990-06-15","country":"Maroc","region":"Casablanca-Settat","city":"Casablanca","bio":"Chaque journée est un cadeau de Dieu : je la remplis de voyages et de mode. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Voyages","Mode","Lecture"],"denomination":"Protestante (EEAM)","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.ma.14@profils-virtuels.yona.invalid","first_name":"Jamal","last_name":"Chraibi","gender":"male","birth_date":"1997-08-30","country":"Maroc","region":"Rabat-Salé-Kénitra","city":"Rabat","bio":"Fils de Dieu avant tout, je trouve ma joie dans les voyages et la danse. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Danse"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.ma.15@profils-virtuels.yona.invalid","first_name":"Kenza","last_name":"Bennani","gender":"female","birth_date":"1990-08-24","country":"Maroc","region":"Marrakesh-Safi","city":"Marrakesh","bio":"Fille de Dieu avant tout, je trouve ma joie dans la musique et la photographie. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Musique"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.ma.16@profils-virtuels.yona.invalid","first_name":"Anas","last_name":"El Fassi","gender":"male","birth_date":"1978-04-22","country":"Maroc","region":"Fes-Meknes","city":"Fes","bio":"Souriant et attentionné, j'aime les balades dans la nature et le cinéma. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Cinéma","Nature","Cuisine"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.ma.17@profils-virtuels.yona.invalid","first_name":"Nadia","last_name":"Benali","gender":"female","birth_date":"1993-08-26","country":"Maroc","region":"Tanger-Tetouan-Al Hoceima","city":"Tangier","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. La prière rythme mes journées. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Lecture"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.ma.18@profils-virtuels.yona.invalid","first_name":"Youssef","last_name":"Lahlou","gender":"male","birth_date":"1997-02-24","country":"Maroc","region":"Souss-Massa","city":"Agadir","bio":"Fils de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la photographie. Je suis engagé dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Photographie","Nature"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.ma.19@profils-virtuels.yona.invalid","first_name":"Yasmina","last_name":"Ouazzani","gender":"female","birth_date":"1984-01-07","country":"Maroc","region":"Fes-Meknes","city":"Meknes","bio":"Fille de Dieu avant tout, je trouve ma joie dans la danse et le bénévolat. Je suis engagée dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Photographie","Danse"],"denomination":"Protestante (EEAM)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.ma.20@profils-virtuels.yona.invalid","first_name":"Adam","last_name":"Tazi","gender":"male","birth_date":"1991-06-21","country":"Maroc","region":"Oriental","city":"Oujda","bio":"Souriant et attentionné, j'aime la musique et le cinéma. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Musique","Cinéma","Sport"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.ma.21@profils-virtuels.yona.invalid","first_name":"Amal","last_name":"Fassi Fihri","gender":"female","birth_date":"1977-06-19","country":"Maroc","region":"Rabat-Salé-Kénitra","city":"Kenitra","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de cuisine. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Photographie","Cuisine","Lecture"],"denomination":"Protestante (EEAM)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.ma.22@profils-virtuels.yona.invalid","first_name":"Karim","last_name":"Alaoui","gender":"male","birth_date":"1991-06-09","country":"Maroc","region":"Tanger-Tetouan-Al Hoceima","city":"Tétouan","bio":"Souriant et attentionné, j'aime la danse et la mode. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Musique","Mode"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.ma.23@profils-virtuels.yona.invalid","first_name":"Siham","last_name":"El Idrissi","gender":"female","birth_date":"1982-12-26","country":"Maroc","region":"Casablanca-Settat","city":"El Jadida","bio":"Douce mais déterminée, j'aime la danse, le bénévolat et les longues discussions. La prière rythme mes journées. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Danse","Cuisine"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.ma.24@profils-virtuels.yona.invalid","first_name":"Hicham","last_name":"Kettani","gender":"male","birth_date":"1978-08-17","country":"Maroc","region":"Casablanca-Settat","city":"Mohammedia","bio":"Calme et joyeux, je partage mon temps entre mon travail et la musique. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Musique","Mode"],"denomination":"Protestante (EEAM)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.ma.25@profils-virtuels.yona.invalid","first_name":"Sara","last_name":"Zniber","gender":"female","birth_date":"1983-06-08","country":"Maroc","region":"Casablanca-Settat","city":"Casablanca","bio":"Chaque journée est un cadeau de Dieu : je la remplis de danse et de voyages. Je suis engagée dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Danse","Voyages"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":34,"max_age":52},
{"email":"virtuel.dz.01@profils-virtuels.yona.invalid","first_name":"Nadia","last_name":"Mebarki","gender":"female","birth_date":"1979-07-28","country":"Algérie","region":"Algiers","city":"Algiers","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de danse. Je suis engagée dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Danse"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.dz.02@profils-virtuels.yona.invalid","first_name":"Youcef","last_name":"Meziane","gender":"male","birth_date":"1984-07-07","country":"Algérie","region":"Oran","city":"Oran","bio":"Fils de Dieu avant tout, je trouve ma joie dans la cuisine et la lecture. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Lecture","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.dz.03@profils-virtuels.yona.invalid","first_name":"Tinhinane","last_name":"Ouali","gender":"female","birth_date":"1987-11-29","country":"Algérie","region":"Constantine","city":"Constantine","bio":"Fille de Dieu avant tout, je trouve ma joie dans le bénévolat et les balades dans la nature. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Photographie","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.dz.04@profils-virtuels.yona.invalid","first_name":"Amine","last_name":"Kaci","gender":"male","birth_date":"1980-07-23","country":"Algérie","region":"Annaba","city":"Annaba","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de lecture. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Photographie","Cinéma","Louange"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.dz.05@profils-virtuels.yona.invalid","first_name":"Lynda","last_name":"Rahmani","gender":"female","birth_date":"1993-03-04","country":"Algérie","region":"Tizi Ouzou","city":"Tizi Ouzou","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Louange","Sport","Cinéma"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.dz.06@profils-virtuels.yona.invalid","first_name":"Nassim","last_name":"Chaouch","gender":"male","birth_date":"1989-11-07","country":"Algérie","region":"Béjaïa","city":"Béjaïa","bio":"Calme et joyeux, je partage mon temps entre mon travail et le bénévolat. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Danse","Voyages","Bénévolat","Louange"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.dz.07@profils-virtuels.yona.invalid","first_name":"Dihia","last_name":"Slimani","gender":"female","birth_date":"1987-12-21","country":"Algérie","region":"Sétif","city":"Sétif","bio":"Chaque journée est un cadeau de Dieu : je la remplis de louange et de lecture. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.","interests":["Louange","Lecture"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.dz.08@profils-virtuels.yona.invalid","first_name":"Mourad","last_name":"Hamidi","gender":"male","birth_date":"2002-04-11","country":"Algérie","region":"Blida","city":"Blida","bio":"Posé mais déterminé, j'aime la cuisine, le sport et les longues discussions. Je joue dans le groupe de louange de mon église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Cinéma","Cuisine"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":33},
{"email":"virtuel.dz.09@profils-virtuels.yona.invalid","first_name":"Lamia","last_name":"Lounès","gender":"female","birth_date":"1984-03-30","country":"Algérie","region":"Batna","city":"Batna","bio":"Je suis une femme simple, passionnée par la danse et le bénévolat. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Danse","Cinéma","Cuisine","Bénévolat"],"denomination":"Protestante (EPA)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.dz.10@profils-virtuels.yona.invalid","first_name":"Karim","last_name":"Aït Ahmed","gender":"male","birth_date":"1990-03-29","country":"Algérie","region":"Tlemcen","city":"Tlemcen","bio":"Souriant et attentionné, j'aime le sport et la louange. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Sport","Louange"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":27,"max_age":45},
{"email":"virtuel.dz.11@profils-virtuels.yona.invalid","first_name":"Karima","last_name":"Benali","gender":"female","birth_date":"1990-03-09","country":"Algérie","region":"Bouira","city":"Bouïra","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la cuisine. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Cuisine","Musique","Sport"],"denomination":"Protestante (EPA)","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.dz.12@profils-virtuels.yona.invalid","first_name":"Massinissa","last_name":"Amrani","gender":"male","birth_date":"1984-03-18","country":"Algérie","region":"Algiers","city":"Algiers","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de voyages. J'aime méditer la Parole chaque matin. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Lecture","Mode","Nature","Voyages"],"denomination":"Protestante (EPA)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.dz.13@profils-virtuels.yona.invalid","first_name":"Sonia","last_name":"Djebbar","gender":"female","birth_date":"1991-12-19","country":"Algérie","region":"Oran","city":"Oran","bio":"Douce mais déterminée, j'aime la musique, la mode et les longues discussions. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Musique","Danse","Mode"],"denomination":"Protestante (EPA)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":26,"max_age":44},
{"email":"virtuel.dz.14@profils-virtuels.yona.invalid","first_name":"Yacine","last_name":"Khelifi","gender":"male","birth_date":"1979-08-03","country":"Algérie","region":"Constantine","city":"Constantine","bio":"Fils de Dieu avant tout, je trouve ma joie dans le bénévolat et la photographie. Je joue dans le groupe de louange de mon église. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Voyages","Bénévolat","Nature"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.dz.15@profils-virtuels.yona.invalid","first_name":"Nawel","last_name":"Taleb","gender":"female","birth_date":"1987-12-05","country":"Algérie","region":"Annaba","city":"Annaba","bio":"Je suis une femme simple, passionnée par les balades dans la nature et la danse. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Danse","Nature"],"denomination":"Protestante (EPA)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.dz.16@profils-virtuels.yona.invalid","first_name":"Farid","last_name":"Belkacem","gender":"male","birth_date":"1989-03-07","country":"Algérie","region":"Tizi Ouzou","city":"Tizi Ouzou","bio":"Posé mais déterminé, j'aime le sport, les balades dans la nature et les longues discussions. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Danse","Cuisine","Sport","Nature"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.dz.17@profils-virtuels.yona.invalid","first_name":"Fatiha","last_name":"Saadi","gender":"female","birth_date":"1978-08-26","country":"Algérie","region":"Béjaïa","city":"Béjaïa","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. J'enseigne à l'école du dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Nature","Sport"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.dz.18@profils-virtuels.yona.invalid","first_name":"Samir","last_name":"Bouzid","gender":"male","birth_date":"2003-06-05","country":"Algérie","region":"Sétif","city":"Sétif","bio":"Calme et joyeux, je partage mon temps entre mon travail et la louange. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Louange","Cinéma"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.dz.19@profils-virtuels.yona.invalid","first_name":"Sabrina","last_name":"Haddad","gender":"female","birth_date":"1984-09-12","country":"Algérie","region":"Blida","city":"Blida","bio":"Douce mais déterminée, j'aime la musique, la mode et les longues discussions. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Mode","Musique"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":33,"max_age":51},
{"email":"virtuel.dz.20@profils-virtuels.yona.invalid","first_name":"Lyes","last_name":"Zerrouki","gender":"male","birth_date":"1995-01-02","country":"Algérie","region":"Batna","city":"Batna","bio":"Chaque journée est un cadeau de Dieu : je la remplis de balades dans la nature et de sport. J'aide à l'organisation des sorties de l'église. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Voyages","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.dz.21@profils-virtuels.yona.invalid","first_name":"Yasmine","last_name":"Mebarki","gender":"female","birth_date":"2000-02-02","country":"Algérie","region":"Tlemcen","city":"Tlemcen","bio":"Douce mais déterminée, j'aime les voyages, la lecture et les longues discussions. J'enseigne à l'école du dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Voyages","Bénévolat","Lecture"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.dz.22@profils-virtuels.yona.invalid","first_name":"Hakim","last_name":"Meziane","gender":"male","birth_date":"1977-01-23","country":"Algérie","region":"Bouira","city":"Bouïra","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux voyages. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Mode","Voyages","Musique"],"denomination":"Protestante (EPA)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":40,"max_age":58},
{"email":"virtuel.dz.23@profils-virtuels.yona.invalid","first_name":"Katia","last_name":"Ouali","gender":"female","birth_date":"1982-09-27","country":"Algérie","region":"Algiers","city":"Algiers","bio":"Douce mais déterminée, j'aime la louange, la lecture et les longues discussions. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.dz.24@profils-virtuels.yona.invalid","first_name":"Rafik","last_name":"Kaci","gender":"male","birth_date":"2002-09-15","country":"Algérie","region":"Oran","city":"Oran","bio":"Je suis un homme simple, passionné par les voyages et le bénévolat. Ma foi guide chacune de mes décisions. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Bénévolat","Voyages"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":33},
{"email":"virtuel.dz.25@profils-virtuels.yona.invalid","first_name":"Meriem","last_name":"Rahmani","gender":"female","birth_date":"1987-05-17","country":"Algérie","region":"Constantine","city":"Constantine","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la photographie. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Louange","Photographie"],"denomination":"Protestante (EPA)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.tn.01@profils-virtuels.yona.invalid","first_name":"Leïla","last_name":"Nasri","gender":"female","birth_date":"1999-11-06","country":"Tunisie","region":"Tunis Governorate","city":"Tunis","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de voyages. Ma foi guide chacune de mes décisions. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Voyages","Cinéma"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.tn.02@profils-virtuels.yona.invalid","first_name":"Sami","last_name":"Bouazizi","gender":"male","birth_date":"1991-12-09","country":"Tunisie","region":"Sfax Governorate","city":"Sfax","bio":"Souriant et attentionné, j'aime la musique et le sport. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Musique","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.tn.03@profils-virtuels.yona.invalid","first_name":"Emna","last_name":"Gharbi","gender":"female","birth_date":"2002-09-05","country":"Tunisie","region":"Sousse Governorate","city":"Sousse","bio":"Souriante et attentionnée, j'aime la lecture et le bénévolat. Je sers à l'accueil de mon église le dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Bénévolat","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":33},
{"email":"virtuel.tn.04@profils-virtuels.yona.invalid","first_name":"Skander","last_name":"Jaziri","gender":"male","birth_date":"1980-03-17","country":"Tunisie","region":"Bizerte Governorate","city":"Bizerte","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la cuisine. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Cuisine","Danse","Musique","Nature"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.tn.05@profils-virtuels.yona.invalid","first_name":"Rim","last_name":"Jebali","gender":"female","birth_date":"1994-10-21","country":"Tunisie","region":"Nabeul Governorate","city":"Nabeul","bio":"Douce mais déterminée, j'aime le sport, le bénévolat et les longues discussions. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Bénévolat","Sport"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.tn.06@profils-virtuels.yona.invalid","first_name":"Anis","last_name":"Trabelsi","gender":"male","birth_date":"1997-05-28","country":"Tunisie","region":"Monastir Governorate","city":"Monastir","bio":"Fils de Dieu avant tout, je trouve ma joie dans le bénévolat et la musique. J'aime méditer la Parole chaque matin. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Cuisine","Musique","Bénévolat","Lecture"],"denomination":"Protestante (Église réformée)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.tn.07@profils-virtuels.yona.invalid","first_name":"Nour","last_name":"Ayari","gender":"female","birth_date":"1981-10-24","country":"Tunisie","region":"Nabeul Governorate","city":"Hammamet","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de musique. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Cuisine","Louange","Musique","Photographie"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":36,"max_age":54},
{"email":"virtuel.tn.08@profils-virtuels.yona.invalid","first_name":"Mehdi","last_name":"Karoui","gender":"male","birth_date":"1989-11-11","country":"Tunisie","region":"Tunis Governorate","city":"La Marsa","bio":"Je suis un homme simple, passionné par la musique et la lecture. Je sers à l'accueil de mon église le dimanche. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Louange","Cuisine","Lecture"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.tn.09@profils-virtuels.yona.invalid","first_name":"Ines","last_name":"Dridi","gender":"female","birth_date":"1995-08-20","country":"Tunisie","region":"Kairouan","city":"Kairouan","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de balades dans la nature. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.","interests":["Nature","Musique","Lecture"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.tn.10@profils-virtuels.yona.invalid","first_name":"Bilel","last_name":"Ben Ali","gender":"male","birth_date":"1979-09-22","country":"Tunisie","region":"Gabès Governorate","city":"Gabès","bio":"Je suis un homme simple, passionné par les voyages et la photographie. Je sers à l'accueil de mon église le dimanche. J'attends une femme de foi, douce et pleine de joie.","interests":["Voyages","Photographie"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":38,"max_age":56},
{"email":"virtuel.tn.11@profils-virtuels.yona.invalid","first_name":"Sana","last_name":"Sassi","gender":"female","birth_date":"1993-11-24","country":"Tunisie","region":"Tunis Governorate","city":"Tunis","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de voyages. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Voyages","Cuisine","Musique"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.tn.12@profils-virtuels.yona.invalid","first_name":"Nizar","last_name":"Ben Ammar","gender":"male","birth_date":"1978-12-04","country":"Tunisie","region":"Sfax Governorate","city":"Sfax","bio":"Posé mais déterminé, j'aime les balades dans la nature, la louange et les longues discussions. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Louange","Nature","Mode"],"denomination":"Protestante (Église réformée)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.tn.13@profils-virtuels.yona.invalid","first_name":"Olfa","last_name":"Mejri","gender":"female","birth_date":"1990-12-12","country":"Tunisie","region":"Sousse Governorate","city":"Sousse","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Bénévolat","Lecture","Voyages","Danse"],"denomination":"Protestante (Église réformée)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.tn.14@profils-virtuels.yona.invalid","first_name":"Hatem","last_name":"Zaouali","gender":"male","birth_date":"1978-03-03","country":"Tunisie","region":"Bizerte Governorate","city":"Bizerte","bio":"Fils de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la photographie. Ma foi guide chacune de mes décisions. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Nature","Photographie"],"denomination":"Protestante (Église réformée)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.tn.15@profils-virtuels.yona.invalid","first_name":"Sarra","last_name":"Chaabane","gender":"female","birth_date":"1998-10-25","country":"Tunisie","region":"Nabeul Governorate","city":"Nabeul","bio":"Chaque journée est un cadeau de Dieu : je la remplis de danse et de mode. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Nature","Cinéma","Mode","Danse"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.tn.16@profils-virtuels.yona.invalid","first_name":"Yassine","last_name":"Ben Salem","gender":"male","birth_date":"1981-05-12","country":"Tunisie","region":"Monastir Governorate","city":"Monastir","bio":"Posé mais déterminé, j'aime la lecture, la photographie et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Lecture","Photographie"],"denomination":"Protestante (Église réformée)","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.tn.17@profils-virtuels.yona.invalid","first_name":"Wafa","last_name":"Khemiri","gender":"female","birth_date":"1979-10-10","country":"Tunisie","region":"Nabeul Governorate","city":"Hammamet","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la musique. La prière rythme mes journées. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Musique","Nature"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.tn.18@profils-virtuels.yona.invalid","first_name":"Amine","last_name":"Mabrouk","gender":"male","birth_date":"1986-06-04","country":"Tunisie","region":"Tunis Governorate","city":"La Marsa","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. Le Psaume 23 m'accompagne depuis toujours. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Sport"],"denomination":"Protestante (Église réformée)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":31,"max_age":49},
{"email":"virtuel.tn.19@profils-virtuels.yona.invalid","first_name":"Mariem","last_name":"Saidi","gender":"female","birth_date":"1985-11-19","country":"Tunisie","region":"Kairouan","city":"Kairouan","bio":"Chaque journée est un cadeau de Dieu : je la remplis de photographie et de cinéma. Je chante dans la chorale de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Louange","Voyages","Photographie","Cinéma"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.tn.20@profils-virtuels.yona.invalid","first_name":"Rami","last_name":"Hammami","gender":"male","birth_date":"1998-04-24","country":"Tunisie","region":"Gabès Governorate","city":"Gabès","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. Je joue dans le groupe de louange de mon église. J'attends une femme de foi, douce et pleine de joie.","interests":["Bénévolat","Photographie","Sport"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.tn.21@profils-virtuels.yona.invalid","first_name":"Asma","last_name":"Nasri","gender":"female","birth_date":"1982-01-08","country":"Tunisie","region":"Tunis Governorate","city":"Tunis","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.","interests":["Cinéma","Bénévolat"],"denomination":"Protestante (Église réformée)","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.tn.22@profils-virtuels.yona.invalid","first_name":"Fares","last_name":"Bouazizi","gender":"male","birth_date":"1982-02-11","country":"Tunisie","region":"Sfax Governorate","city":"Sfax","bio":"Je suis un homme simple, passionné par la mode et la musique. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Musique","Mode"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.tn.23@profils-virtuels.yona.invalid","first_name":"Rania","last_name":"Gharbi","gender":"female","birth_date":"1995-08-25","country":"Tunisie","region":"Sousse Governorate","city":"Sousse","bio":"Je suis une femme simple, passionnée par les voyages et la mode. J'enseigne à l'école du dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Mode","Musique","Voyages"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.tn.24@profils-virtuels.yona.invalid","first_name":"Karim","last_name":"Jaziri","gender":"male","birth_date":"1990-10-27","country":"Tunisie","region":"Bizerte Governorate","city":"Bizerte","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de danse. Je suis engagé dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Danse","Musique","Bénévolat"],"denomination":"Protestante (Église réformée)","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":27,"max_age":45},
{"email":"virtuel.tn.25@profils-virtuels.yona.invalid","first_name":"Yosra","last_name":"Jebali","gender":"female","birth_date":"1993-02-18","country":"Tunisie","region":"Nabeul Governorate","city":"Nabeul","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux voyages. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Voyages","Danse","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":24,"max_age":42}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
