-- ============================================================
-- YONA — profils virtuels : fichier 10 sur 10
-- 75 profils : France, Belgique, Canada.
-- À coller tel quel dans Supabase → SQL Editor, puis « Run ».
-- Rejouable sans risque. À faire APRÈS le fichier de structure
-- (supabase/migrations/20261002100000_profils_virtuels_et_verification.sql).
-- ============================================================

DO $do$
DECLARE
  _seed jsonb := $seed$[{"email":"virtuel.fr.01@profils-virtuels.yona.invalid","first_name":"Marie","last_name":"Chevalier","gender":"female","birth_date":"1994-03-05","country":"France","region":"Île-de-France","city":"Paris","bio":"Souriante et attentionnée, j'aime les balades dans la nature et la mode. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.","interests":["Mode","Nature"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.fr.02@profils-virtuels.yona.invalid","first_name":"Benoît","last_name":"Bonnet","gender":"male","birth_date":"1978-06-27","country":"France","region":"Auvergne-Rhône-Alpes","city":"Lyon","bio":"Posé mais déterminé, j'aime la cuisine, le bénévolat et les longues discussions. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Cuisine","Danse","Bénévolat","Sport"],"denomination":"Protestante réformée","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.fr.03@profils-virtuels.yona.invalid","first_name":"Sarah","last_name":"Morel","gender":"female","birth_date":"1980-03-09","country":"France","region":"Provence-Alpes-Côte d'Azur","city":"Marseille","bio":"Souriante et attentionnée, j'aime la musique et la danse. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Danse","Musique"],"denomination":"Protestante réformée","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.fr.04@profils-virtuels.yona.invalid","first_name":"Hugo","last_name":"Martin","gender":"male","birth_date":"1980-03-16","country":"France","region":"Occitanie","city":"Toulouse","bio":"Fils de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la lecture. J'aime méditer la Parole chaque matin. J'attends une femme de foi, douce et pleine de joie.","interests":["Lecture","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.fr.05@profils-virtuels.yona.invalid","first_name":"Camille","last_name":"Faure","gender":"female","birth_date":"1985-03-31","country":"France","region":"New Aquitaine","city":"Bordeaux","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.","interests":["Voyages","Danse","Cinéma"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.fr.06@profils-virtuels.yona.invalid","first_name":"Clément","last_name":"Rousseau","gender":"male","birth_date":"1978-06-13","country":"France","region":"Hauts-de-France","city":"Lille","bio":"Souriant et attentionné, j'aime le cinéma et la mode. Je suis engagé dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Danse","Bénévolat","Cinéma","Mode"],"denomination":"Adventiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.fr.07@profils-virtuels.yona.invalid","first_name":"Hélène","last_name":"Masson","gender":"female","birth_date":"1992-01-09","country":"France","region":"Pays de la Loire","city":"Nantes","bio":"Je suis une femme simple, passionnée par la louange et les voyages. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Louange","Cuisine","Lecture","Voyages"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.fr.08@profils-virtuels.yona.invalid","first_name":"Louis","last_name":"Lambert","gender":"male","birth_date":"1980-03-25","country":"France","region":"Grand Est","city":"Strasbourg","bio":"Posé mais déterminé, j'aime la cuisine, la lecture et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. J'attends une femme de foi, douce et pleine de joie.","interests":["Lecture","Cuisine"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.fr.09@profils-virtuels.yona.invalid","first_name":"Anne","last_name":"Laurent","gender":"female","birth_date":"1990-10-09","country":"France","region":"Brittany","city":"Rennes","bio":"Je suis une femme simple, passionnée par le sport et la mode. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Sport","Danse","Nature","Mode"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.fr.10@profils-virtuels.yona.invalid","first_name":"Mathieu","last_name":"Dubois","gender":"male","birth_date":"1992-05-05","country":"France","region":"Occitanie","city":"Montpellier","bio":"Je suis un homme simple, passionné par la louange et le cinéma. La prière rythme mes journées. J'attends une femme de foi, douce et pleine de joie.","interests":["Louange","Cinéma"],"denomination":"Adventiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":25,"max_age":43},
{"email":"virtuel.fr.11@profils-virtuels.yona.invalid","first_name":"Pauline","last_name":"Bernard","gender":"female","birth_date":"2000-04-07","country":"France","region":"Auvergne-Rhône-Alpes","city":"Grenoble","bio":"Calme et joyeuse, je partage mon temps entre mon travail et les voyages. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Voyages","Photographie","Cuisine"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.fr.12@profils-virtuels.yona.invalid","first_name":"Nicolas","last_name":"André","gender":"male","birth_date":"1982-01-23","country":"France","region":"Provence-Alpes-Côte d'Azur","city":"Nice","bio":"Je suis un homme simple, passionné par les voyages et la danse. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Danse","Voyages"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.fr.13@profils-virtuels.yona.invalid","first_name":"Lucie","last_name":"Girard","gender":"female","birth_date":"1989-02-19","country":"France","region":"Centre-Val de Loire","city":"Tours","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la cuisine. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cuisine","Louange","Bénévolat","Photographie"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.fr.14@profils-virtuels.yona.invalid","first_name":"Étienne","last_name":"Moreau","gender":"male","birth_date":"1996-01-09","country":"France","region":"Pays de la Loire","city":"Angers","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Lecture","Photographie"],"denomination":"Adventiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.fr.15@profils-virtuels.yona.invalid","first_name":"Élise","last_name":"Garnier","gender":"female","birth_date":"1992-12-06","country":"France","region":"Île-de-France","city":"Paris","bio":"Fille de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la cuisine. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Nature","Cuisine","Louange"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":25,"max_age":43},
{"email":"virtuel.fr.16@profils-virtuels.yona.invalid","first_name":"Julien","last_name":"Fontaine","gender":"male","birth_date":"1982-07-31","country":"France","region":"Auvergne-Rhône-Alpes","city":"Lyon","bio":"Posé mais déterminé, j'aime la musique, les voyages et les longues discussions. Ma foi guide chacune de mes décisions. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Musique","Voyages"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":35,"max_age":53},
{"email":"virtuel.fr.17@profils-virtuels.yona.invalid","first_name":"Claire","last_name":"Fournier","gender":"female","birth_date":"1979-09-08","country":"France","region":"Provence-Alpes-Côte d'Azur","city":"Marseille","bio":"Je suis une femme simple, passionnée par la photographie et le sport. Je suis engagée dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Sport","Photographie"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.fr.18@profils-virtuels.yona.invalid","first_name":"Antoine","last_name":"Mercier","gender":"male","birth_date":"1994-12-26","country":"France","region":"Occitanie","city":"Toulouse","bio":"Calme et joyeux, je partage mon temps entre mon travail et la mode. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Mode","Cuisine"],"denomination":"Protestante réformée","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.fr.19@profils-virtuels.yona.invalid","first_name":"Sophie","last_name":"Robin","gender":"female","birth_date":"1999-12-10","country":"France","region":"New Aquitaine","city":"Bordeaux","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la danse. Je chante dans la chorale de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Danse"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.fr.20@profils-virtuels.yona.invalid","first_name":"Baptiste","last_name":"Lefebvre","gender":"male","birth_date":"1978-08-29","country":"France","region":"Hauts-de-France","city":"Lille","bio":"Posé mais déterminé, j'aime le bénévolat, la louange et les longues discussions. J'aide à l'organisation des sorties de l'église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Louange","Musique","Bénévolat","Mode"],"denomination":"Protestante réformée","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":39,"max_age":57},
{"email":"virtuel.fr.21@profils-virtuels.yona.invalid","first_name":"Émilie","last_name":"Chevalier","gender":"female","birth_date":"1999-08-30","country":"France","region":"Pays de la Loire","city":"Nantes","bio":"Je suis une femme simple, passionnée par la cuisine et la mode. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Cuisine","Mode","Louange"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":36},
{"email":"virtuel.fr.22@profils-virtuels.yona.invalid","first_name":"Samuel","last_name":"Bonnet","gender":"male","birth_date":"1986-12-09","country":"France","region":"Grand Est","city":"Strasbourg","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Cinéma"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":31,"max_age":49},
{"email":"virtuel.fr.23@profils-virtuels.yona.invalid","first_name":"Laure","last_name":"Morel","gender":"female","birth_date":"1993-04-08","country":"France","region":"Brittany","city":"Rennes","bio":"Chaque journée est un cadeau de Dieu : je la remplis de sport et de photographie. Je suis engagée dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Lecture","Sport"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.fr.24@profils-virtuels.yona.invalid","first_name":"Guillaume","last_name":"Martin","gender":"male","birth_date":"1983-11-30","country":"France","region":"Occitanie","city":"Montpellier","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Cinéma","Cuisine","Photographie"],"denomination":"Baptiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":34,"max_age":52},
{"email":"virtuel.fr.25@profils-virtuels.yona.invalid","first_name":"Mathilde","last_name":"Faure","gender":"female","birth_date":"1994-05-16","country":"France","region":"Auvergne-Rhône-Alpes","city":"Grenoble","bio":"Douce mais déterminée, j'aime la louange, la cuisine et les longues discussions. Je chante dans la chorale de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cinéma","Cuisine","Louange"],"denomination":"Protestante réformée","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":23,"max_age":41},
{"email":"virtuel.be.01@profils-virtuels.yona.invalid","first_name":"Pauline","last_name":"Simon","gender":"female","birth_date":"1987-08-06","country":"Belgique","region":"Brussels Capital","city":"Brussels","bio":"Douce mais déterminée, j'aime la lecture, la louange et les longues discussions. J'enseigne à l'école du dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Louange","Lecture","Danse"],"denomination":"Protestante unie","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":30,"max_age":48},
{"email":"virtuel.be.02@profils-virtuels.yona.invalid","first_name":"Cédric","last_name":"Gilson","gender":"male","birth_date":"1995-12-24","country":"Belgique","region":"Wallonia","city":"Liège","bio":"Souriant et attentionné, j'aime la louange et les voyages. Ma foi guide chacune de mes décisions. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Voyages","Louange"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.be.03@profils-virtuels.yona.invalid","first_name":"Sophie","last_name":"Dupont","gender":"female","birth_date":"1980-01-09","country":"Belgique","region":"Wallonia","city":"Namur","bio":"Souriante et attentionnée, j'aime la musique et la lecture. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Photographie","Lecture","Musique"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.be.04@profils-virtuels.yona.invalid","first_name":"Maxime","last_name":"Denis","gender":"male","birth_date":"1997-06-14","country":"Belgique","region":"Wallonia","city":"Charleroi","bio":"Fils de Dieu avant tout, je trouve ma joie dans la louange et la mode. Je joue dans le groupe de louange de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Louange","Mode","Cuisine","Lecture"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.be.05@profils-virtuels.yona.invalid","first_name":"Charlotte","last_name":"Lecomte","gender":"female","birth_date":"1986-10-07","country":"Belgique","region":"Wallonia","city":"Mons","bio":"Souriante et attentionnée, j'aime la musique et les voyages. J'enseigne à l'école du dimanche. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Cuisine","Voyages","Musique","Sport"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.be.06@profils-virtuels.yona.invalid","first_name":"François","last_name":"Goossens","gender":"male","birth_date":"1999-07-05","country":"Belgique","region":"Wallonia","city":"Louvain-la-Neuve","bio":"Je suis un homme simple, passionné par les balades dans la nature et la mode. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Mode","Nature"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":36},
{"email":"virtuel.be.07@profils-virtuels.yona.invalid","first_name":"Delphine","last_name":"Hubert","gender":"female","birth_date":"1985-05-02","country":"Belgique","region":"Wallonia","city":"Tournai","bio":"Je suis une femme simple, passionnée par le cinéma et la mode. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Mode"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.be.08@profils-virtuels.yona.invalid","first_name":"Laurent","last_name":"Wauters","gender":"male","birth_date":"1996-05-24","country":"Belgique","region":"Wallonia","city":"Wavre","bio":"Calme et joyeux, je partage mon temps entre mon travail et les voyages. Je joue dans le groupe de louange de mon église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Danse","Voyages"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":21,"max_age":39},
{"email":"virtuel.be.09@profils-virtuels.yona.invalid","first_name":"Nathalie","last_name":"Mertens","gender":"female","birth_date":"1990-01-25","country":"Belgique","region":"Wallonia","city":"Verviers","bio":"Souriante et attentionnée, j'aime le sport et le bénévolat. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Bénévolat","Mode","Cuisine","Sport"],"denomination":"Protestante unie","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.be.10@profils-virtuels.yona.invalid","first_name":"Gilles","last_name":"Leclercq","gender":"male","birth_date":"1995-11-13","country":"Belgique","region":"Wallonia","city":"Arlon","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre aux balades dans la nature. J'aime méditer la Parole chaque matin. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Nature"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":22,"max_age":40},
{"email":"virtuel.be.11@profils-virtuels.yona.invalid","first_name":"Valérie","last_name":"Marchal","gender":"female","birth_date":"1998-07-14","country":"Belgique","region":"Wallonia","city":"La Louvière","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la danse. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Louange","Danse"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":19,"max_age":37},
{"email":"virtuel.be.12@profils-virtuels.yona.invalid","first_name":"Christophe","last_name":"Collard","gender":"male","birth_date":"1987-07-27","country":"Belgique","region":"Wallonia","city":"Nivelles","bio":"Posé mais déterminé, j'aime la musique, la danse et les longues discussions. Je joue dans le groupe de louange de mon église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.","interests":["Danse","Musique","Louange"],"denomination":"Protestante unie","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":30,"max_age":48},
{"email":"virtuel.be.13@profils-virtuels.yona.invalid","first_name":"Élodie","last_name":"Martin","gender":"female","birth_date":"1995-11-09","country":"Belgique","region":"Brussels Capital","city":"Brussels","bio":"Douce mais déterminée, j'aime la photographie, le cinéma et les longues discussions. Je chante dans la chorale de mon église. J'attends un homme de foi, doux et responsable.","interests":["Photographie","Cinéma"],"denomination":"Protestante unie","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":22,"max_age":40},
{"email":"virtuel.be.14@profils-virtuels.yona.invalid","first_name":"Arnaud","last_name":"Lemaire","gender":"male","birth_date":"1990-07-13","country":"Belgique","region":"Wallonia","city":"Liège","bio":"Chaque journée est un cadeau de Dieu : je la remplis de cinéma et de danse. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Cinéma","Danse"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":27,"max_age":45},
{"email":"virtuel.be.15@profils-virtuels.yona.invalid","first_name":"Géraldine","last_name":"Lambert","gender":"female","birth_date":"1986-11-08","country":"Belgique","region":"Wallonia","city":"Namur","bio":"Souriante et attentionnée, j'aime la photographie et le cinéma. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Musique","Mode","Cinéma","Photographie"],"denomination":"Protestante unie","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":31,"max_age":49},
{"email":"virtuel.be.16@profils-virtuels.yona.invalid","first_name":"Damien","last_name":"Jacobs","gender":"male","birth_date":"1988-01-25","country":"Belgique","region":"Wallonia","city":"Charleroi","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la cuisine. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Sport","Lecture"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.be.17@profils-virtuels.yona.invalid","first_name":"Julie","last_name":"Lejeune","gender":"female","birth_date":"1977-01-10","country":"Belgique","region":"Wallonia","city":"Mons","bio":"Souriante et attentionnée, j'aime le bénévolat et la photographie. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Photographie","Bénévolat","Musique","Cuisine"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.be.18@profils-virtuels.yona.invalid","first_name":"Quentin","last_name":"Laurent","gender":"male","birth_date":"2000-07-15","country":"Belgique","region":"Wallonia","city":"Louvain-la-Neuve","bio":"Souriant et attentionné, j'aime le sport et la lecture. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Cuisine","Lecture","Bénévolat","Sport"],"denomination":"Évangélique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.be.19@profils-virtuels.yona.invalid","first_name":"Céline","last_name":"Dubois","gender":"female","birth_date":"1997-01-09","country":"Belgique","region":"Wallonia","city":"Tournai","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la photographie. Je sers à l'accueil de mon église le dimanche. J'attends un homme de foi, doux et responsable.","interests":["Cinéma","Photographie"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":20,"max_age":38},
{"email":"virtuel.be.20@profils-virtuels.yona.invalid","first_name":"Thibault","last_name":"Renard","gender":"male","birth_date":"1998-07-02","country":"Belgique","region":"Wallonia","city":"Wavre","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de danse. Je joue dans le groupe de louange de mon église. J'attends une femme de foi, douce et pleine de joie.","interests":["Lecture","Danse"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"female","min_age":19,"max_age":37},
{"email":"virtuel.be.21@profils-virtuels.yona.invalid","first_name":"Laurence","last_name":"Simon","gender":"female","birth_date":"1980-05-08","country":"Belgique","region":"Wallonia","city":"Verviers","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la photographie. Je participe à un groupe de prière chaque semaine. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Bénévolat","Sport","Voyages","Photographie"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.be.22@profils-virtuels.yona.invalid","first_name":"Jérôme","last_name":"Gilson","gender":"male","birth_date":"1997-06-11","country":"Belgique","region":"Wallonia","city":"Arlon","bio":"Je suis un homme simple, passionné par la musique et le bénévolat. Ma foi guide chacune de mes décisions. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Bénévolat"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":20,"max_age":38},
{"email":"virtuel.be.23@profils-virtuels.yona.invalid","first_name":"Virginie","last_name":"Dupont","gender":"female","birth_date":"1977-07-15","country":"Belgique","region":"Wallonia","city":"La Louvière","bio":"Je suis une femme simple, passionnée par la louange et la danse. Le Psaume 23 m'accompagne depuis toujours. Je cherche une relation sérieuse, en vue du mariage.","interests":["Louange","Danse"],"denomination":"Pentecôtiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.be.24@profils-virtuels.yona.invalid","first_name":"Benoît","last_name":"Denis","gender":"male","birth_date":"1994-04-13","country":"Belgique","region":"Wallonia","city":"Nivelles","bio":"Souriant et attentionné, j'aime les balades dans la nature et la photographie. J'aime méditer la Parole chaque matin. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Nature"],"denomination":"Pentecôtiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":23,"max_age":41},
{"email":"virtuel.be.25@profils-virtuels.yona.invalid","first_name":"Marie","last_name":"Lecomte","gender":"female","birth_date":"1982-12-09","country":"Belgique","region":"Brussels Capital","city":"Brussels","bio":"Je suis une femme simple, passionnée par la photographie et les voyages. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Photographie","Voyages"],"denomination":"Protestante unie","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":35,"max_age":53},
{"email":"virtuel.ca.01@profils-virtuels.yona.invalid","first_name":"Karine","last_name":"Ouellet","gender":"female","birth_date":"1985-10-09","country":"Canada","region":"Quebec","city":"Montréal","bio":"Chaque journée est un cadeau de Dieu : je la remplis de lecture et de danse. Je suis engagée dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.","interests":["Danse","Lecture","Cinéma"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":32,"max_age":50},
{"email":"virtuel.ca.02@profils-virtuels.yona.invalid","first_name":"Marc-André","last_name":"Lavoie","gender":"male","birth_date":"2001-03-17","country":"Canada","region":"Quebec","city":"Québec","bio":"Fils de Dieu avant tout, je trouve ma joie dans le sport et la photographie. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Nature","Bénévolat","Sport","Photographie"],"denomination":"Pentecôtiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":34},
{"email":"virtuel.ca.03@profils-virtuels.yona.invalid","first_name":"Valérie","last_name":"Bergeron","gender":"female","birth_date":"1980-05-21","country":"Canada","region":"Quebec","city":"Laval","bio":"Souriante et attentionnée, j'aime le sport et la cuisine. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.","interests":["Cuisine","Sport"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":37,"max_age":55},
{"email":"virtuel.ca.04@profils-virtuels.yona.invalid","first_name":"Mathieu","last_name":"Girard","gender":"male","birth_date":"1984-02-22","country":"Canada","region":"Quebec","city":"Gatineau","bio":"Calme et joyeux, je partage mon temps entre mon travail et le cinéma. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Cinéma","Lecture"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"female","min_age":33,"max_age":51},
{"email":"virtuel.ca.05@profils-virtuels.yona.invalid","first_name":"Isabelle","last_name":"Lévesque","gender":"female","birth_date":"2003-10-23","country":"Canada","region":"Quebec","city":"Longueuil","bio":"Souriante et attentionnée, j'aime les balades dans la nature et la musique. Ma foi guide chacune de mes décisions. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Nature","Cuisine","Musique","Photographie"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":18,"max_age":32},
{"email":"virtuel.ca.06@profils-virtuels.yona.invalid","first_name":"Alexandre","last_name":"Gauthier","gender":"male","birth_date":"2003-03-17","country":"Canada","region":"Quebec","city":"Sherbrooke","bio":"Calme et joyeux, je partage mon temps entre mon travail et la louange. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.","interests":["Louange","Photographie"],"denomination":"Baptiste","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":18,"max_age":32},
{"email":"virtuel.ca.07@profils-virtuels.yona.invalid","first_name":"Stéphanie","last_name":"Côté","gender":"female","birth_date":"1978-09-14","country":"Canada","region":"Quebec","city":"Saguenay","bio":"Douce mais déterminée, j'aime la photographie, le bénévolat et les longues discussions. Je chante dans la chorale de mon église. Je cherche une relation sérieuse, en vue du mariage.","interests":["Bénévolat","Photographie"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Mariage","preferred_gender":"male","min_age":39,"max_age":57},
{"email":"virtuel.ca.08@profils-virtuels.yona.invalid","first_name":"Philippe","last_name":"Boucher","gender":"male","birth_date":"1981-09-28","country":"Canada","region":"Quebec","city":"Lévis","bio":"Calme et joyeux, je partage mon temps entre mon travail et la louange. Je participe à un groupe de prière chaque semaine. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Louange","Danse","Cuisine","Bénévolat"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":36,"max_age":54},
{"email":"virtuel.ca.09@profils-virtuels.yona.invalid","first_name":"Noémie","last_name":"Gagnon","gender":"female","birth_date":"1996-06-14","country":"Canada","region":"Quebec","city":"Trois-Rivières","bio":"Douce mais déterminée, j'aime la louange, le bénévolat et les longues discussions. J'aime méditer la Parole chaque matin. J'attends un homme de foi, doux et responsable.","interests":["Louange","Bénévolat"],"denomination":"Anglicane","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"male","min_age":21,"max_age":39},
{"email":"virtuel.ca.10@profils-virtuels.yona.invalid","first_name":"Charles","last_name":"Simard","gender":"male","birth_date":"1989-09-06","country":"Canada","region":"Quebec","city":"Terrebonne","bio":"Souriant et attentionné, j'aime la danse et les balades dans la nature. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.","interests":["Danse","Cinéma","Cuisine","Nature"],"denomination":"Catholique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":28,"max_age":46},
{"email":"virtuel.ca.11@profils-virtuels.yona.invalid","first_name":"Julie","last_name":"Tremblay","gender":"female","birth_date":"1990-03-07","country":"Canada","region":"Quebec","city":"Drummondville","bio":"Douce mais déterminée, j'aime le cinéma, les balades dans la nature et les longues discussions. J'aime méditer la Parole chaque matin. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Cinéma","Nature"],"denomination":"Évangélique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":27,"max_age":45},
{"email":"virtuel.ca.12@profils-virtuels.yona.invalid","first_name":"Maxime","last_name":"Bouchard","gender":"male","birth_date":"1993-09-23","country":"Canada","region":"Quebec","city":"Rimouski","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre au sport. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.","interests":["Photographie","Sport"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":24,"max_age":42},
{"email":"virtuel.ca.13@profils-virtuels.yona.invalid","first_name":"Catherine","last_name":"Gagné","gender":"female","birth_date":"1979-01-21","country":"Canada","region":"Quebec","city":"Montréal","bio":"Souriante et attentionnée, j'aime les voyages et le bénévolat. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Photographie","Voyages","Bénévolat"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Très importante","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":38,"max_age":56},
{"email":"virtuel.ca.14@profils-virtuels.yona.invalid","first_name":"Jérémie","last_name":"Roy","gender":"male","birth_date":"2000-06-25","country":"Canada","region":"Quebec","city":"Québec","bio":"Dynamique et fidèle en amitié, je consacre mon temps libre à la cuisine. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Mode","Nature","Photographie","Cuisine"],"denomination":"Pentecôtiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":18,"max_age":35},
{"email":"virtuel.ca.15@profils-virtuels.yona.invalid","first_name":"Émilie","last_name":"Fortin","gender":"female","birth_date":"1989-07-09","country":"Canada","region":"Quebec","city":"Laval","bio":"Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. Je suis engagée dans le groupe de jeunes de ma paroisse. Prête à bâtir une famille fondée sur l'amour et la foi.","interests":["Sport","Voyages","Mode","Cinéma"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Mariage","preferred_gender":"male","min_age":28,"max_age":46},
{"email":"virtuel.ca.16@profils-virtuels.yona.invalid","first_name":"Louis-Philippe","last_name":"Paquette","gender":"male","birth_date":"1991-12-25","country":"Canada","region":"Quebec","city":"Gatineau","bio":"Souriant et attentionné, j'aime les balades dans la nature et la mode. Je participe à un groupe de prière chaque semaine. J'attends une femme de foi, douce et pleine de joie.","interests":["Nature","Mode","Louange"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.ca.17@profils-virtuels.yona.invalid","first_name":"Myriam","last_name":"Pelletier","gender":"female","birth_date":"1977-10-18","country":"Canada","region":"Quebec","city":"Longueuil","bio":"Souriante et attentionnée, j'aime le sport et la photographie. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.","interests":["Photographie","Cuisine","Sport"],"denomination":"Anglicane","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Faire connaissance d'abord","preferred_gender":"male","min_age":40,"max_age":58},
{"email":"virtuel.ca.18@profils-virtuels.yona.invalid","first_name":"Jean-François","last_name":"Bélanger","gender":"male","birth_date":"1990-03-21","country":"Canada","region":"Quebec","city":"Sherbrooke","bio":"Fils de Dieu avant tout, je trouve ma joie dans la mode et les balades dans la nature. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.","interests":["Musique","Mode","Nature"],"denomination":"Catholique","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":27,"max_age":45},
{"email":"virtuel.ca.19@profils-virtuels.yona.invalid","first_name":"Annie","last_name":"Morin","gender":"female","birth_date":"2000-07-02","country":"Canada","region":"Quebec","city":"Saguenay","bio":"Souriante et attentionnée, j'aime le cinéma et les voyages. Je sers à l'accueil de mon église le dimanche. J'attends un homme de foi, doux et responsable.","interests":["Voyages","Cinéma"],"denomination":"Catholique","church_attendance":"Plusieurs fois par semaine","prayer_practice":"Tous les jours","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":18,"max_age":35},
{"email":"virtuel.ca.20@profils-virtuels.yona.invalid","first_name":"Samuel","last_name":"Leblanc","gender":"male","birth_date":"1991-06-02","country":"Canada","region":"Quebec","city":"Lévis","bio":"Calme et joyeux, je partage mon temps entre mon travail et le sport. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.","interests":["Sport","Nature"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Plusieurs fois par semaine","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"female","min_age":26,"max_age":44},
{"email":"virtuel.ca.21@profils-virtuels.yona.invalid","first_name":"Geneviève","last_name":"Ouellet","gender":"female","birth_date":"1993-04-20","country":"Canada","region":"Quebec","city":"Trois-Rivières","bio":"Calme et joyeuse, je partage mon temps entre mon travail et la musique. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.","interests":["Cuisine","Musique","Louange"],"denomination":"Pentecôtiste","church_attendance":"Deux à trois fois par mois","prayer_practice":"Tous les jours","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.ca.22@profils-virtuels.yona.invalid","first_name":"Vincent","last_name":"Lavoie","gender":"male","birth_date":"1980-08-12","country":"Canada","region":"Quebec","city":"Terrebonne","bio":"Je suis un homme simple, passionné par le sport et la lecture. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.","interests":["Sport","Lecture"],"denomination":"Baptiste","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Relation sérieuse","preferred_gender":"female","min_age":37,"max_age":55},
{"email":"virtuel.ca.23@profils-virtuels.yona.invalid","first_name":"Marie-Ève","last_name":"Bergeron","gender":"female","birth_date":"1993-01-18","country":"Canada","region":"Quebec","city":"Drummondville","bio":"Fille de Dieu avant tout, je trouve ma joie dans les balades dans la nature et la louange. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Voyages","Nature","Louange"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Au centre de ma vie","goal":"Relation sérieuse","preferred_gender":"male","min_age":24,"max_age":42},
{"email":"virtuel.ca.24@profils-virtuels.yona.invalid","first_name":"Olivier","last_name":"Girard","gender":"male","birth_date":"1988-04-13","country":"Canada","region":"Quebec","city":"Rimouski","bio":"Calme et joyeux, je partage mon temps entre mon travail et la cuisine. J'aide à l'organisation des sorties de l'église. J'attends une femme de foi, douce et pleine de joie.","interests":["Voyages","Nature","Cuisine","Cinéma"],"denomination":"Anglicane","church_attendance":"Chaque semaine","prayer_practice":"Matin et soir","faith_importance":"Très importante","goal":"Relation sérieuse","preferred_gender":"female","min_age":29,"max_age":47},
{"email":"virtuel.ca.25@profils-virtuels.yona.invalid","first_name":"Sophie","last_name":"Lévesque","gender":"female","birth_date":"1980-05-09","country":"Canada","region":"Quebec","city":"Montréal","bio":"Fille de Dieu avant tout, je trouve ma joie dans la lecture et la musique. Ma foi guide chacune de mes décisions. Je souhaite rencontrer un homme sincère pour construire un foyer béni.","interests":["Lecture","Musique"],"denomination":"Évangélique","church_attendance":"Chaque semaine","prayer_practice":"Tous les jours","faith_importance":"Essentielle","goal":"Mariage","preferred_gender":"male","min_age":37,"max_age":55}]$seed$;
  _col text;
BEGIN
  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    s.email, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', s.first_name, 'last_name', s.last_name, 'is_virtual', true),
    now(), now()
  FROM jsonb_to_recordset(_seed) AS s(email text, first_name text, last_name text)
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = s.email);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = s.first_name,
      gender = s.gender::public.gender,
      birth_date = s.birth_date::date,
      country = s.country,
      region = s.region,
      city = s.city,
      bio = s.bio,
      interests = ARRAY(SELECT jsonb_array_elements_text(s.interests)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_to_recordset(_seed) AS s(
    email text, first_name text, gender text, birth_date text, country text, region text,
    city text, bio text, interests jsonb
  )
  JOIN public.users u ON u.email = s.email
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = s.denomination,
      church_attendance = s.church_attendance,
      prayer_practice = s.prayer_practice,
      faith_importance = s.faith_importance
  FROM jsonb_to_recordset(_seed) AS s(
    email text, denomination text, church_attendance text, prayer_practice text,
    faith_importance text
  )
  JOIN public.users u ON u.email = s.email
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET preferred_gender = s.preferred_gender::public.gender,
      min_age = s.min_age,
      max_age = s.max_age,
      relationship_goal = s.goal
  FROM jsonb_to_recordset(_seed) AS s(
    email text, preferred_gender text, min_age smallint, max_age smallint, goal text
  )
  JOIN public.users u ON u.email = s.email
  WHERE pr.user_id = u.id;
END
$do$;
