-- ============================================================
-- Profils virtuels : données (générées par scripts/generate-virtual-profiles.mjs)
--
-- * public.geo_countries : position de chaque pays (base GeoNames), pour « le pays le
--   plus proche » quand il n'y a plus de profil virtuel dans le pays d'un nouveau membre.
-- * 81 profils virtuels : 3 par pays (41 femmes et 40 hommes au total), 27 pays,
--   22 à 48 ans. Ce sont des comptes sans mot de passe (connexion impossible), marqués
--   « virtual » dans le compte et is_virtual dans le profil. Aucune photo : la carte
--   affiche l'initiale, en attendant de vraies photos.
-- Aucune table n'est créée. Rejouable sans risque : un profil déjà présent n'est pas
-- recréé, et les profils virtuels d'une version précédente absents de la liste sont retirés.
-- À exécuter APRÈS 20261002100000_profils_virtuels_et_verification.sql.
-- ============================================================

INSERT INTO public.geo_countries (code, name, lat, lng) VALUES
  ('AF', 'Afghanistan', 34.64, 67.55),
  ('ZA', 'Afrique du Sud', -28.59, 27.24),
  ('AL', 'Albanie', 41.1, 20.01),
  ('DZ', 'Algérie', 34.84, 3.3),
  ('DE', 'Allemagne', 50.65, 10.18),
  ('AD', 'Andorre', 42.53, 1.55),
  ('AO', 'Angola', -10.9, 15.97),
  ('AI', 'Anguilla', 18.21, -63.06),
  ('AG', 'Antigua-et-Barbuda', 17.14, -61.8),
  ('SA', 'Arabie saoudite', 23.86, 44.13),
  ('AR', 'Argentine', -32.06, -62.61),
  ('AM', 'Arménie', 40.31, 44.57),
  ('AW', 'Aruba', 12.52, -70),
  ('AU', 'Australie', -32.28, 144.13),
  ('AT', 'Autriche', 47.62, 14.38),
  ('AZ', 'Azerbaïdjan', 40.35, 47.71),
  ('BS', 'Bahamas', 24.76, -76.52),
  ('BH', 'Bahreïn', 26.17, 50.55),
  ('BD', 'Bangladesh', 23.69, 90.26),
  ('BB', 'Barbade', 13.18, -59.57),
  ('BE', 'Belgique', 50.74, 4.52),
  ('BZ', 'Belize', 17.49, -88.58),
  ('BJ', 'Bénin', 8.09, 2.23),
  ('BM', 'Bermudes', 32.31, -64.77),
  ('BT', 'Bhoutan', 27.29, 90.27),
  ('BY', 'Biélorussie', 53.57, 27.82),
  ('BO', 'Bolivie', -17.52, -65.46),
  ('BA', 'Bosnie-Herzégovine', 44.36, 17.83),
  ('BW', 'Botswana', -22.93, 25.8),
  ('BR', 'Brésil', -16.49, -46.3),
  ('BN', 'Brunei', 4.85, 114.81),
  ('BG', 'Bulgarie', 42.8, 25.14),
  ('BF', 'Burkina Faso', 12.31, -1.63),
  ('BI', 'Burundi', -3.36, 29.78),
  ('KH', 'Cambodge', 12.18, 104.71),
  ('CM', 'Cameroun', 5.75, 11.54),
  ('CA', 'Canada', 48.24, -91.4),
  ('CV', 'Cap-Vert', 15.7, -23.9),
  ('CF', 'Centrafrique', 5.68, 18.99),
  ('CL', 'Chili', -35.27, -71.82),
  ('CN', 'Chine', 32.44, 110.25),
  ('CY', 'Chypre', 34.98, 33.24),
  ('CO', 'Colombie', 5.69, -74.76),
  ('KM', 'Comores', -11.95, 43.86),
  ('CG', 'Congo-Brazzaville', -1.98, 14.64),
  ('KP', 'Corée du Nord', 40.17, 127.23),
  ('KR', 'Corée du Sud', 36.1, 127.44),
  ('CR', 'Costa Rica', 9.96, -84.23),
  ('CI', 'Côte d''Ivoire', 7.22, -5.64),
  ('HR', 'Croatie', 45.14, 16.41),
  ('CU', 'Cuba', 22.07, -79.92),
  ('CW', 'Curaçao', 12.17, -68.97),
  ('DK', 'Danemark', 55.84, 10.68),
  ('DJ', 'Djibouti', 11.64, 42.78),
  ('DM', 'Dominique', 15.41, -61.36),
  ('EG', 'Égypte', 29.35, 31.43),
  ('AE', 'Émirats arabes unis', 25.1, 55.37),
  ('EC', 'Équateur', -1.48, -79.11),
  ('ER', 'Érythrée', 14.98, 38.87),
  ('ES', 'Espagne', 40.54, -3.23),
  ('EE', 'Estonie', 58.93, 25.4),
  ('SZ', 'Eswatini', -26.5, 31.43),
  ('VA', 'État de la Cité du Vatican', 41.9, 12.45),
  ('US', 'États-Unis', 38.34, -90.5),
  ('ET', 'Éthiopie', 9.17, 38.9),
  ('FJ', 'Fidji', -17.37, 155.86),
  ('FI', 'Finlande', 61.71, 24.77),
  ('FR', 'France', 46.99, 2.49),
  ('GA', 'Gabon', -0.84, 11.68),
  ('GM', 'Gambie', 13.42, -15.7),
  ('GE', 'Géorgie', 42.22, 42.92),
  ('GS', 'Géorgie du Sud-et-les Îles Sandwich du Sud', -54.28, -36.51),
  ('GH', 'Ghana', 6.69, -1.01),
  ('GI', 'Gibraltar', 36.13, -5.35),
  ('GR', 'Grèce', 38.82, 23.19),
  ('GD', 'Grenade', 12.18, -61.66),
  ('GL', 'Groenland', 65.86, -49.72),
  ('GP', 'Guadeloupe', 16.18, -61.56),
  ('GU', 'Guam', 13.44, 144.76),
  ('GT', 'Guatemala', 14.92, -90.85),
  ('GG', 'Guernesey', 49.48, -2.55),
  ('GN', 'Guinée', 10.61, -11.28),
  ('GQ', 'Guinée équatoriale', 1.75, 9.86),
  ('GW', 'Guinée-Bissau', 11.95, -15.35),
  ('GY', 'Guyana', 6.39, -58.13),
  ('GF', 'Guyane française', 4.91, -52.93),
  ('HT', 'Haïti', 18.99, -72.73),
  ('HN', 'Honduras', 14.79, -87.52),
  ('HU', 'Hongrie', 47.32, 19.53),
  ('CX', 'Île Christmas', -10.42, 105.68),
  ('IM', 'Île de Man', 54.22, -4.54),
  ('NF', 'Île Norfolk', -29.05, 167.97),
  ('AX', 'Îles Åland', 60.2, 20.18),
  ('KY', 'Îles Caïmans', 19.36, -81.13),
  ('CC', 'Îles Cocos', -12.16, 96.82),
  ('CK', 'Îles Cook', -21.22, -159.75),
  ('FO', 'Îles Féroé', 61.99, -6.82),
  ('FK', 'Îles Malouines', -51.69, -57.86),
  ('MP', 'Îles Mariannes du Nord', 15.15, 145.71),
  ('MH', 'Îles Marshall', 8.25, 168.99),
  ('UM', 'Îles mineures éloignées des États-Unis', 0, 0),
  ('PN', 'Îles Pitcairn', -25.07, -130.1),
  ('SB', 'Îles Salomon', -9.17, 159.79),
  ('TC', 'Îles Turques-et-Caïques', 21.76, -72.06),
  ('VG', 'Îles Vierges britanniques', 18.44, -64.53),
  ('VI', 'Îles Vierges des États-Unis', 18.14, -64.84),
  ('IN', 'Inde', 20.45, 79.18),
  ('ID', 'Indonésie', -3.81, 112.59),
  ('IQ', 'Irak', 34.29, 44.56),
  ('IR', 'Iran', 33.83, 51.72),
  ('IE', 'Irlande', 53.2, -7.38),
  ('IS', 'Islande', 64.61, -20.27),
  ('IL', 'Israël', 32.28, 35.06),
  ('IT', 'Italie', 43.43, 11.58),
  ('JM', 'Jamaïque', 18.15, -77.28),
  ('JP', 'Japon', 35.92, 137.14),
  ('JE', 'Jersey', 49.21, -2.1),
  ('JO', 'Jordanie', 31.87, 35.89),
  ('KZ', 'Kazakhstan', 48.34, 69.24),
  ('KE', 'Kenya', -0.61, 36.73),
  ('KG', 'Kirghizstan', 41.33, 73.35),
  ('KI', 'Kiribati', 1.77, 85.99),
  ('XK', 'Kosovo', 42.55, 20.78),
  ('KW', 'Koweït', 29.26, 48.03),
  ('RE', 'La Réunion', -21.12, 55.5),
  ('LA', 'Laos', 18.32, 103.84),
  ('LS', 'Lesotho', -29.56, 27.95),
  ('LV', 'Lettonie', 56.91, 24.5),
  ('LB', 'Liban', 33.78, 35.71),
  ('LR', 'Liberia', 6.47, -9.26),
  ('LY', 'Libye', 30.87, 16.01),
  ('LI', 'Liechtenstein', 47.17, 9.52),
  ('LT', 'Lituanie', 55.17, 23.84),
  ('LU', 'Luxembourg', 49.68, 6.11),
  ('MK', 'Macédoine du Nord', 41.68, 21.56),
  ('MG', 'Madagascar', -19.25, 47.33),
  ('MY', 'Malaisie', 3.84, 103.4),
  ('MW', 'Malawi', -14, 34.52),
  ('MV', 'Maldives', 3.16, 73.28),
  ('ML', 'Mali', 14.02, -5.45),
  ('MT', 'Malte', 35.92, 14.43),
  ('MA', 'Maroc', 32.85, -6.37),
  ('MQ', 'Martinique', 14.64, -60.99),
  ('MU', 'Maurice', -20.09, 57.71),
  ('MR', 'Mauritanie', 17.35, -12.56),
  ('YT', 'Mayotte', -12.81, 45.15),
  ('MX', 'Mexique', 20.19, -99.25),
  ('FM', 'Micronésie', 6.96, 151.76),
  ('MD', 'Moldavie', 47.09, 28.73),
  ('MC', 'Monaco', 43.74, 7.42),
  ('MN', 'Mongolie', 47.48, 102.55),
  ('ME', 'Monténégro', 42.56, 19.22),
  ('MS', 'Montserrat', 16.76, -62.21),
  ('MZ', 'Mozambique', -18.98, 35.72),
  ('MM', 'Myanmar (Birmanie)', 18.13, 96.22),
  ('NA', 'Namibie', -21.54, 17.09),
  ('NR', 'Nauru', -0.53, 166.93),
  ('NP', 'Népal', 27.85, 84.29),
  ('NI', 'Nicaragua', 12.6, -85.89),
  ('NE', 'Niger', 14.45, 6.31),
  ('NG', 'Nigeria', 8.74, 7.37),
  ('NU', 'Niue', -19.05, -169.92),
  ('NO', 'Norvège', 61.99, 10.26),
  ('NC', 'Nouvelle-Calédonie', -21.77, 166.05),
  ('NZ', 'Nouvelle-Zélande', -40.4, 173.32),
  ('OM', 'Oman', 23.06, 57.18),
  ('UG', 'Ouganda', 0.82, 32.07),
  ('UZ', 'Ouzbékistan', 40.6, 67.22),
  ('PK', 'Pakistan', 30.57, 71.27),
  ('PW', 'Palaos', 7.15, 134.26),
  ('PA', 'Panama', 8.46, -80.7),
  ('PG', 'Papouasie-Nouvelle-Guinée', -6.36, 146.97),
  ('PY', 'Paraguay', -25.26, -56.68),
  ('NL', 'Pays-Bas', 52.07, 5.46),
  ('BQ', 'Pays-Bas caribéens', 14.2, -66.36),
  ('PE', 'Pérou', -11.1, -75.29),
  ('PH', 'Philippines', 11.9, 122.73),
  ('PL', 'Pologne', 51.48, 19.43),
  ('PF', 'Polynésie française', -17.3, -148.48),
  ('PR', 'Porto Rico', 18.23, -66.38),
  ('PT', 'Portugal', 39.58, -9.75),
  ('QA', 'Qatar', 25.39, 51.43),
  ('HK', 'R.A.S. chinoise de Hong Kong', 22.32, 114.17),
  ('MO', 'R.A.S. chinoise de Macao', 22.16, 113.55),
  ('CD', 'RD Congo', -3.38, 23.52),
  ('DO', 'République dominicaine', 18.93, -70.55),
  ('RO', 'Roumanie', 45.8, 25.13),
  ('GB', 'Royaume-Uni', 52.85, -1.84),
  ('RU', 'Russie', 53.5, 57.2),
  ('RW', 'Rwanda', -2.05, 29.63),
  ('EH', 'Sahara occidental', 25.2, -13.8),
  ('BL', 'Saint-Barthélemy', 17.9, -62.85),
  ('KN', 'Saint-Christophe-et-Niévès', 17.29, -62.73),
  ('SM', 'Saint-Marin', 43.94, 12.46),
  ('MF', 'Saint-Martin', 18.07, -63.07),
  ('SX', 'Saint-Martin (partie néerlandaise)', 18.04, -63.05),
  ('PM', 'Saint-Pierre-et-Miquelon', 46.94, -56.28),
  ('VC', 'Saint-Vincent-et-les Grenadines', 13.19, -61.2),
  ('SH', 'Sainte-Hélène', -19.21, -9.54),
  ('LC', 'Sainte-Lucie', 13.92, -60.96),
  ('SV', 'Salvador', 13.69, -88.93),
  ('WS', 'Samoa', -13.81, -171.93),
  ('AS', 'Samoa américaines', -14.11, -170.55),
  ('ST', 'Sao Tomé-et-Principe', 0.35, 6.72),
  ('SN', 'Sénégal', 14.58, -15.51),
  ('RS', 'Serbie', 44.74, 20.41),
  ('SC', 'Seychelles', -4.61, 55.51),
  ('SL', 'Sierra Leone', 8.36, -11.8),
  ('SG', 'Singapour', 1.34, 103.83),
  ('SK', 'Slovaquie', 48.62, 18.7),
  ('SI', 'Slovénie', 46.22, 14.98),
  ('SO', 'Somalie', 6.03, 45.39),
  ('SD', 'Soudan', 14.38, 31.45),
  ('SS', 'Soudan du Sud', 7, 29.54),
  ('LK', 'Sri Lanka', 7.15, 80.46),
  ('SE', 'Suède', 58.97, 15.37),
  ('CH', 'Suisse', 47.06, 8.11),
  ('SR', 'Suriname', 5.73, -55.27),
  ('SJ', 'Svalbard et Jan Mayen', 74.57, 3.46),
  ('SY', 'Syrie', 34.91, 37.07),
  ('TJ', 'Tadjikistan', 38.76, 69.45),
  ('TW', 'Taïwan', 24.15, 120.67),
  ('TZ', 'Tanzanie', -5.81, 35.5),
  ('TD', 'Tchad', 12.03, 17.55),
  ('CZ', 'Tchéquie', 49.75, 15.71),
  ('TF', 'Terres australes françaises', -49.35, 70.22),
  ('IO', 'Territoire britannique de l''océan Indien', -7.26, 72.38),
  ('PS', 'Territoires palestiniens', 31.97, 35.12),
  ('TH', 'Thaïlande', 14.32, 101.19),
  ('TL', 'Timor oriental', -8.8, 125.73),
  ('TG', 'Togo', 8.23, 0.97),
  ('TK', 'Tokelau', -9.04, -171.87),
  ('TO', 'Tonga', -20.64, -174.94),
  ('TT', 'Trinité-et-Tobago', 10.47, -61.4),
  ('TN', 'Tunisie', 35.64, 10.02),
  ('TM', 'Turkménistan', 38.57, 59.47),
  ('TR', 'Turquie', 38.86, 34.4),
  ('TV', 'Tuvalu', -7.69, 178.29),
  ('UA', 'Ukraine', 48.43, 30.97),
  ('UY', 'Uruguay', -33.56, -56.18),
  ('VU', 'Vanuatu', -16.33, 167.83),
  ('VE', 'Venezuela', 9.4, -68.25),
  ('VN', 'Viêt Nam', 16.62, 106.32),
  ('WF', 'Wallis-et-Futuna', -13.96, -177.48),
  ('YE', 'Yémen', 14.9, 45.12),
  ('ZM', 'Zambie', -13.55, 28.12),
  ('ZW', 'Zimbabwe', -18.52, 30.34)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, lat = EXCLUDED.lat, lng = EXCLUDED.lng;

DO $do$
DECLARE
  _seed jsonb := $seed$[
["virtuel.ga.01@profils-virtuels.yona.invalid","Prisca","Ondo","female","1997-10-29","Gabon","Estuaire","Libreville","Souriante et attentionnée, j'aime la cuisine et la louange. J'enseigne à l'école du dimanche. J'attends un homme de foi, doux et responsable.",["Louange","Cuisine"],"Adventiste","Plusieurs fois par semaine","Matin et soir","Au centre de ma vie","Relation sérieuse","male",20,38],
["virtuel.ga.02@profils-virtuels.yona.invalid","Steeve","Mintsa","male","2000-04-03","Gabon","Ogooué-Maritime","Port-Gentil","Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.",["Nature","Louange","Voyages"],"Adventiste","Plusieurs fois par semaine","Plusieurs fois par semaine","Très importante","Mariage","female",18,35],
["virtuel.ga.03@profils-virtuels.yona.invalid","Rachel","Obiang","female","1986-04-18","Gabon","Haut-Ogooué","Franceville","Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. J'enseigne à l'école du dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Voyages","Musique","Cinéma","Mode"],"Catholique","Chaque semaine","Matin et soir","Essentielle","Mariage","male",31,49],
["virtuel.cm.01@profils-virtuels.yona.invalid","Guy","Bella","male","1992-07-26","Cameroun","Centre","Yaoundé","Calme et joyeux, je partage mon temps entre mon travail et la musique. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.",["Louange","Musique","Cinéma"],"Catholique","Chaque semaine","Matin et soir","Essentielle","Mariage","female",25,43],
["virtuel.cm.02@profils-virtuels.yona.invalid","Danielle","Kenmogne","female","1978-05-14","Cameroun","Littoral","Douala","Fille de Dieu avant tout, je trouve ma joie dans la danse et la lecture. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.",["Mode","Lecture","Danse"],"Presbytérienne","Chaque semaine","Matin et soir","Très importante","Mariage","male",39,57],
["virtuel.cm.03@profils-virtuels.yona.invalid","Serge","Mbarga","male","2001-03-27","Cameroun","West","Bafoussam","Calme et joyeux, je partage mon temps entre mon travail et la lecture. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.",["Lecture","Cinéma"],"Presbytérienne","Chaque semaine","Plusieurs fois par semaine","Au centre de ma vie","Relation sérieuse","female",18,34],
["virtuel.cg.01@profils-virtuels.yona.invalid","Prisca","Okemba","female","1992-02-26","Congo-Brazzaville","Brazzaville","Brazzaville","Souriante et attentionnée, j'aime la danse et la cuisine. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.",["Cuisine","Danse","Mode"],"Catholique","Chaque semaine","Plusieurs fois par semaine","Très importante","Relation sérieuse","male",25,43],
["virtuel.cg.02@profils-virtuels.yona.invalid","Hardy","Moukoko","male","1982-09-02","Congo-Brazzaville","Pointe-Noire","Pointe-Noire","Je suis un homme simple, passionné par la danse et le sport. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.",["Danse","Sport","Lecture","Photographie"],"Catholique","Chaque semaine","Tous les jours","Au centre de ma vie","Relation sérieuse","female",35,53],
["virtuel.cg.03@profils-virtuels.yona.invalid","Reine","Ngoma","female","1983-07-24","Congo-Brazzaville","Niari","Dolisie","Dynamique et fidèle en amitié, je consacre mon temps libre au bénévolat. Je suis engagée dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.",["Nature","Sport","Photographie","Bénévolat"],"Kimbanguiste","Plusieurs fois par semaine","Plusieurs fois par semaine","Très importante","Relation sérieuse","male",34,52],
["virtuel.cd.01@profils-virtuels.yona.invalid","Ruphin","Mbuyi","male","1985-10-09","RD Congo","Kinshasa","Kinshasa","Je suis un homme simple, passionné par la danse et le sport. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.",["Sport","Danse","Lecture"],"Pentecôtiste","Chaque semaine","Plusieurs fois par semaine","Essentielle","Relation sérieuse","female",32,50],
["virtuel.cd.02@profils-virtuels.yona.invalid","Grâce","Lukusa","female","1987-10-10","RD Congo","Haut-Katanga","Lubumbashi","Douce mais déterminée, j'aime le cinéma, la lecture et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Lecture","Cinéma","Sport"],"Pentecôtiste","Plusieurs fois par semaine","Matin et soir","Essentielle","Faire connaissance d'abord","male",30,48],
["virtuel.cd.03@profils-virtuels.yona.invalid","Dieumerci","Kabeya","male","2000-11-30","RD Congo","East Kasai","Mbuji-Mayi","Chaque journée est un cadeau de Dieu : je la remplis de lecture et de musique. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.",["Lecture","Musique"],"Kimbanguiste","Chaque semaine","Matin et soir","Au centre de ma vie","Relation sérieuse","female",18,35],
["virtuel.ci.01@profils-virtuels.yona.invalid","Chantal","Assi","female","1988-08-31","Côte d'Ivoire","Abidjan Autonomous District","Abidjan","Douce mais déterminée, j'aime les balades dans la nature, la cuisine et les longues discussions. Je chante dans la chorale de mon église. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Cuisine","Nature"],"Adventiste","Chaque semaine","Tous les jours","Au centre de ma vie","Relation sérieuse","male",29,47],
["virtuel.ci.02@profils-virtuels.yona.invalid","Kouassi","Brou","male","1992-12-11","Côte d'Ivoire","Vallée du Bandama District","Bouaké","Posé mais déterminé, j'aime les balades dans la nature, le cinéma et les longues discussions. La prière rythme mes journées. Je crois au mariage, à la fidélité et au respect.",["Photographie","Mode","Cinéma","Nature"],"Évangélique (Assemblées de Dieu)","Chaque semaine","Matin et soir","Très importante","Mariage","female",25,43],
["virtuel.ci.03@profils-virtuels.yona.invalid","Ruth","Gnagne","female","1977-04-30","Côte d'Ivoire","Lacs District","Yamoussoukro","Je suis une femme simple, passionnée par la cuisine et les voyages. La prière rythme mes journées. Je souhaite rencontrer un homme sincère pour construire un foyer béni.",["Voyages","Cuisine"],"Évangélique (Assemblées de Dieu)","Plusieurs fois par semaine","Plusieurs fois par semaine","Au centre de ma vie","Mariage","male",40,58],
["virtuel.sn.01@profils-virtuels.yona.invalid","Antoine","Diène","male","2001-07-28","Sénégal","Dakar","Dakar","Souriant et attentionné, j'aime la musique et le bénévolat. Je sers à l'accueil de mon église le dimanche. Je cherche une relation sérieuse, en vue du mariage.",["Bénévolat","Musique","Louange"],"Adventiste","Deux à trois fois par mois","Plusieurs fois par semaine","Au centre de ma vie","Relation sérieuse","female",18,34],
["virtuel.sn.02@profils-virtuels.yona.invalid","Clémentine","Faye","female","1988-04-08","Sénégal","Thies","Thiès","Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.",["Cinéma","Louange"],"Protestante","Deux à trois fois par mois","Matin et soir","Essentielle","Relation sérieuse","male",29,47],
["virtuel.sn.03@profils-virtuels.yona.invalid","Ferdinand","Diatta","male","1979-08-03","Sénégal","Ziguinchor","Ziguinchor","Chaque journée est un cadeau de Dieu : je la remplis de balades dans la nature et de bénévolat. Je participe à un groupe de prière chaque semaine. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Nature","Bénévolat"],"Évangélique","Chaque semaine","Tous les jours","Au centre de ma vie","Mariage","female",38,56],
["virtuel.ml.01@profils-virtuels.yona.invalid","Rachel","Goïta","female","1992-06-02","Mali","Bamako","Bamako","Souriante et attentionnée, j'aime la mode et les voyages. Je chante dans la chorale de mon église. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Danse","Musique","Voyages","Mode"],"Protestante (Église chrétienne évangélique)","Chaque semaine","Tous les jours","Essentielle","Relation sérieuse","male",25,43],
["virtuel.ml.02@profils-virtuels.yona.invalid","Emmanuel","Bengaly","male","1997-11-27","Mali","Sikasso","Sikasso","Fils de Dieu avant tout, je trouve ma joie dans la lecture et la photographie. La prière rythme mes journées. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Photographie","Lecture","Danse"],"Évangélique","Chaque semaine","Matin et soir","Très importante","Faire connaissance d'abord","female",20,38],
["virtuel.ml.03@profils-virtuels.yona.invalid","Élise","Kassogué","female","2001-12-18","Mali","Ségou","Ségou","Douce mais déterminée, j'aime la mode, le bénévolat et les longues discussions. Je participe à un groupe de prière chaque semaine. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Bénévolat","Nature","Mode"],"Évangélique","Deux à trois fois par mois","Tous les jours","Au centre de ma vie","Relation sérieuse","male",18,34],
["virtuel.bf.01@profils-virtuels.yona.invalid","Lazare","Yaméogo","male","1977-03-12","Burkina Faso","Centre","Ouagadougou","Posé mais déterminé, j'aime les balades dans la nature, la cuisine et les longues discussions. Je participe à un groupe de prière chaque semaine. Je cherche une relation sérieuse, en vue du mariage.",["Lecture","Cuisine","Nature"],"Protestante","Chaque semaine","Matin et soir","Essentielle","Relation sérieuse","female",40,58],
["virtuel.bf.02@profils-virtuels.yona.invalid","Carine","Kouraogo","female","1992-10-01","Burkina Faso","Hauts-Bassins","Bobo-Dioulasso","Douce mais déterminée, j'aime le cinéma, le bénévolat et les longues discussions. Je suis engagée dans le groupe de jeunes de ma paroisse. Je crois au mariage, à la fidélité et au respect.",["Bénévolat","Cinéma","Nature"],"Évangélique","Plusieurs fois par semaine","Tous les jours","Très importante","Relation sérieuse","male",25,43],
["virtuel.bf.03@profils-virtuels.yona.invalid","Gérard","Kinda","male","2002-08-15","Burkina Faso","Centre-Ouest","Koudougou","Souriant et attentionné, j'aime la musique et le sport. Je joue dans le groupe de louange de mon église. Je crois au mariage, à la fidélité et au respect.",["Musique","Cinéma","Louange","Sport"],"Adventiste","Chaque semaine","Plusieurs fois par semaine","Essentielle","Relation sérieuse","female",18,33],
["virtuel.ne.01@profils-virtuels.yona.invalid","Naomi","Seyni","female","1999-05-17","Niger","Niamey","Niamey","Dynamique et fidèle en amitié, je consacre mon temps libre au sport. Je chante dans la chorale de mon église. Je souhaite rencontrer un homme sincère pour construire un foyer béni.",["Sport","Voyages"],"Évangélique (EERN)","Chaque semaine","Tous les jours","Très importante","Relation sérieuse","male",18,36],
["virtuel.ne.02@profils-virtuels.yona.invalid","Philippe","Djibo","male","1977-03-25","Niger","Maradi Region","Maradi","Chaque journée est un cadeau de Dieu : je la remplis de voyages et de bénévolat. Je suis engagé dans le groupe de jeunes de ma paroisse. Prêt à bâtir une famille fondée sur l'amour et la foi.",["Voyages","Bénévolat"],"Évangélique (EERN)","Chaque semaine","Plusieurs fois par semaine","Essentielle","Faire connaissance d'abord","female",40,58],
["virtuel.ne.03@profils-virtuels.yona.invalid","Lydie","Hamani","female","1977-11-14","Niger","Zinder Region","Zinder","Je suis une femme simple, passionnée par la mode et la danse. Je suis engagée dans le groupe de jeunes de ma paroisse. Je cherche une relation sérieuse, en vue du mariage.",["Danse","Musique","Mode","Louange"],"Catholique","Deux à trois fois par mois","Plusieurs fois par semaine","Très importante","Relation sérieuse","male",40,58],
["virtuel.tg.01@profils-virtuels.yona.invalid","Komla","Kudjoh","male","2003-12-26","Togo","Maritime","Lomé","Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. J'aime méditer la Parole chaque matin. Je crois au mariage, à la fidélité et au respect.",["Sport","Photographie","Lecture","Cuisine"],"Adventiste","Plusieurs fois par semaine","Plusieurs fois par semaine","Essentielle","Mariage","female",18,32],
["virtuel.tg.02@profils-virtuels.yona.invalid","Edem","Ekoué","female","1977-06-13","Togo","Centrale","Sokodé","Douce mais déterminée, j'aime les balades dans la nature, la photographie et les longues discussions. Je participe à un groupe de prière chaque semaine. Je crois au mariage, à la fidélité et au respect.",["Lecture","Danse","Photographie","Nature"],"Assemblées de Dieu","Chaque semaine","Matin et soir","Essentielle","Mariage","male",40,58],
["virtuel.tg.03@profils-virtuels.yona.invalid","Sénamé","Sossou","male","1985-11-26","Togo","Kara","Kara","Calme et joyeux, je partage mon temps entre mon travail et le cinéma. Ma foi guide chacune de mes décisions. Prêt à bâtir une famille fondée sur l'amour et la foi.",["Cinéma","Voyages"],"Catholique","Deux à trois fois par mois","Plusieurs fois par semaine","Très importante","Faire connaissance d'abord","female",32,50],
["virtuel.bj.01@profils-virtuels.yona.invalid","Gisèle","Kiki","female","1991-03-13","Bénin","Littoral","Cotonou","Calme et joyeuse, je partage mon temps entre mon travail et la cuisine. La prière rythme mes journées. J'attends un homme de foi, doux et responsable.",["Mode","Cuisine"],"Église du christianisme céleste","Deux à trois fois par mois","Plusieurs fois par semaine","Au centre de ma vie","Faire connaissance d'abord","male",26,44],
["virtuel.bj.02@profils-virtuels.yona.invalid","Dieudonné","Gbaguidi","male","1982-07-04","Bénin","Ouémé","Porto-Novo","Posé mais déterminé, j'aime la cuisine, la photographie et les longues discussions. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.",["Cuisine","Photographie"],"Catholique","Plusieurs fois par semaine","Plusieurs fois par semaine","Essentielle","Mariage","female",35,53],
["virtuel.bj.03@profils-virtuels.yona.invalid","Bénédicte","Amoussou","female","1982-02-11","Bénin","Borgou","Parakou","Calme et joyeuse, je partage mon temps entre mon travail et la louange. Je chante dans la chorale de mon église. Je souhaite rencontrer un homme sincère pour construire un foyer béni.",["Louange","Photographie","Musique","Lecture"],"Évangélique","Chaque semaine","Tous les jours","Au centre de ma vie","Mariage","male",35,53],
["virtuel.gn.01@profils-virtuels.yona.invalid","Honoré","Loua","male","1997-09-03","Guinée","Conakry","Conakry","Dynamique et fidèle en amitié, je consacre mon temps libre au cinéma. J'aide à l'organisation des sorties de l'église. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.",["Louange","Cinéma","Cuisine"],"Protestante évangélique","Deux à trois fois par mois","Tous les jours","Au centre de ma vie","Relation sérieuse","female",20,38],
["virtuel.gn.02@profils-virtuels.yona.invalid","Denise","Kolié","female","1984-08-14","Guinée","Nzérékoré Region","Nzérékoré","Dynamique et fidèle en amitié, je consacre mon temps libre à la photographie. J'enseigne à l'école du dimanche. Prête à bâtir une famille fondée sur l'amour et la foi.",["Photographie","Sport"],"Protestante évangélique","Deux à trois fois par mois","Matin et soir","Très importante","Relation sérieuse","male",33,51],
["virtuel.gn.03@profils-virtuels.yona.invalid","Pascal","Kourouma","male","1989-09-03","Guinée","Kankan Region","Kankan","Souriant et attentionné, j'aime le cinéma et la lecture. La prière rythme mes journées. Je cherche une relation sérieuse, en vue du mariage.",["Cinéma","Lecture"],"Anglicane","Chaque semaine","Tous les jours","Très importante","Mariage","female",28,46],
["virtuel.td.01@profils-virtuels.yona.invalid","Honorine","Mbaïlemdana","female","1984-02-19","Tchad","N'Djaména","N'Djamena","Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.",["Lecture","Louange","Cinéma"],"Assemblées chrétiennes","Deux à trois fois par mois","Tous les jours","Très importante","Mariage","male",33,51],
["virtuel.td.02@profils-virtuels.yona.invalid","Alain","Doumgor","male","2001-07-23","Tchad","Logone Occidental","Moundou","Calme et joyeux, je partage mon temps entre mon travail et le bénévolat. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.",["Cuisine","Danse","Bénévolat"],"Baptiste","Chaque semaine","Plusieurs fois par semaine","Essentielle","Mariage","female",18,34],
["virtuel.td.03@profils-virtuels.yona.invalid","Esther","Ngaba","female","1980-07-21","Tchad","Moyen-Chari","Sarh","Je suis une femme simple, passionnée par les voyages et la cuisine. La prière rythme mes journées. Prête à bâtir une famille fondée sur l'amour et la foi.",["Cuisine","Danse","Voyages"],"Catholique","Plusieurs fois par semaine","Tous les jours","Au centre de ma vie","Relation sérieuse","male",37,55],
["virtuel.cf.01@profils-virtuels.yona.invalid","Martial","Sélébangue","male","1982-01-05","Centrafrique","Bangui","Bangui","Fils de Dieu avant tout, je trouve ma joie dans le bénévolat et la danse. Je joue dans le groupe de louange de mon église. Je crois au mariage, à la fidélité et au respect.",["Musique","Danse","Bénévolat","Nature"],"Apostolique","Deux à trois fois par mois","Tous les jours","Très importante","Relation sérieuse","female",35,53],
["virtuel.cf.02@profils-virtuels.yona.invalid","Anicette","Mbaïkoua","female","1984-12-16","Centrafrique","Ombella-M'Poko","Bimbo","Chaque journée est un cadeau de Dieu : je la remplis de louange et de bénévolat. Le Psaume 23 m'accompagne depuis toujours. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Mode","Louange","Lecture","Bénévolat"],"Baptiste","Chaque semaine","Tous les jours","Très importante","Mariage","male",33,51],
["virtuel.cf.03@profils-virtuels.yona.invalid","Fidèle","Kossi","male","2001-04-13","Centrafrique","Mambéré-Kadéï","Berbérati","Souriant et attentionné, j'aime le cinéma et la mode. Je suis engagé dans le groupe de jeunes de ma paroisse. J'attends une femme de foi, douce et pleine de joie.",["Cinéma","Voyages","Mode"],"Baptiste","Deux à trois fois par mois","Matin et soir","Très importante","Faire connaissance d'abord","female",18,34],
["virtuel.mg.01@profils-virtuels.yona.invalid","Noro","Rasolofonirina","female","1990-01-19","Madagascar","Analamanga","Antananarivo","Chaque journée est un cadeau de Dieu : je la remplis de balades dans la nature et de cuisine. Je chante dans la chorale de mon église. Je souhaite rencontrer un homme sincère pour construire un foyer béni.",["Nature","Cuisine"],"Anglicane","Plusieurs fois par semaine","Tous les jours","Au centre de ma vie","Relation sérieuse","male",27,45],
["virtuel.mg.02@profils-virtuels.yona.invalid","Naina","Randriamampionona","male","1984-12-11","Madagascar","Atsinanana","Toamasina","Posé mais déterminé, j'aime les voyages, la lecture et les longues discussions. Je suis engagé dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Lecture","Voyages","Danse"],"Catholique","Chaque semaine","Plusieurs fois par semaine","Très importante","Relation sérieuse","female",33,51],
["virtuel.mg.03@profils-virtuels.yona.invalid","Nirina","Andriatsitohaina","female","1996-02-18","Madagascar","Vakinankaratra","Antsirabe","Calme et joyeuse, je partage mon temps entre mon travail et les balades dans la nature. Je chante dans la chorale de mon église. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Nature","Voyages"],"Luthérienne (FLM)","Chaque semaine","Matin et soir","Très importante","Mariage","male",21,39],
["virtuel.bi.01@profils-virtuels.yona.invalid","Vianney","Uwimana","male","1986-12-10","Burundi","Bujumbura Mairie","Bujumbura","Dynamique et fidèle en amitié, je consacre mon temps libre au sport. Je suis engagé dans le groupe de jeunes de ma paroisse. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Bénévolat","Sport"],"Pentecôtiste","Chaque semaine","Plusieurs fois par semaine","Au centre de ma vie","Mariage","female",31,49],
["virtuel.bi.02@profils-virtuels.yona.invalid","Liliane","Niyonzima","female","1987-04-28","Burundi","Gitega","Gitega","Calme et joyeuse, je partage mon temps entre mon travail et le cinéma. J'aime méditer la Parole chaque matin. Prête à bâtir une famille fondée sur l'amour et la foi.",["Cinéma","Photographie","Sport"],"Évangélique","Chaque semaine","Tous les jours","Essentielle","Mariage","male",30,48],
["virtuel.bi.03@profils-virtuels.yona.invalid","Éric","Nibizi","male","1982-03-06","Burundi","Ngozi","Ngozi","Calme et joyeux, je partage mon temps entre mon travail et le bénévolat. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.",["Nature","Bénévolat"],"Anglicane","Chaque semaine","Tous les jours","Très importante","Relation sérieuse","female",35,53],
["virtuel.rw.01@profils-virtuels.yona.invalid","Esther","Gatera","female","1988-01-08","Rwanda","Kigali","Kigali","Souriante et attentionnée, j'aime le bénévolat et la danse. La prière rythme mes journées. Prête à bâtir une famille fondée sur l'amour et la foi.",["Louange","Bénévolat","Danse"],"Adventiste","Deux à trois fois par mois","Matin et soir","Au centre de ma vie","Mariage","male",29,47],
["virtuel.rw.02@profils-virtuels.yona.invalid","Fabrice","Kayitesi","male","1984-02-08","Rwanda","Southern Province","Butare","Souriant et attentionné, j'aime le cinéma et la musique. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Cinéma","Musique"],"Adventiste","Deux à trois fois par mois","Tous les jours","Essentielle","Faire connaissance d'abord","female",33,51],
["virtuel.rw.03@profils-virtuels.yona.invalid","Liliane","Munyaneza","female","1991-06-06","Rwanda","Western Province","Gisenyi","Je suis une femme simple, passionnée par le bénévolat et la mode. Le Psaume 23 m'accompagne depuis toujours. Prête à bâtir une famille fondée sur l'amour et la foi.",["Mode","Bénévolat"],"Adventiste","Chaque semaine","Tous les jours","Essentielle","Relation sérieuse","male",26,44],
["virtuel.dj.01@profils-virtuels.yona.invalid","Antoine","Moussa","male","2000-09-30","Djibouti","Djibouti","Djibouti","Souriant et attentionné, j'aime les voyages et le cinéma. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Cinéma","Voyages"],"Évangélique","Plusieurs fois par semaine","Tous les jours","Très importante","Relation sérieuse","female",18,35],
["virtuel.dj.02@profils-virtuels.yona.invalid","Naomi","Hassan","female","2002-07-18","Djibouti","Tadjourah","Tadjoura","Chaque journée est un cadeau de Dieu : je la remplis de lecture et de mode. Je sers à l'accueil de mon église le dimanche. Je crois au mariage, à la fidélité et au respect.",["Mode","Danse","Lecture"],"Évangélique","Deux à trois fois par mois","Tous les jours","Très importante","Mariage","male",18,33],
["virtuel.dj.03@profils-virtuels.yona.invalid","Michel","Hersi","male","2002-06-13","Djibouti","Obock","Obock","Chaque journée est un cadeau de Dieu : je la remplis de cuisine et de bénévolat. Je sers à l'accueil de mon église le dimanche. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.",["Cuisine","Bénévolat","Nature"],"Catholique","Chaque semaine","Matin et soir","Essentielle","Relation sérieuse","female",18,33],
["virtuel.km.01@profils-virtuels.yona.invalid","Ankili","Soulé","female","2001-01-31","Comores","Grande Comore","Moroni","Calme et joyeuse, je partage mon temps entre mon travail et la mode. Je chante dans la chorale de mon église. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Sport","Voyages","Nature","Mode"],"Protestante","Chaque semaine","Matin et soir","Très importante","Relation sérieuse","male",18,34],
["virtuel.km.02@profils-virtuels.yona.invalid","Saïd","Bacar","male","1980-01-10","Comores","Anjouan","Moutsamoudou","Je suis un homme simple, passionné par la danse et le cinéma. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.",["Cinéma","Cuisine","Sport","Danse"],"Évangélique","Chaque semaine","Tous les jours","Au centre de ma vie","Relation sérieuse","female",37,55],
["virtuel.km.03@profils-virtuels.yona.invalid","Esther","Mbaé","female","1995-12-12","Comores","Mohéli","Fomboni","Je suis une femme simple, passionnée par le bénévolat et le cinéma. Je chante dans la chorale de mon église. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Cinéma","Bénévolat","Danse"],"Évangélique","Chaque semaine","Plusieurs fois par semaine","Très importante","Relation sérieuse","male",22,40],
["virtuel.mu.01@profils-virtuels.yona.invalid","Olivier","Appadoo","male","1987-05-12","Maurice","Port Louis","Port Louis","Je suis un homme simple, passionné par la cuisine et la lecture. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.",["Nature","Lecture","Louange","Cuisine"],"Assemblées de Dieu","Plusieurs fois par semaine","Tous les jours","Très importante","Mariage","female",30,48],
["virtuel.mu.02@profils-virtuels.yona.invalid","Stéphanie","Henri","female","1995-01-14","Maurice","Plaines Wilhems","Curepipe","Fille de Dieu avant tout, je trouve ma joie dans la mode et la louange. Je chante dans la chorale de mon église. J'attends un homme de foi, doux et responsable.",["Mode","Sport","Louange","Cinéma"],"Assemblées de Dieu","Deux à trois fois par mois","Matin et soir","Au centre de ma vie","Faire connaissance d'abord","male",22,40],
["virtuel.mu.03@profils-virtuels.yona.invalid","Patrick","Bégué","male","1996-01-02","Maurice","Plaines Wilhems","Quatre Bornes","Dynamique et fidèle en amitié, je consacre mon temps libre au cinéma. Je suis engagé dans le groupe de jeunes de ma paroisse. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.",["Lecture","Cinéma","Nature","Voyages"],"Catholique","Chaque semaine","Tous les jours","Très importante","Faire connaissance d'abord","female",21,39],
["virtuel.sc.01@profils-virtuels.yona.invalid","Amanda","Larue","female","1988-11-01","Seychelles","La Rivière Anglaise","Victoria","Douce mais déterminée, j'aime la louange, la mode et les longues discussions. La prière rythme mes journées. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Louange","Mode"],"Anglicane","Plusieurs fois par semaine","Matin et soir","Essentielle","Mariage","male",29,47],
["virtuel.sc.02@profils-virtuels.yona.invalid","Wavel","Hoareau","male","1984-07-26","Seychelles","Anse Boileau","Anse Boileau","Je suis un homme simple, passionné par la musique et le bénévolat. La prière rythme mes journées. J'attends une femme de foi, douce et pleine de joie.",["Bénévolat","Musique","Sport","Danse"],"Catholique","Deux à trois fois par mois","Tous les jours","Au centre de ma vie","Relation sérieuse","female",33,51],
["virtuel.sc.03@profils-virtuels.yona.invalid","Fiona","Payet","female","1995-09-25","Seychelles","Beau Vallon","Beau Vallon","Fille de Dieu avant tout, je trouve ma joie dans la musique et la mode. Je chante dans la chorale de mon église. Je cherche une relation sérieuse, en vue du mariage.",["Sport","Lecture","Musique","Mode"],"Pentecôtiste","Chaque semaine","Tous les jours","Essentielle","Relation sérieuse","male",22,40],
["virtuel.ma.01@profils-virtuels.yona.invalid","Nabil","Sebti","male","1999-12-18","Maroc","Casablanca-Settat","Casablanca","Je suis un homme simple, passionné par les balades dans la nature et la lecture. Ma foi guide chacune de mes décisions. Je crois au mariage, à la fidélité et au respect.",["Lecture","Nature","Danse"],"Catholique","Chaque semaine","Plusieurs fois par semaine","Essentielle","Mariage","female",18,36],
["virtuel.ma.02@profils-virtuels.yona.invalid","Hanane","El Fassi","female","1991-04-22","Maroc","Rabat-Salé-Kénitra","Rabat","Calme et joyeuse, je partage mon temps entre mon travail et le sport. Je participe à un groupe de prière chaque semaine. J'attends un homme de foi, doux et responsable.",["Musique","Sport","Cinéma"],"Évangélique","Chaque semaine","Plusieurs fois par semaine","Essentielle","Relation sérieuse","male",26,44],
["virtuel.ma.03@profils-virtuels.yona.invalid","Jamal","Belkadi","male","1993-08-07","Maroc","Marrakesh-Safi","Marrakesh","Calme et joyeux, je partage mon temps entre mon travail et la musique. J'aide à l'organisation des sorties de l'église. Prêt à bâtir une famille fondée sur l'amour et la foi.",["Musique","Sport","Cinéma"],"Catholique","Chaque semaine","Tous les jours","Très importante","Mariage","female",24,42],
["virtuel.dz.01@profils-virtuels.yona.invalid","Katia","Khelifi","female","1997-11-11","Algérie","Algiers","Algiers","Dynamique et fidèle en amitié, je consacre mon temps libre aux balades dans la nature. Le Psaume 23 m'accompagne depuis toujours. Je crois au mariage, à la fidélité et au respect.",["Mode","Photographie","Nature","Cuisine"],"Protestante (EPA)","Deux à trois fois par mois","Plusieurs fois par semaine","Très importante","Relation sérieuse","male",20,38],
["virtuel.dz.02@profils-virtuels.yona.invalid","Djamel","Bouzid","male","1995-06-05","Algérie","Oran","Oran","Dynamique et fidèle en amitié, je consacre mon temps libre au sport. J'aime méditer la Parole chaque matin. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Louange","Sport","Voyages","Photographie"],"Catholique","Chaque semaine","Tous les jours","Au centre de ma vie","Relation sérieuse","female",22,40],
["virtuel.dz.03@profils-virtuels.yona.invalid","Amel","Rahmani","female","1991-02-09","Algérie","Constantine","Constantine","Calme et joyeuse, je partage mon temps entre mon travail et la louange. J'aime méditer la Parole chaque matin. Je souhaite rencontrer un homme sincère pour construire un foyer béni.",["Louange","Sport"],"Protestante (EPA)","Chaque semaine","Tous les jours","Essentielle","Relation sérieuse","male",26,44],
["virtuel.tn.01@profils-virtuels.yona.invalid","Skander","Jaziri","male","1979-09-28","Tunisie","Tunis Governorate","Tunis","Dynamique et fidèle en amitié, je consacre mon temps libre à la louange. La prière rythme mes journées. J'aimerais rencontrer une femme qui place Dieu au centre de sa vie.",["Danse","Bénévolat","Louange","Musique"],"Évangélique","Chaque semaine","Plusieurs fois par semaine","Au centre de ma vie","Relation sérieuse","female",38,56],
["virtuel.tn.02@profils-virtuels.yona.invalid","Wafa","Karoui","female","1987-11-16","Tunisie","Sfax Governorate","Sfax","Fille de Dieu avant tout, je trouve ma joie dans la photographie et le bénévolat. J'aime méditer la Parole chaque matin. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Photographie","Bénévolat","Voyages","Danse"],"Évangélique","Plusieurs fois par semaine","Matin et soir","Essentielle","Mariage","male",30,48],
["virtuel.tn.03@profils-virtuels.yona.invalid","Amine","Mejri","male","1977-04-19","Tunisie","Sousse Governorate","Sousse","Posé mais déterminé, j'aime la mode, la cuisine et les longues discussions. Je joue dans le groupe de louange de mon église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Musique","Cuisine","Mode"],"Catholique","Chaque semaine","Tous les jours","Très importante","Relation sérieuse","female",40,58],
["virtuel.fr.01@profils-virtuels.yona.invalid","Anne","André","female","2001-08-20","France","Île-de-France","Paris","Calme et joyeuse, je partage mon temps entre mon travail et la photographie. J'aime méditer la Parole chaque matin. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Bénévolat","Danse","Photographie"],"Adventiste","Plusieurs fois par semaine","Plusieurs fois par semaine","Au centre de ma vie","Relation sérieuse","male",18,34],
["virtuel.fr.02@profils-virtuels.yona.invalid","Nicolas","Moreau","male","1989-06-25","France","Auvergne-Rhône-Alpes","Lyon","Dynamique et fidèle en amitié, je consacre mon temps libre aux balades dans la nature. Ma foi guide chacune de mes décisions. Je cherche une relation sérieuse, en vue du mariage.",["Sport","Nature","Lecture"],"Baptiste","Chaque semaine","Matin et soir","Très importante","Relation sérieuse","female",28,46],
["virtuel.fr.03@profils-virtuels.yona.invalid","Juliette","Lefebvre","female","2000-05-30","France","Provence-Alpes-Côte d'Azur","Marseille","Chaque journée est un cadeau de Dieu : je la remplis de photographie et de cuisine. Le Psaume 23 m'accompagne depuis toujours. Je souhaite rencontrer un homme sincère pour construire un foyer béni.",["Photographie","Cuisine"],"Évangélique","Chaque semaine","Tous les jours","Au centre de ma vie","Mariage","male",18,35],
["virtuel.be.01@profils-virtuels.yona.invalid","François","Marchal","male","2000-07-01","Belgique","Brussels Capital","Brussels","Chaque journée est un cadeau de Dieu : je la remplis de voyages et de lecture. J'aide à l'organisation des sorties de l'église. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Lecture","Voyages"],"Évangélique","Plusieurs fois par semaine","Tous les jours","Essentielle","Relation sérieuse","female",18,35],
["virtuel.be.02@profils-virtuels.yona.invalid","Céline","Lejeune","female","1977-01-31","Belgique","Wallonia","Liège","Dynamique et fidèle en amitié, je consacre mon temps libre à la musique. Je suis engagée dans le groupe de jeunes de ma paroisse. J'attends un homme de foi, doux et responsable.",["Musique","Voyages"],"Protestante unie","Chaque semaine","Tous les jours","Essentielle","Relation sérieuse","male",40,58],
["virtuel.be.03@profils-virtuels.yona.invalid","Pierre","Jacobs","male","1979-09-24","Belgique","Wallonia","Namur","Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de musique. Je sers à l'accueil de mon église le dimanche. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Danse","Musique","Lecture","Bénévolat"],"Protestante unie","Plusieurs fois par semaine","Tous les jours","Essentielle","Mariage","female",38,56],
["virtuel.ca.01@profils-virtuels.yona.invalid","Valérie","Bergeron","female","1984-04-24","Canada","Quebec","Montréal","Je suis une femme simple, passionnée par la lecture et la cuisine. Je chante dans la chorale de mon église. Je cherche une relation sérieuse, en vue du mariage.",["Photographie","Voyages","Lecture","Cuisine"],"Anglicane","Chaque semaine","Matin et soir","Très importante","Mariage","male",33,51],
["virtuel.ca.02@profils-virtuels.yona.invalid","Jean-François","Gauthier","male","1986-07-05","Canada","Quebec","Québec","Je suis un homme simple, passionné par les voyages et la mode. Ma foi guide chacune de mes décisions. Je souhaite rencontrer une femme sincère pour construire un foyer béni.",["Voyages","Sport","Mode"],"Pentecôtiste","Chaque semaine","Plusieurs fois par semaine","Essentielle","Relation sérieuse","female",31,49],
["virtuel.ca.03@profils-virtuels.yona.invalid","Noémie","Pelletier","female","1989-07-10","Canada","Quebec","Laval","Chaque journée est un cadeau de Dieu : je la remplis de bénévolat et de mode. J'enseigne à l'école du dimanche. J'aimerais rencontrer un homme qui place Dieu au centre de sa vie.",["Voyages","Bénévolat","Cuisine","Mode"],"Baptiste","Chaque semaine","Plusieurs fois par semaine","Essentielle","Mariage","male",28,46]
]$seed$;
  _col text;
BEGIN
  -- 0. Profils virtuels laissés par une version précédente et absents de cette liste :
  --    retirés (uniquement des comptes virtuels : fournisseur « virtual » + adresse
  --    @profils-virtuels.yona.invalid). Il reste ainsi exactement 81 profils virtuels.
  DELETE FROM auth.users u
  WHERE u.email LIKE '%@profils-virtuels.yona.invalid'
    AND u.raw_app_meta_data ->> 'provider' = 'virtual'
    AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(_seed) e WHERE e ->> 0 = u.email);

  -- 1. Comptes sans mot de passe (le déclencheur handle_new_user crée users, profiles,
  --    préférences…). Un compte déjà présent (même adresse) n'est pas recréé.
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  SELECT
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
    e ->> 0, '', now(),
    jsonb_build_object('provider', 'virtual', 'providers', jsonb_build_array('virtual')),
    jsonb_build_object('first_name', e ->> 1, 'last_name', e ->> 2, 'is_virtual', true),
    now(), now()
  FROM jsonb_array_elements(_seed) e
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.email = e ->> 0);

  -- Colonnes texte du service d'authentification : jamais NULL (sinon l'écran des
  -- utilisateurs de Supabase peut échouer). Seules les colonnes présentes sont touchées.
  FOREACH _col IN ARRAY ARRAY[
    'confirmation_token', 'recovery_token', 'email_change_token_new', 'email_change',
    'email_change_token_current', 'phone_change', 'phone_change_token', 'reauthentication_token'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'auth' AND table_name = 'users' AND column_name = _col
    ) THEN
      EXECUTE format(
        'UPDATE auth.users SET %I = '''' WHERE %I IS NULL AND email LIKE %L',
        _col, _col, '%@profils-virtuels.yona.invalid'
      );
    END IF;
  END LOOP;

  -- 2. Profils complets, actifs et visibles.
  UPDATE public.profiles p
  SET first_name = e ->> 1,
      gender = (e ->> 3)::public.gender,
      birth_date = (e ->> 4)::date,
      country = e ->> 5,
      region = e ->> 6,
      city = e ->> 7,
      bio = e ->> 8,
      interests = ARRAY(SELECT jsonb_array_elements_text(e -> 9)),
      is_virtual = true,
      terms_accepted_at = now(),
      onboarding_step = 4,
      onboarding_completed_at = coalesce(p.onboarding_completed_at, now()),
      status = 'active',
      visibility = 'visible'
  FROM jsonb_array_elements(_seed) e
  JOIN public.users u ON u.email = e ->> 0
  WHERE p.user_id = u.id;

  UPDATE public.christian_profiles c
  SET denomination = e ->> 10,
      church_attendance = e ->> 11,
      prayer_practice = e ->> 12,
      faith_importance = e ->> 13
  FROM jsonb_array_elements(_seed) e
  JOIN public.users u ON u.email = e ->> 0
  WHERE c.user_id = u.id;

  UPDATE public.preferences pr
  SET relationship_goal = e ->> 14,
      preferred_gender = (e ->> 15)::public.gender,
      min_age = (e ->> 16)::smallint,
      max_age = (e ->> 17)::smallint
  FROM jsonb_array_elements(_seed) e
  JOIN public.users u ON u.email = e ->> 0
  WHERE pr.user_id = u.id;
END
$do$;
